---
sidebar: sidebar 
permalink: aqos-kfs.html 
keywords: aqos, qos, adaptive quality of service, quality of service 
summary: KeystoneアダプティブQoS（AQoS） 
---
= KeystoneのアダプティブQuality of Service（QoS；サービス品質
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ストレージQuality of Service（QoS；サービス品質）は、アプリケーションのパフォーマンスが安定し、予測可能な安定したものになるようにするための重要なテクノロジです。QoSを設定しないと、複数のシステムのブート用など、特定のワークロードが一定期間リソースのほとんどまたはすべてを消費し、他のワークロードに影響する可能性があります。QoSの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"^]。



== アダプティブ QoS

アダプティブQoS（AQoS）は、ボリュームサイズに基づいてTiBあたりのIOPSを動的に維持するためにKeystoneサービスで使用されます。AQoSポリシーの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["アダプティブ QoS について"^]。

KeystoneにはAQoSポリシーが用意されており、クラスタの本番環境への移行後に設定できます。システムで作成済みで使用可能な正しいAQoSポリシーにすべてのボリュームが関連付けられていることを確認する必要があります。

ONTAP ボリュームにAQoSポリシーが適用されていない場合、そのボリュームは非準拠です。QoSポリシーが設定されていないボリュームは、使用可能な入出力処理を提供する優先度リストの最後になります。ただし、使用可能な入出力操作がある場合、ボリュームは使用可能なすべてのIOを消費する可能性があります。


NOTE: ボリュームにAQoSポリシーを適用していない場合、それらのボリュームは、サブスクリプションに基づいて最高のサービスレベルで測定および課金されます。これにより、意図しないバースト料金が発生する可能性があります。



=== アダプティブQoSの設定

アダプティブQoS（AQoS）の設定はサービスレベルによって異なります。

|===


| *ポリシー名* | * Extreme *および* Extreme Tiering * | * Premium *および* Premium Tiering * | * 標準 * | * 値 * 


| *想定IOPS * | 6,144 | 2 、 048 | 128 | 64 


| *想定IOPS割り当て* 4+| 割り当て済みスペース 


| *最大IOPS * | 12,288 | 4,096 | 512 | 128 


| *最大IOPS割り当て* 4+| 割り当て済みスペース 


| * ブロックサイズ * 4+| 32K 
|===