---
sidebar: sidebar 
permalink: nkfsosm_tiering.html 
keywords: netapp, keystone, tiering, 
summary: Keystone の階層化 
---
= 階層化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flex サブスクリプションサービスには、使用頻度の低いデータを識別し、ネットアップが所有、導入、管理するコールドストレージに階層化する階層化機能が含まれています。

この階層化機能では、 NetApp FabricPool テクノロジを活用して、オンプレミスまたはオフプレミスの低コストのオブジェクトストレージ階層へデータを自動で階層化できます。この機能を使用すると、合意したサービスに基づいて、アクセス頻度の低いデータがオンプレミスまたはクラウドの低コストのストレージに自動的に階層化されます。

パートナーとテナントは、ストレージのプロビジョニング時に、 Extreme 階層化と Premium 階層化の 2 つのサービスレベルを選択することで、この機能を簡単に利用できます。Extreme 階層化には、 Standard 、 Extreme 、 Premium の各サービスレベルと同じ QoS ポリシーがあります。

アドオンの階層化機能を使用できるのは、 Extreme および Premium サービス階層のみです。ネットアップでは、データの 25% がホットであり、 75% が使用頻度が低く、コールドストレージに移動できると仮定しています。請求は、ボリュームあたりの期間が各サービスレベルで決定されます。

有効な機能は次のとおりです。

* ディスクとファイル共有についてアクセス頻度の低いデータのレポートを作成し、サービスレベルを変更するかどうかを判断できます。階層化ポリシーを移動または変更すると、コールド階層からデータにアクセスした場合にレイテンシが高くなる可能性があります。
* デスティネーション階層化がクラスタで有効になっている場合は、ボリュームのサービスレベルを「 Extreme 」と「 Premium 」から「 Extreme 」にそれぞれ変更できます。
* 同様に、ボリュームの階層化サービスレベルを非階層化に変更することもできます。
* ボリュームのバックアップを階層化サービスレベルで有効または無効にします。
* ボリュームのディザスタリカバリを階層化サービスレベルで有効または無効にします。


課金については、を参照してください link:nkfsosm_kfs_billing.html#billing-for-fabricpool-usage["FabricPool 使用のための課金"]。
