---
sidebar: sidebar 
permalink: nkfsosm_data_protection.html 
keywords: netapp, keystone, data, protection, 
summary: データ保護 
---
= データ保護
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone データ保護サービスでは、データをバックアップし、必要に応じてリカバリできます。使用可能なデータ保護サービスは次のとおりです。

* ディスクと共有のスナップショット
* ディスクおよび共有のバックアップ（サブスクリプションの一部としてデータ保護サービスが必要）
* ディスクおよび共有のディザスタリカバリ（サブスクリプションの一部としてデータ保護サービスが必要）



NOTE: バックアップサービスとディザスタリカバリサービスはアドオンサービスとして提供され、スナップショットは基本的なストレージサービスの一部として提供される。

データ保護サービスにサブスクライブしている場合は、サブスクリプションに特定のサービスレベルが割り当てられます（_Data-Protect Extreme_、_Data-Protect Premium_など）。詳細については、を参照してください https://docs.netapp.com/us-en/keystone/aiq-keystone-details.html#additional-details-for-data-protection["データ保護の詳細"]

|===
|  | 単一リージョンのSnapshot（基本的なストレージサービスの一部として利用可能） | マルチリージョンバックアップ（データ保護アドオン） | 複数リージョンのディザスタリカバリ（データ保護アドオン） 


| ユースケース | インフラの損失や障害ではなく、ユーザやアプリケーションのデータ削除や破損のリスクを軽減 | インフラの損失や障害によってプライマリボリュームのデータが完全に失われるリスクを軽減します | インフラの損失や障害が原因でプライマリボリュームのデータが完全に失われるリスクを、目標復旧時間とともに軽減します 


| ポリシー | 毎時、毎日、毎週、毎月 | 毎時、日次、週次、および月単位のSnapshotに基づいて保持するバックアップの数 | 1 時間、 4 時間、毎日 


| トポロジ | ソースのみ | バックアップ | 非同期レプリケーションターゲット 


| レプリケーションサービスレベルを指定してください。 ^1 | 該当なし | 標準 | プライマリと同じ 
|===
^1 追加のストレージ容量をサブスクライブする必要があります


NOTE: Keystoneの基本サービスのサブスクリプションでは、データは自動的にバックアップされません。アドオンのデータ保護サービスに登録し、データバックアップサービスやディザスタリカバリサービス用にシステムを設定する必要があります。お客様のストレージシステムがKeystoneサービスで管理されていない場合でも、ネットアップではストレージシステム上のデータの保護とKeystoneサービスとの接続をサポートできます。ただし、ネットアップはバックアップの失敗に対して責任を負いません。
