---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: NetApp Keystone の概要 
---
= NetApp Keystone のよくある質問（FAQ）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の質問をお寄せください。 NetApp Keystone に関するよくあるお問い合わせをご確認ください。

* NetApp Keystone とは?*

NetApp Keystone は、オンプレミスの設備投資（CAPEX）オプションのポートフォリオです。詳細については、を参照してください https://["NetApp Keystone"]。

* NetApp Keystone はお客様にどのようなメリットをもたらしますか。*

NetApp Keystone は、お客様がキャッシュフローとビジネスニーズを満たせるように、即応性、財務の柔軟性、財務リスクの軽減を実現する、 CAPEX とハイブリッドクラウド戦略の柱をつなぐ架け橋となります。

NetApp Keystone ブランドは、従来のファイナンス、リース、固定/変動オプションを含む柔軟な支払いソリューションのポートフォリオを、資金を重視するお客様向けに、Keystoneサービスに加えて提供しています。

* Keystoneサービス（OPEX、クラウドレベルのエクスペリエンス）：*** 100%のOPEXが望ましいため、資産がお客様の貸借対照表に載らない*使用量や収益に比例してコストを調整したいと考えている社内/社外のサービスプロバイダ*容量の増加が予測できないワークロード*一般的なストレージタスク（移行、機器更改、アップグレード、 など）*ワークロードをクラウドに移行する前の短期解決策 *クラウドからオンプレミスに戻す前のワークロード

* NetApp Keystone とは?*

NetApp Keystone は、柔軟性に優れた新しいオンプレミスのサブスクリプションベースの調達モデルです。お客様は、リソースの管理に伴う課題を排除し、時間のかかる調達サイクルを実施することで、価値創出までの時間を短縮できます。Keystoneサービスを利用すれば、経済性とビジネスの優先事項を連動させることができます。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["こちらをご覧ください"]。

*オンプレミスとはどういう意味ですか。*

オンプレミスは、コロケーション施設のお客様所有のデータセンタースペースまたはお客様所有のスペースとして定義されています。設置面積、消費電力、冷却コストは、お客様の負担となります。

* Keystoneサービスにはどのようなメリットがありますか？*

Keystoneサービスには次のようなメリットがあります。

* 複雑なストレージ関連タスクから IT 担当者を解放し、アプリケーション管理に集中できるようにします
* 初期投資を削減します
* オーバープロビジョニングを行わずにお客様のニーズに対応できます
* データストレージのコストをビジネスニーズやアクティビティに合わせて調整
* 複雑な組織調達手順を省略することで、インフラのプロビジョニングを簡易化
* データのセキュリティをオンプレミスで維持
* コンプライアンス、パフォーマンス、セキュリティを適切に制御できます。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["こちらをご覧ください"]。

