---
sidebar: sidebar 
permalink: nkfsosm_uscs.html 
keywords: netapp, keystone, US citizen support, USCS GSSC, Keystone Success Manager, USCS support 
summary: 米国市民サポート（ USCS ） 
---
= 米国市民サポート（USCS）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
米国市民サポート（USCS）は、NetApp Keystone サブスクリプションのアドオンサービスです。また、米国から継続的なKeystoneサービスの提供とサポートを受けることができます米国の市民土。

次のセクションを読み、このアドオンサービスに拘束されているサブスクリプションの要素を理解してください。また、NetApp Keystone 契約の条件に基づいて提供されています。脚注：disclaimer1 [ここで説明するサービスとサービスは、完全に締結されたKeystone契約の対象となり、これらに限定されます。]



== ネットアップグローバルサービスサポートセンターの監視

NetApp Global Services and Support Center（GSSC）は、お客様の製品と登録サービスの健常性を監視し、リモートサポートを提供し、Keystone Success Managerとのコラボレーションを行います。関連するKeystoneサブスクリプション注文に関連する製品を監視する担当者は、すべて米国で運用されている米国市民です土。



== Keystone Success Managerの略

Keystone Success Managerは米国米国で活動している市民土。担当業務は、NetApp Keystone 契約に明記されています。



== 展開アクティビティ

米国では、可能な場合、オンサイトおよびリモートでの導入および設置作業を行います米国の市民土。脚注：免責事項[オンサイトでの活動に適切な担当者がいるかどうかは、Keystoneシステムが導入されている地域によって異なります。]



== サポート

可能な場合は、必要なオンサイトのトラブルシューティングおよびサポート活動が米国によって実施されます米国の市民土。脚注:免責事項[]
