---
sidebar: sidebar 
permalink: nkfsfaq_operations_and_support.html 
keywords: netapp, keystone, operations, support, 
summary: 運用とサポート 
---
= Flex サブスクリプションの操作とサポート
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用しないで後で削除します

* Flex Subscription の利用状況をどのように表示しますか？ * NetApp Service Engine は、サブスクライブされているすべてのサービスに関する情報と、利用されている容量をダッシュボードに表示します。NetApp Service Engine の詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_overview.html["こちらをご覧ください"]。

* サービスに関する問題はどのように報告すればよいですか？ * NetApp Keystone サポートには、次のようなさまざまなチャネルを通じてアクセスできます。

* サポート E メール： mailto ： keystone.services@netapp.com[keystone.services@netapp.com^]
* エスカレーションメール： mailto ： keystone.escalations@netapp.com[keystone.escalations@netapp.com^]


* 新しいストレージサービスを注文できますか？ * はい、 NetApp Service Engine ポータルから新しいストレージサービスまたはストレージサービスへの拡張をリクエストできます。要求は、 NetApp Keystone 運用チームが処理してから使用可能になります。

* ストレージに関するコミットメントは即座に向上しますか？ * 必要な容量に応じて、容量がすでに導入されているかどうかを判断するか、追加の機器の発送と設置が必要かを判断します。

* ワークロードを階層間で移動できますか？ * はい、ユーザがワークロードの移動先の階層にサブスクライブされている場合、ワークロードを階層間で移動できます。ただし、原因によってパフォーマンスが低下する可能性があるため、上位の階層から下位の階層に移動することは推奨されません。このプロセスは、ファイル共有を編集し、サービスレベル設定を変更するだけで完了します。

* どのバージョンのソフトウェア（たとえば、 ONTAP ）がデフォルトとしてインストールされていますか。 * 登録されているサービス階層（ファイルサービスとブロックサービスを使用する ONTAP 、ブロック用の SANtricity 、オブジェクト用の StorageGRID など）に応じて、サポートチームはセキュリティや機能の問題なしで最新の安定版リリースをインストールします。

* 特定のソフトウェアバージョンを要求できますか。 * いいえNetApp Keystone は、顧客ベース全体でソフトウェアバージョンを標準化しています。

* ソフトウェアのアップグレードに関する情報は提供されますか。 * はい。すべての保守 / アップグレード作業は、 NetApp Keystone 成功マネージャがお客様と相互に合意した時間に連絡し、スケジュールされます。
