---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: NetApp Keystone の概要 
---
= NetApp Keystone のよくある質問（FAQ）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の質問をお寄せください。 NetApp Keystone に関するよくあるお問い合わせをご確認ください。

* NetApp Keystone とは?*

NetApp Keystone は、 NetApp Keystone Flex Pay （ Flex Pay ）と NetApp Keystone Flex Subscription （ Flex Subscription ）で構成される、オンプレミスの CAPEX （設備投資）ソリューションのポートフォリオです。

* * Flex Pay ：従来のファイナンス、リース、固定 / 可変オプションなどの決済ソリューションのポートフォリオ。お客様のキャッシュフローニーズに対応します。
* * フレックスサブスクリプション： * 従量課金制のサブスクリプションベースサービス。オンプレミスでクラウドレベルのエクスペリエンスを提供し、結果ベースのサービスオプション（ネットアップが運用）を提供します。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/index.html["こちらをご覧ください"]。


* NetApp Keystone はお客様にどのようなメリットをもたらしますか。*

NetApp Keystone は、お客様がキャッシュフローとビジネスニーズを満たせるように、即応性、財務の柔軟性、財務リスクの軽減を実現する、 CAPEX とハイブリッドクラウド戦略の柱をつなぐ架け橋となります。

NetApp Keystone ブランドは、従来のファイナンス、リース、固定 / 可変オプションなどの柔軟な決済ソリューションのポートフォリオを提供しており、現金意識の高いお客様には Flex サブスクリプションを提供しています。

* * フレックス・ペイ（金融面での柔軟性、決済ソリューション）： *
+
** 資産のタイトルを所有したいが、支払い / 財務の柔軟性（レンタルモデル、リース、ローン、分割）が必要
** 契約を有効にするための外部データ接続オプションがない厳格なセキュリティ要件
** ワークロードの容量は予測可能で、 CAPEX の予算に合わせて拡張できます
** 資産利用率の高い、管理の行き届いたインフラ
** ストレージを物理容量単位で調達し、効率化のメリットを活用することを希望します


* * フレックスサブスクリプション（ OPEX 、クラウドレベルのエクスペリエンス）： *
+
** 運用コストを 100% にすることをお勧めします。そのため、アセットが顧客の貸借対照表に表示されることはありません
** 使用状況や収益に応じたコストを検討している社内 / 社外のサービスプロバイダ
** 容量の予測不能な増加を伴うワークロード
** 一般的なストレージタスク（移行、機器更改、アップグレードなど）から IT リソースを再割り当て
** ワークロードをクラウドに移行する前の短期的な解決策
** ワークロードをクラウドからオンプレミスに戻すことが可能




* Flexサブスクリプションとは？*

Flex サブスクリプションは、柔軟性に優れた、サブスクリプションベースの新しい購入モデルです。お客様は、リソースの管理に伴う課題を排除し、時間のかかる調達サイクルを実施することで、価値創出までの時間を短縮できます。Flex サブスクリプションを使用すると、お客様は経済性をビジネス上の優先事項に合わせることができます。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["こちらをご覧ください"]。

*オンプレミスとはどういう意味ですか。*

オンプレミスは、コロケーション施設のお客様所有のデータセンタースペースまたはお客様所有のスペースとして定義されています。設置面積、消費電力、冷却コストは、お客様の負担となります。

* Flexサブスクリプションサービスの利点は何ですか。*

Flex サブスクリプションサービスには、次のような利点があります。

* 複雑なストレージ関連タスクから IT 担当者を解放し、アプリケーション管理に集中できるようにします
* 初期投資を削減します
* オーバープロビジョニングを行わずにお客様のニーズに対応できます
* データストレージのコストをビジネスニーズやアクティビティに合わせて調整
* 複雑な組織調達手順を省略することで、インフラのプロビジョニングを簡易化
* データのセキュリティをオンプレミスで維持
* コンプライアンス、パフォーマンス、セキュリティを適切に制御できます。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["こちらをご覧ください"]。

