---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Keystone Performancesサービスレベル 
---
= サービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystoneは、事前定義されたパフォーマンスサービスレベル（サービスレベル）またはサブスクリプションベースのレートプランでデータストレージ容量を提供します。Keystoneサービスで管理される各ボリュームはサービスレベルに関連付けられます。

各サービスレベルは、I/O密度（IOPS/TiB/ボリューム）で定義されます。パフォーマンス（1秒あたりの入出力操作[IOPS]）と割り当て済みストレージ容量（TiB）の比率で、ボリュームあたりの平均レイテンシでのIOPS/TiBです。

ボリュームのI/O密度は1時間ごとに計算され、ピークI/O密度が報告されます。ボリュームのI/O密度レポートは毎月生成されます。

サービスレベルは、ストレージ環境、およびストレージと消費のニーズに基づいて選択します。基本サービスレベルは、デフォルトで設定されています。特定のサービスを選択した場合は、他のサービスレベルも追加で利用できます。たとえば、データ保護サービスの場合、_Data-Protect <base-service-level>_サービスレベルがサブスクリプションに割り当てられます。

ここには、ファイル、ブロック、オブジェクトの各ストレージタイプの基本サービスレベルを示します。



== ファイルストレージのサービスレベル

* サポートされているプロトコル * ： NFS 、 CIFS 、 iSCSI 、 FC

|===


| * サービスレベル * | * エクストリーム * | * プレミアム * | * 標準 * | * 値 * 


| * ワークロードタイプ * | 分析、データベース | VDI 、仮想化アプリケーション、ソフトウェア開発 | ファイル共有、 Web サーバ | バックアップ 


| *ボリュームあたりの割り当て済み論理容量（TiB）あたりの最大IOPS * | 12,288 | 4,096 | 512 | 該当なし 


| *ターゲットIOPS/ボリュームあたりの割り当て済み論理TiB数* | 6,144 | 2 、 048 | 128 | 該当なし 


| *ボリュームあたりの割り当て済み論理容量（TiB）あたりの最大MBps * | 384 | 128 | 16 | 該当なし 


| *平均レイテンシー* | 1 ミリ秒未満 | 2 ミリ秒未満 | 17 ミリ秒未満 | 該当なし 


| *ブロックサイズ* 4+| 32K 
|===


=== ファイルストレージのサービスレベルの詳細

基本のサービスレベルメトリックは、次の条件によって異なります。

* ファイルストレージとブロックストレージのサービスレベルはONTAP 9.7以降をサポートします。
* サービスレベルのIOPS/TiB/ボリューム、MBPS/TiB/ボリューム、およびレイテンシの値は、ボリュームに格納されている論理データの量、32KBのブロックサイズ、およびランダムなI/O処理の70%と30%の書き込みI/O処理に基づきます。
* 実際のIOPS/TiB/ボリュームとMBPS/TiB/ボリュームは、実際のブロックサイズまたは想定されるブロックサイズ、システムワークロードの同時実行数、または入出力処理によって変わります。
* レイテンシには、次の要素は含まれません。
+
** アプリケーションまたはホストのレイテンシ
** コントローラポートとの間のお客様のネットワークレイテンシ
** FabricPool の場合のオブジェクトストアへのデータ転送に関連するオーバーヘッド
** レイテンシはQoSによって自動的に適用され、IOがサービスレベルの上限内に維持されます


* レイテンシの値は、MetroCluster 書き込み処理には適用されません。これらの書き込み処理は、リモートシステムの距離に依存します。
* ストレージシステム上の1つ以上のボリュームにAQoSポリシーが割り当てられていない場合、それらのボリュームは非準拠ボリュームとみなされ、それらのシステムに適用されるターゲットサービスレベルはありません。
* 想定IOPS_は、階層化ポリシーが「none」に設定されていて、ブロックがクラウドにない場合にのみFabricPool のターゲットになります。想定IOPS_は、SnapMirror同期関係にないボリュームを対象としています。
* Keystoneの順序で決定されるように、導入されているすべてのコントローラ間でワークロードIO処理を分散させる必要があります。




== ブロックストレージのサービスレベル

* サポートされているプロトコル * ： FC 、 iSCSI

|===


| * サービスレベル * | * エクストリーム * | * プレミアム * | * 標準 * 


| * ワークロードタイプ * | HPC | ビデオ監視 | バックアップ 


| * ターゲット IOPS/ TiB * 3+| 該当なし 


| * 最大 IOPS / TiB * | 5,500です | 4 、 000 名 | 該当なし 


| * 最大スループット MBps （ 32KB / IOP ） * | 43 | 31. | 該当なし 


| *平均レイテンシー* | 0.5 ミリ秒未満 | 0.5 ミリ秒未満 | 該当なし 


| *ブロックサイズ* 3+| 32K 
|===


== オブジェクトストレージのサービスレベル

* サポートされるプロトコル * ： S3

|===


| * サービスレベル * | オブジェクト 


| * ワークロードタイプ * | メディアリポジトリ、アーカイブ 


| * ターゲット IOPS/ TiB * | 該当なし 


| * 最大 IOPS / TiB * | 該当なし 


| * 最大スループット MBps （ 32KB / IOP ） * | 該当なし 


| *平均レイテンシー* | 該当なし 
|===