---
sidebar: sidebar 
permalink: nkfsosm_netapp_global_services_and_support_center_@gssc@.html 
keywords: netapp, keystone, global, services, support, center, gssc, 
summary: ネットアップグローバルサービスおよびサポートセンター（ GSSC ） 
---
= Keystoneサービスオペレーション
:allow-uri-read: 


[role="lead"]
NetApp Keystone Keystoneサービスは、ネットアップグローバルサービスおよびサポートセンター（GSSC）、NetApp Keystone サクセスマネージャー、NetApp Keystone サービスデリバリマネージャーを活用して実施されます。



== ネットアップグローバルサービスおよびサポートセンター（ GSSC ）

ネットアップは、 NetApp Keystone のお客様に運用サービスをリモートで提供しています。これらのサービスには、資産管理と構成管理、容量とパフォーマンス管理、変更管理、イベント、インシデントと問題管理、サービスリクエストの履行、レポートなど、ストレージ管理アクティビティ全体にわたる運用上のさまざまな分野が含まれます。ネットアップは、必要に応じて入手可能な管理の状態と証拠を提示します。



== 追加情報とサポートの連絡先

ネットアップグローバルサービスおよびサポートセンター（GSSC）チームは、主にNetApp Keystone のお客様に対するサービスをサポートします。

ネットアップサービスエンジンポータル（ * Support > Service Requests * ）から直接、問題の詳細情報を参照してチケットを発行し、サポートを依頼します。

以下の情報を使用して、サポートチームに連絡することもできます。

* グローバルサービス担当者：https://www.netapp.com/us/contact-us/support.aspx[]
* エスカレーションが必要なオープンケース / チケットをお持ちの場合は、次のいずれかのアドレスに電子メールを送信してください： Keystone.services@netapp.com Keystone.escalations@netapp.com
* ネットアップでは、クラウドベースのリモートゲートウェイ解決策である OpsRamp を使用して、トラブルシューティングのために NetApp Keystone 環境をプロアクティブに監視し、接続します。OpsRamp の詳細については、を参照してください https://www.opsramp.com/#[]。



NOTE: パートナーが運用するモデルでは、テナントおよびサブテナントのサービスリクエストがパートナーのサービスデスクに割り当てられます。OpsRamp と GSSC アプリケーションとの統合はパートナーのサポートツールで可能です。L3 の問題のみが GSSC を通じてネットアップにエスカレーションされます。

このドキュメントに記載されている情報の詳細については、以下のドキュメントや Web サイトを参照してください。

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* ネットアップの製品マニュアルhttps://docs.netapp.com["https://docs.netapp.com"^]

