---
sidebar: sidebar 
permalink: nkfsfaq_keystone_subscription.html 
keywords: netapp, keystone, subscription, subscriptions, 
summary: NetApp Keystone サブスクリプション 
---
= NetApp Keystone に関する FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の質問は、NetApp Keystone Keystoneサービスに関するよくある質問に対する回答です。

* NetApp Keystone の一部として提供される機能* NetApp Keystone は、ブロック、ファイル、オブジェクトのデータサービスを対象としたサブスクリプションベースのサービスです。オンプレミスに導入でき、ネットアップ、パートナー、お客様が運用できます。

* Keystoneの一部として提供されるストレージサービス*詳細については、を参照してください link:nkfsosm_performance.html["サービスレベル"]

*どのようなアドオンサービスがサポートされていますか？* FabricPool による高度なデータ保護（バックアップとディザスタリカバリ）とハイブリッドクラウド階層化は、追加料金で選択できるアドオンサービスです。

*ネットアップがサービスに対してどのようなサービスレベルを保証しますか？*ネットアップが運用するシナリオでは、プロビジョニングされたストレージでNetApp Keystone が1TiBのIOPSを保証し、各サービスレベルでのレイテンシを保証します。

* Keystoneは何に対応していますか？* Keystoneは単一のサイトまたは単一のデータセンターに対応しており、さまざまなサービスレベルで構成できます。

*階層化サービス・レベルの高度な階層化とプレミアム階層化のメリットは何ですか*階層化は'階層化とプレミアム階層化のサービス・レベルで有効化されており'ストレージの設置面積と関連コストを削減できますネットアップでは、データの 25% がホットで、残りの 75% は使用頻度やコールドデータが低く、コールドストレージに移動します。また、使用状況レポートを確認して、データへのアクセス頻度を把握したり、情報に基づいて階層化サービスを有効にしたりすることができます。

*パートナー様はネットアップから購入した容量よりも多くの容量をお客様に販売できますか？*テナントサブスクリプションは、パートナー様が購入した容量に制限されません。パートナー様は、ネットアップから購入した容量よりも多くの容量をお客様に販売できます。購入済み容量を超える容量はオーバーサブスクリプションと呼ばれます。

*バースト容量とは何ですか？*コミット容量を最大20%上回る使用量を増減できます。バースト時の使用容量は 1 日単位で測定され、使用時にのみ課金されます。たとえば、コミット済み容量が 100TiB の場合、バースト時に最大 120TiB を使用できます。

*バースト時にプレミアム料金が発生しますか？*バースト時の容量使用率は、コミット済み容量と同じレートで、コミット済み容量の20%を超える使用率は、50%のプレミアム料金で請求されます。

*バースト容量のメリットは何ですか?*バースト容量により、長期的な契約とは異なり、ストレージをオンデマンドで柔軟に消費できます。

*バースト時の容量はどのようにテナントに割り当てられますか。*バースト時の容量は、要件に基づいてさらにお客様に割り当てられるパートナー様に割り当てられます。

*コミット済み容量とバースト容量の使用状況はどこで確認できますか。*
Active IQデジタルアドバイザのダッシュボード。

*コミット済み容量の使用率が一定の割合に達した場合、通知はありますか？*
はい。管理ツールは、Active IQデジタルアドバイザのダッシュボードで容量使用量を通知します。

* Keystoneの使用状況を表示するにはどうすればよいですか？*
Active IQデジタルアドバイザは、サブスクライブされているすべてのサービスと消費量に関する情報を含むダッシュボードビューを提供します。

* サービスに関する問題はどのように報告すればよいですか？ * NetApp Keystone サポートには、次のようなさまざまなチャネルを通じてアクセスできます。

* サポート E メール： mailto ： keystone.services@netapp.com[keystone.services@netapp.com^]
* エスカレーションメール： mailto ： keystone.escalations@netapp.com[keystone.escalations@netapp.com^]


*新しいストレージサービスを注文できますか？*
はい。新しいストレージサービスまたはストレージサービスへの拡張は、KSMを通じて要求できます。要求は、 NetApp Keystone 運用チームが処理してから使用可能になります。

* ストレージに関するコミットメントは即座に向上しますか？ * 必要な容量に応じて、容量がすでに導入されているかどうかを判断するか、追加の機器の発送と設置が必要かを判断します。

* ワークロードを階層間で移動できますか？ * はい、ユーザがワークロードの移動先の階層にサブスクライブされている場合、ワークロードを階層間で移動できます。ただし、原因によってパフォーマンスが低下する可能性があるため、上位の階層から下位の階層に移動することは推奨されません。このプロセスは、ファイル共有を編集し、サービスレベル設定を変更するだけで完了します。

*デフォルトでインストールされるソフトウェアバージョン（ONTAP など）は何ですか？*サブスクリプションしているサービスレベル（ファイルサービスとブロックサービスを使用するONTAP 、ブロックサービス用SANtricity 、オブジェクト用StorageGRID など）に応じて、サポートチームが最新の安定版リリースをインストールします。セキュリティや機能の問題は発生しません。
