---
sidebar: sidebar 
permalink: nkfsosm_kfs_billing.html 
keywords: netapp, keystone, billing, flex subscription billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing 
summary: Keystone Flex サブスクリプションの課金 
---
= Flex サブスクリプションの課金
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flex サブスクリプション（ Flex サブスクリプション）の請求は、コミット済み容量とバースト消費に基づいています。

▽コミット済み容量およびバースト時の使用容量については、を参照してください。△ link:nkfsosm_keystone_service_capacity_definitions.html["Flex サブスクリプションサービスの容量の定義"]。

課金情報の詳細を表示する方法については、を参照してください link:sewebiug_billing.html["請求を表示します"]。



== コミット済み容量に基づく請求

コミット済み容量とは、関係者（ネットアップ / パートナー様とお客様）が合意した 1 回のサブスクリプションでの各種サービスの容量を指します。この容量は、 Flex サブスクリプションの注文ごとに記載され、実際の消費量にかかわらず請求されます。

ネットアップは、 Flex Subscription サービスの導入の一環として、サービスの消費状況を継続的に監視し、測定します。5 分ごとに消費レコードが生成され、サブスクリプションの現在の消費容量が詳細に表示されます。これらのレコードは、請求書および使用状況レポートを生成するために請求期間にわたって集計されます。



== バースト消費に基づく請求

使用済み容量が特定のパフォーマンスサービスレベルのコミット済み容量を超えると、バースト消費量が記録され、それに応じて料金が適用されます。このプロセスは、生成される消費レコードごとに実行されます。したがって、バースト消費量は、オーバー消費容量の量と時間の両方を、コミット済み容量の上に反映したものです。



== 請求スケジュール

Flex サブスクリプションサービスは、月単位および年単位で課金されます。

請求書は毎月送付されます。サービスが利用可能になった月については、請求書が翌月に送付されます。たとえば、 1 月に使用したサービスの請求書は、 2 月初めに送付されます。この請求書には、コミット済み容量の料金と、該当する場合はバースト時の使用料が含まれます。

コミット済み容量の最小支払額については、各サブスクリプション年の開始時に請求書が生成されます。サブスクリプションの開始日に生成されます。別の請求書は、サブスクリプション四半期の終了時に送信され、当該四半期に発生したバースト使用の適用可能な料金を合計したものです。サブスクリプション中にコミット済み容量が変更された場合、そのサブスクリプション年の残りの期間の年間年間の比例した最小支払額について、コミット済み容量の変更が有効になった日に請求書が送信されます。



== Flex サブスクリプション課金のその他のシナリオ

Flex サブスクリプションの課金にはいくつかのシナリオがあります。これらのシナリオについて理解しておく必要があります。



=== クローニングされたボリュームに対する請求

ONTAP でボリュームがクローニングされている場合に、データのバックアップとリストアに使用すると、追加の支払いなしでクローンを引き続き使用できます。ただし、ビジネスで他の目的に使用されていたクローンボリュームには、広範囲の期間料金がかかります。

次の点に注意してください。

* クローンボリュームの消費は、クローンの作成から 24 時間以内には考慮されないため、この間に料金は発生しません。
* 新しいデータがボリュームに書き込まれない場合、 Standard および Value Performance サービスレベルのクローンボリュームの消費は考慮されません。たとえば、バックアップとリストアのユースケースでは、クローンボリュームのデータのバックアップやリストアによって、クローンボリューム自体のデータが変更されることはなく、消費とはみなされません。




=== MetroCluster の請求

高度なデータ保護： NetApp MetroCluster を使用して、物理的に分離された 2 つのクラスタ間でデータをミラーリングしますMetroCluster のミラーされたアグリゲートでは、データが各クラスタに 1 回ずつ、 2 回書き込まれます。Flex サブスクリプションサービスでは、各サイドで個別に消費量が課金されるため、 2 つの同一の消費レコードが生成されます。ONTAP System Manager （ System Manager ）または Active IQ Unified Manager （ Unified Manager ）を使用してクラスタを監視する場合は、これらのツールの使用量とフレックスサブスクリプションの使用量が一致しないことがあります。System Manager と Unified Manager では、ミラーリングされた（リモートの）クラスタにボリュームが報告されません。報告される消費指標の半分は、フレックスサブスクリプションサービスから報告されます。

たとえば、サイト A とサイト B は MetroCluster 構成にセットアップされます。サイト A に 10TB のボリュームを作成すると、サイト B には同一の 10TB ボリュームが作成されますFlex サブスクリプションでは、ボリュームが区別され、各サイトに 10TB の追加消費が記録されるため、合計で 20TB が増加します。System Manager と Unified Manager で、サイト A に作成された 10TB のボリュームが報告されます



=== 一時ボリュームについての請求

ボリュームを移動する際に、 ONTAP によって一時（ TMP ）ボリュームが作成されることがあります。これらの一時ボリュームは一時的なものであり、これらのボリュームの消費量は課金対象として測定されません。



=== 課金およびアダプティブ QoS ポリシー

Flex Subscription では、パフォーマンスサービスレベルに基づいて消費量を測定します。各パフォーマンスサービスレベルは、特定のアダプティブ QoS ポリシーに関連付けられています。展開中に、加入している Flex サブスクリプションサービスの各 QoS ポリシーの詳細が通知されます。ストレージ管理処理の実行中に予期しない課金を避けるため、ボリュームには、サブスクライブしたパフォーマンスサービスレベルに従って適切な QoS ポリシーが割り当てられていることを確認してください。ONTAP の QoS ポリシーの詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS の概要を使用してスループットを保証"]。
