---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: サービス提供の詳細 
---
= Flex サブスクリプションサービスの詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の質問では、 NetApp Keystone Flex サブスクリプションサービスについてよくお問い合わせいただく質問を記載しています。



=== 最小コミット済み容量

NetApp Keystone フレックスサブスクリプション（ Flex サブスクリプション）の最小コミット容量は、 1 つ以上のサービス階層のサイトあたり 100TiB です。



=== Flex サブスクリプション契約の一般的な期間はどれくらいですか。

Flex サブスクリプションは、 12 、 24 、および 36 か月の期間を提供します。



=== ストレージへのアクセス方法

ネットアップが運用する（標準）モデルでは、ストレージコントローラ（ ONTAP システムマネージャまたはシステムへの管理アクセス）はネットアップが所有および管理します。ストレージの監視と管理には、 NetApp Service Engine の UI および API を使用する必要があります。ネットアップサービスエンジンの UI と API が主に課金機能に使用されるお客様管理（または Lite ）環境では、 Active IQ Unified Manager や ONTAP System Manager などのストレージコントローラにアクセスして、 ONTAP クラスタに直接アクセスできます。



=== サービスの管理方法を教えてください。

NetApp Service Engine は、ストレージのプロビジョニングやサービス使用状況のレポートの取得に使用できるオーケストレーションおよび管理ツールです。



=== サブスクリプションのコミット済み容量を増やすにはどうすればよいですか？

容量追加要求は、ネットアップサービスエンジン管理ツールまたは NetApp Keystone 成功マネージャから送信できます。



=== 容量を増やすことで用語は延びていますか？

既存の期間に追加されるのはすべて、サブスクリプションの過去 90 日間にリクエストが行われた場合を除き、既存の期間と同じ期間です。この場合、期間は少なくとも 12 カ月延長する必要があります。



=== 新しいサブスクリプションには、新しい年単位の期間を追加できる柔軟性がありますか。

はい。新しいサブスクリプションでは、既存のサブスクリプションとは別に新しい条件を設定できます。



=== テナントのサブスクリプション期間は、パートナーのサブスクリプション期間を超えて延長できますか？

テナントサブスクリプションは、パートナーの現行の Flex サブスクリプション期間を超えて延長できます。サブスクリプションが作成されると警告が表示され、使用状況レポートにも表示されます。



=== 同じ ONTAP クラスタで複数のサブスクリプションを混在させることはできますか。

いいえ。各クラスタは特定のサブスクリプションに割り当てられます。



=== 監視と運用の担当者

ネットアップが実施するサービスについては、合意された期待に沿ってサービスを提供できるように、ネットアップがリモートでインフラを監視する責任があります。

パートナーが運営するサービスについては、合意された期待に沿ってサービスが提供されるように、パートナーがインフラをリモートで監視する責任があります。

お客様が実施するサービスについては、インフラの監視とネットアップへの問題の報告は、顧客自身で行う



=== サービスを早期に終了した場合はどうなりますか？

サービスの最低契約期間は 12 カ月です。サービスを早期にキャンセルした場合は、残存価額を事前に支払う必要があります。



=== 最初の期間が終了した後、購入に転換する機会はありますか？

いいえこの特典には、購入に切り替えるオプションは含まれていません。また、以前に購入されたネットアップ製品はこのプログラムの対象外です。



=== 特定のソフトウェアバージョンをリクエストできますか？

いいえNetApp Keystone は、顧客ベース全体でソフトウェアバージョンを標準化しています。



=== ソフトウェアのアップグレードに関する情報は提供されますか？

はい。すべての保守 / アップグレード作業は、 NetApp Keystone 成功マネージャがお客様と相互に合意した時間に連絡し、スケジュールされます。
