---
sidebar: sidebar 
permalink: nkfsosm_keystone_service_capacity_definitions.html 
keywords: netapp, keystone, service, capacity, definitions, 
summary: Keystone サービスの容量の定義 
---
= Flex サブスクリプションサービスの容量の定義
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flex サブスクリプション（ Flex サブスクリプション）サービスの容量は次のとおりです。

* * 論理容量。 * お客様が Flex サブスクリプションインフラストラクチャに配置したデータ：
+
** すべての Flex サブスクリプション容量は、論理容量を参照します。
+
たとえば、 1TiB のファイルが Flex サブスクリプションインフラに格納された場合、少なくとも 1TiB 以上の容量を購入する必要があります。



* * コミット済み容量。 * 期間中に毎月請求される最小論理容量：
+
** 容量は各パフォーマンスレベルにコミットされます。
** この期間中はコミット済み容量を減らすことはできません。
** コミット済み容量および追加のパフォーマンスレベルは、期間中に追加できます。


* * バースト時の容量 * 論理容量、コミット済み容量を超過：
+
** Flex サブスクリプションサービスでは、コミット済み容量を 20% 超える容量が提供されます。
** バースト時の容量は柔軟に消費でき、 1 日あたりの平均消費量に基づいて課金されます。
** バースト時の容量は 20% まで、コミット済み容量と同じ速度で充電されます。
** バースト時の容量がコミット容量の 20% を超えると、プレミアム料金が発生します。20% を超えるその他のバースト要件については、サポートにお問い合わせください。


* * 使用済み / プロビジョニング済み容量。 * 設定されているすべてのボリュームサイズの合計：
+
** 容量は、ボリュームの作成、変更、削除、または自動拡張によってプロビジョニングされます。
** Snapshot とクローンが含まれます。
** プロビジョニングされた容量に格納されているデータ量は考慮されません。
** ディスクに実際に書き込まれるデータ量は考慮されません。


* * 請求済み容量。 * 請求書ごとの請求額 = （コミット済み容量 [TiB ] * コミット済み率 [TiB / TiB ] ） + （ 1 日あたりの平均プロビジョニング済みバースト容量 [TiB ] * バーストレート [TiB / TiB ] ）：
+
** 月単位の課金には、コミット済み容量に基づく最小料金が含まれます。
+
月単位の請求額は、日単位の平均バースト容量の消費量に基づいて、最小料金を超えます。




