---
sidebar: sidebar 
permalink: nkfsosm_site_requirements.html 
keywords: netapp, keystone, sire, requirements, 
summary: Keystone サイトの要件 
---
= サイト要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
環境で NetApp Keystone Flex Subscription （ Flex サブスクリプション）サービスを有効にするには、スペース、ラック、 PDU 、電源、 さらに、ネットワークとセキュリティの追加要件については後述します。



== スペース

Flex サブスクリプションインフラストラクチャ機器をホストするためのフロアスペース（お客様が用意）。ネットアップは、最終的な構成に基づいて重量仕様を提供します。



== ラック

お客様が運用するサービスには、 4 柱式ラックが用意されています（お客様が用意）。ネットアップが提供するサービスでは、要件に応じて、ネットアップまたはお客様がラックを用意できます。ネットアップのディープラックは 42 個あります。



== PDU

C13 コンセントが十分にある、 2 つの個別の保護された回路に接続された Power Distribution Unit （ PDU ；配電ユニット）を提供する必要があります。お客様が実施するサービスでは、場合によっては C19 コンセントが必要です。ネットアップが提供するサービスでは、要件に応じて、ネットアップまたはお客様が PDU を提供できます。



== 電源

必要な電源を投入する必要があります。ネットアップでは、 200V 定格（標準 A 、最大 A 、標準 W 、最大 W 、電源コードタイプ、 および数量）。最終構成に基づきます。すべてのコンポーネントに冗長な電源装置があります。キャビネット内の電源コードはネットアップが提供します。



== 冷却

ネットアップでは、最終的な構成と要件に基づいて、冷却要件の仕様（実効 BTU 、最大 BTU ）を提供しています。



== ネットワーキング

お客様の要件や使用しているストレージコントローラに応じて、ネットアップはお客様のサイトで 10Gb 、 40GB 、および 100GB の接続を提供できます。

ネットアップが提供する Flex サブスクリプションインフラデバイスにのみ必要なトランシーバを提供します。お客様のデバイスに必要なトランシーバを支給し、ネットアップが提供する Flex サブスクリプションインフラデバイスにケーブル接続する必要があります。
