= Keystone サービスの容量の定義
:allow-uri-read: 


--definitionsサイドバー：sidebar permalink：nkfsosm_keystone_service_capacity_definitions.html keywords：netapp、keystone、service、capacity、definitions、 バースト、コミット済み容量、消費容量、課金対象容量の概要：Keystoneサービス容量の定義--



= Keystone サービスの容量の定義

[role="lead"]
NetApp Keystone サービスの容量は次のとおりです。



== 論理容量

これは、お客様がKeystoneインフラに配置したデータです。Keystoneのすべての容量は論理容量を表します。たとえば、1TiBのファイルがKeystoneインフラに格納された場合、少なくとも1TiB以上の容量を購入する必要があります。



== コミット済み容量

期間中に毎月請求される最小論理容量。

* 容量は各サービスレベルにコミットされます。
* この期間中はコミット済み容量を減らすことはできません。
* コミット済み容量および追加のサービスレベルは、期間中に追加できます。




=== コミット済み容量に対する変更

サブスクリプションの期間中に、コミット済み容量を変更できます。ただし、前提条件は次のとおりです。

* コミット済み容量を削減することはできません
* 12 カ月間延長する場合を除き、コミット済み容量はサブスクリプションの有効期限の 90 日前に増やすことはできません。
* コミット済み容量の変更は、 NetApp Service Engine インターフェイスまたは Keystone Success Manager を通じて要求できます。変更の要求については、を参照してください link:sewebiug_raise_a_service_request.html["サービスリクエストを提出します"]。




== バースト時の容量

コミット済み容量を超えている論理容量です。次の点に注意してください。

* Keystoneサービスは、コミット済み容量を20%超える容量を提供します。
* バースト時の容量は柔軟に消費でき、 1 日あたりの平均消費量に基づいて課金されます。
* バースト時の容量は 20% まで、コミット済み容量と同じ速度で充電されます。
* バースト時の容量がコミット容量の 20% を超えると、プレミアム料金が発生します。20% を超えるその他のバースト要件については、サポートにお問い合わせください。




== 使用済み / プロビジョニング済み容量

使用済み容量は、サービスで現在使用されているストレージの容量（ TiB ）です。Keystoneサービスでは、特定のサービスレベルですべてのボリュームのプロビジョニング済みサイズの合計（使用済み論理容量や物理容量ではない）が、そのサービスレベルの消費容量とみなされます。これには、次のもの

* ボリュームの作成、変更、削除、または自動拡張によってプロビジョニングされた容量。
* Snapshot コピーとクローン：
+

NOTE: プロビジョニングされた容量に格納されているデータの量、またはディスクに実際に書き込まれたデータの量は考慮されません。





== 請求容量

月次請求 = （コミット済み容量 [TiB ] * コミット率 [TiB / TiB ] ） + （日単位の平均プロビジョニングバースト容量 [TiB ] * バーストレート [TiB / TiB ] ）月単位の課金には、コミット済み容量に基づく最小料金が含まれます。

月単位の請求額は、日単位の平均バースト容量の消費量に基づいて、最小料金を超えます。課金の詳細については、を参照してください link:nkfsosm_kfs_billing.html["Keystoneの課金"]。
