---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, 
summary: Keystone Flex サブスクリプションのパフォーマンス 
---
= サービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flexサブスクリプション（Flexサブスクリプション）は、事前定義されたパフォーマンスサービスレベル（サービスレベル）で容量を提供します。

各サービスレベルは、I/O密度によって定義されます。これは、パフォーマンス（1秒あたりの入出力処理数（IOPS））と使用済みストレージ（TiBあたりの格納データ）の比率で、単位はIOPS/ TiBです。

Flexサブスクリプションサービスで管理される各ボリュームは、サービスレベルに関連付けられています。各ボリュームで使用されるすべての I/O 処理と使用済みストレージは、ボリュームの I/O 密度の計算に考慮されます。

次の表に、サービスレベルを示します。



== 異なるストレージタイプのサービスレベル

ファイル、ブロック、オブジェクトストレージのサービスレベルを次に示します。

ボリュームレベルでの I/O 密度の計算結果は、過去 1 週間のピーク I/O 密度を示すようにレポートされます。ピークパフォーマンスは 1 時間間隔で決定されます。ボリュームごとの I/O 密度レポートは、各サービスレベルの準拠状況を判断するために毎月生成されます。



=== ファイルサービス

* サポートされているプロトコル * ： NFS 、 CIFS 、 iSCSI 、 FC

|===


| * サービスレベル * | * エクストリーム * | * プレミアム * | * 標準 * | * 値 * 


| * ワークロードタイプ * | 分析、データベース | VDI 、仮想化アプリケーション、ソフトウェア開発 | ファイル共有、 Web サーバ | バックアップ 


| * ターゲット IOPS/ TiB * | 6,144 | 2 、 048 | 128 | 該当なし 


| * 最大 IOPS / TiB * | 12,288 | 4,096 | 512 | 該当なし 


| * 最大スループット MBps （ 32KB / IOP ） * | 384 | 128 | 16 | 該当なし 


| * 遅延 * | 1 ミリ秒未満 | 2 ミリ秒未満 | 17 ミリ秒未満 | 該当なし 


.2+| * 最小容量 * ^ 1 、 2 ^ 4+| 100TiB ^1 ^ 


| 15TiB ^2^ | 25TiB ^2^ | 50TiB ^2^ | 50TiB ^2^ 
|===

NOTE: ^1 ^ NetApp Direct Opportunityに必要なファイル共有レベルとブロックサービスレベルを組み合わせた場合、1年以上の期間と100TiB以上の最小容量。^2^ チャネル主導の販売機会用に選択された各サービス階層ごとに、最低 1 年間の契約期間と最小規定容量。



=== ブロックストレージ

* サポートされているプロトコル * ： FC 、 iSCSI

|===


| * サービスレベル * | * エクストリーム * | * プレミアム * | * 標準 * 


| * ワークロードタイプ * | HPC | ビデオ監視 | バックアップ 


| * ターゲット IOPS/ TiB * 3+| 該当なし 


| * 最大 IOPS / TiB * | 5.500 | 4 、 000 名 | 該当なし 


| * 最大スループット MBps （ 32KB / IOP ） * | 43 | 31. | 該当なし 


| * 遅延 * | 0.5 ミリ秒未満 | 0.5 ミリ秒未満 | 該当なし 


| * 最小容量 * ^ 1 、 2 ^ | 100TiB ^3^ | 100TiB ^3^ | 300TiB ^3^ 
|===

NOTE: ^1 ^ NetApp Direct Opportunityに必要なファイル共有レベルとブロックサービスレベルを組み合わせた場合、1年以上の期間と100TiB以上の最小容量。^2^ チャネル主導の販売機会用に選択されたサービス階層ごとの最低 1 年間の契約期間と最小規定容量。^3^ いずれかの Opportunity タイプに対して選択されたサービス階層ごとの最低 1 年間の期間と最小指定容量。



=== オブジェクトストレージ

* サポートされるプロトコル * ： S3

|===


| * サービスレベル * | オブジェクト 


| * ワークロードタイプ * | メディアリポジトリ、アーカイブ 


| * ターゲット IOPS/ TiB * | 該当なし 


| * 最大 IOPS / TiB * | 該当なし 


| * 最大スループット MBps （ 32KB / IOP ） * | 該当なし 


| * 遅延 * | 該当なし 


| * 最小容量 * ^ 1 、 2 ^ | 500TiB ^3^ 
|===

NOTE: ^1 ^ NetApp Direct Opportunityに必要なファイル共有レベルとブロックサービスレベルを組み合わせた場合、1年以上の期間と100TiB以上の最小容量。^2^ チャネル主導の販売機会用に選択されたサービス階層ごとの最低 1 年間の契約期間と最小規定容量。^3^ いずれかの Opportunity タイプに対して選択されたサービス階層ごとの最低 1 年間の期間と最小指定容量。

NetApp Service Engineのユーザインターフェイスの複数の画面から、サービスレベルをサブスクリプションに割り当てることができます。詳細については、を参照してください link:nkfsosm_tenancy_overview.html["Flex サブスクリプションのテナンシーとマルチテナンシー"]。
