---
sidebar: sidebar 
permalink: nkfsosm_data_protection.html 
keywords: netapp, keystone, data, protection, 
summary: データ保護 
---
= データ保護
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone Flex サブスクリプション（ Flex サブスクリプション）データ保護サービスは、データをバックアップし、必要に応じて回復できます。使用可能なデータ保護サービスは次のとおりです。

* ディスクと共有のスナップショット
* ディスクおよび共有のバックアップ（サブスクリプションの一部としてデータ保護サービスが必要）
* ディスクおよび共有のディザスタリカバリ（サブスクリプションの一部としてデータ保護サービスが必要）



NOTE: バックアップサービスとディザスタリカバリサービスはアドオンサービスとして提供され、 Snapshot は基本的なストレージサービスの一部として提供される。

|===
|  | Single Region Snapshots （基本的なストレージサービスの一部として利用可能） | マルチリージョンバックアップ（データ保護アドオン） | 複数リージョンのディザスタリカバリ（データ保護アドオン） 


| ユースケース | インフラの損失や障害ではなく、ユーザやアプリケーションのデータ削除や破損のリスクを軽減 | インフラの損失や障害によってプライマリボリュームのデータが完全に失われるリスクを軽減します | インフラの損失や障害が原因でプライマリボリュームのデータが完全に失われるリスクを、目標復旧時間とともに軽減します 


| ポリシー | 毎時、毎日、毎週、毎月 | 1 時間、 1 日、 1 週間、および 1 カ月単位の Snapshot に基づいて保持するバックアップの数 | 1 時間、 4 時間、毎日 


| トポロジ | ソースのみ | バックアップ | 非同期レプリケーションターゲット 


| レプリケーションサービスレベルを指定してください。 ^1 | 該当なし | 標準 | プライマリと同じ 
|===
^1 追加のストレージ容量をサブスクライブする必要があります


NOTE: 基本的な Flex Subscription サービスに加入しても、データは自動的にはバックアップされません。アドオンのデータ保護サービスに登録し、データバックアップサービスやディザスタリカバリサービス用にシステムを設定する必要があります。ご使用のストレージシステムが Flex サブスクリプションサービスで管理されていない場合でも、ネットアップはストレージシステム上のデータの保護と Flex サブスクリプションサービスへの接続をサポートします。ただし、ネットアップはバックアップの失敗に対して責任を負いません。
