---
sidebar: sidebar 
permalink: nkfsfaq_operating_models.html 
keywords: netapp, keystone, operating, models, 
summary: 動作モデル 
---
= 運用モデルと担当業務
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Flex サブスクリプションには、 3 つの運用モデルがあります。これらの FAQ は運用モデルに関連しています。



=== さまざまな運用モデルと、主な活動の責任者は誰ですか？

次の表は、ネットアップが運用する運用モデル、パートナーが運用する運用モデル、お客様が運用する運用モデルの 3 つの概要を示しています。

* * ネットアップが運用するモデル * ：インストール、導入、運用、監視、最適化、サポートのエンドツーエンドの管理をネットアップが行います。
* * パートナー運用モデル * ：役割と責任の共有は、パートナー様とサービスプロバイダまたはパートナー様の SLA によって異なります。詳細については、サービスプロバイダにお問い合わせください。
* * お客様が運用するモデル * ：次の表は、サービスライフサイクル全体のモデルと、お客様が運用する環境におけるサービスライフサイクルモデルに関連する役割と責任をまとめたものです。


|===
| タスク | ネットアップ | お客様 


| インストールと関連タスク * インストール * 構成 * Deploy * オンボード | アイコン： [] をオンにします。 | なし 


| 管理と監視 * Monitor * Report * 管理タスクの実行 * Alert | なし | アイコン： [] をオンにします。 


| 運用と最適化 * 容量の管理 * パフォーマンスの管理 * SLA の管理 | なし | アイコン： [] をオンにします。 


| サポート * お客様のサポート * ハードウェア障害修正 * ソフトウェア・サポート * アップグレードとパッチ | アイコン： [] をオンにします。 | なし 
|===


=== ネットアップが運用するモデルとは何ですか？

この運用モデルでは、選択したパフォーマンス階層とストレージサービスタイプに応じて、提供されたサービスにお客様がサブスクライブし、追加料金でネットアップが運用するオプションを選択できます。ネットアップでは、アーキテクチャと製品を定義し、お客様のオンプレミスにインストールを行います。ネットアップは、ストレージと IT リソースを使用して、日常的なインフラ管理業務を管理します。使用可能なストレージサービスタイプは、ファイル、ブロック（ iSCSI ）、およびオブジェクトです。Cloud Volumes Service for GCP と AWS もサポートされています。

ネットアップは、パートナー様、テナントの作成と管理も行い、必要に応じてサブスクリプションを管理します。



=== パートナーが運用するモデルとは何ですか？

パートナー様またはサービスプロバイダ様の運用モデルはネットアップが運用するモデルと似ていますが、パートナー様がエンドユーザ様のサービスを運用している場合も同様です。このモデルでは、パートナーは参照される契約者です。テナントはサービスプロバイダのお客様であり、ネットアップとの請求関係はありません。お客様はテナンシーを管理します。テナントのサポート要求は、サービスプロバイダがネットアップにエスカレーションする前に最初に 3 回発行されます。



=== お客様が運用するモデルとは何ですか？

このオペレーティングモデルを使用すると、選択したパフォーマンス階層とストレージサービスタイプに応じて、提供されるサービスをお客様がサブスクライブできるようになります。ネットアップでは、お客様のオンプレミスでアーキテクチャと製品を定義し、お客様がストレージと IT リソースを使用してインフラを管理できるようにしています。使用可能なストレージサービスタイプは、ファイル、ブロック（ iSCSI ）、およびオブジェクトです。このモデルでは、お客様が契約当事者を参照しており、これはエンドユーザまたはパートナーである場合があります。



=== 機器の所有者

3 つの運用モデルすべてで、ネットアップはお客様のオンプレミスにインストールされているすべてのハードウェアとソフトウェアのタイトルを所有します。
