---
sidebar: sidebar 
permalink: nkfsfaq_keystone_subscription.html 
keywords: netapp, keystone, subscription, subscriptions, 
summary: NetApp Keystone サブスクリプション 
---
= NetApp Keystone フレックスサブスクリプションの FAQ です
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下の質問では、 NetApp Keystone フレックスサブスクリプションサービスに関するよくあるお問い合わせをご紹介します。



=== NetApp Keystone Flex サブスクリプションの一部として提供されるものは何ですか。

NetApp Keystone Flex サブスクリプション（ Flex サブスクリプション）は、ブロック、ファイル、オブジェクトの各データサービスを対象とするサブスクリプションベースのサービスです。オンプレミスに導入して、ネットアップ、パートナー、またはお客様が運用できます。



=== Flex サブスクリプションの一部として提供されるストレージサービスにはどのようなものがありますか。

詳細については、を参照してください link:nkfsosm_performance.html["パフォーマンスサービスレベル"]



=== サポートされているアドオンサービス

高度なデータ保護（バックアップとディザスタリカバリ）と FabricPool によるハイブリッドクラウド階層化は、追加料金で選択できるアドオンサービスです。



=== ネットアップはこのサービスでどのようなサービスレベルを保証していますか？

ネットアップが運用するシナリオでは、 NetApp Keystone は、プロビジョニングされるストレージでは 1TiB の IOPS を保証し、各サービスレベルでのレイテンシを保証します。



=== Flex サブスクリプションのマッピング先

Flex サブスクリプションは、単一のサイトまたは単一のデータセンターにマッピングされ、さまざまなパフォーマンスサービスレベルで構成されます。



=== 卓越した階層化と高度な階層化のパフォーマンスレベルにはどのようなメリットがありますか？

階層化は、階層化の卓越したパフォーマンスレベルと階層化のプレミアムパフォーマンスレベルで実現されるため、ストレージの設置面積と関連コストを削減できます。ネットアップでは、データの 25% がホットで、残りの 75% は使用頻度やコールドデータが低く、コールドストレージに移動します。また、使用状況レポートを確認して、データへのアクセス頻度を把握したり、情報に基づいて階層化サービスを有効にしたりすることができます。



=== パートナー様はネットアップから購入した容量よりも多くの容量をお客様に販売できますか？

テナントサブスクリプションには、パートナー様が購入した容量による制限はありません。パートナー様は、ネットアップから購入した容量よりも多くの容量をお客様に販売できます。購入済み容量を超える容量はオーバーサブスクリプションと呼ばれます。



=== お客様のツールと統合するための API は提供されていますか？

はい。 RESTful API を使用して、独自のアプリケーションに統合できます。サポート > API ドキュメント * に移動して、 Flex サブスクリプションサービスの API ドキュメントを参照します。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/seapiref_overview_of_netapp_service_engine_apis.html["Keystone Flex サブスクリプション API ガイド』を参照してください"]。



=== バースト容量とは何ですか？

コミット済み容量を最大 20% 上回っている場合は、使用量を増減できます。バースト時の使用容量は 1 日単位で測定され、使用時にのみ課金されます。たとえば、コミット済み容量が 100TiB の場合、バースト時に最大 120TiB を使用できます。



=== バーストを使用する場合、プレミアム料金は発生しますか？

コミット済み容量の最大使用率は、コミット済み容量と同じ割合で請求されます。コミット済み容量の 20% を超える使用量は、 50% の Premium 料金で請求されます。



=== バースト容量のメリットは何ですか。

バースト時の容量により、ストレージをオンデマンドで消費することも、長期的な利用にも柔軟に対応することができます。



=== バースト時の容量はテナントにどのように割り当てられますか。

バースト時の容量はパートナー様に割り当てられ、要件に基づいてさらにお客様に割り当てられます。



=== コミット済み容量およびバースト時の容量の使用状況はどこで確認できますか。

NetApp Service Engine には、コミット済み容量と比較して使用済み容量をレポートするダッシュボードが組み込まれています。



=== コミット済み容量の使用率が一定の割合に達した場合に通知はありますか？

はい。管理ツールは、 NetApp Service Engine ダッシュボードを使用して容量使用状況に関する通知を提供します。



=== Flex サブスクリプションの使用状況を表示する方法を教えてください。

NetApp Service Engine は、ダッシュボードビューを提供し、サブスクライブされているすべてのサービスに関する情報と消費されている容量を表示します。NetApp Service Engine の詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_overview.html["こちらをご覧ください"]。



=== サービスに関する問題を報告するにはどうすればよいですか？

NetApp Keystone のサポートには、次のさまざまなチャネルからアクセスできます。

* サポート E メール： mailto ： keystone.services@netapp.com[keystone.services@netapp.com^]
* エスカレーションメール： mailto ： keystone.escalations@netapp.com[keystone.escalations@netapp.com^]




=== 新しいストレージサービスを注文できますか。

はい。新しいストレージサービスまたはストレージサービスへの拡張は、 NetApp Service Engine ポータルから要求できます。要求は、 NetApp Keystone 運用チームが処理してから使用可能になります。



=== ストレージに関するコミットメントは即座に増えますか？

要求された容量に応じて、容量がすでに導入されているかどうか、または追加の機器の配送と設置が必要かどうかが判断されます。



=== ワークロードを階層間で移動できますか。

はい。ワークロードの移動先の階層にユーザがサブスクライブしている場合、ワークロードを階層間で移動できます。ただし、原因によってパフォーマンスが低下する可能性があるため、上位の階層から下位の階層に移動することは推奨されません。このプロセスは、ファイル共有を編集し、サービスレベル設定を変更するだけで完了します。



=== どのソフトウェアバージョン（ ONTAP など）がデフォルトでインストールされているか。

サポートチームは、サブスクライブされているサービス階層（ファイルサービスとブロックサービスを使用する ONTAP 、ブロック用の SANtricity 、オブジェクト用の StorageGRID など）に応じて、セキュリティや機能の問題なしで最新の安定版リリースをインストールします。
