---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: NetApp Keystone フレックスサブスクリプション
    url: "/index.html"
    entries:
    - title: サービス利用規約と概要
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: サービス容量の定義
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Flexサブスクリプションのサービスレベル
        url: "/nkfsosm_performance.html"
      - title: サービスレベルの指標と定義
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: 課金
        url: "/nkfsosm_kfs_billing.html"
      - title: データ保護
        url: "/nkfsosm_data_protection.html"
      - title: 階層化
        url: "/nkfsosm_tiering.html"
      - title: 返却不要ディスクではありません
        url: "/nkfsosm_nrd.html"
      - title: 米国市民サポート
        url: "/nkfsosm_uscs.html"
      - title: Flex サブスクリプションおよび Equinix
        url: "/nkfsosm_equinix.html"
    - title: 運用モデルと担当業務
      url: "/nkfsosm_overview.html"
    - title: テナンシーとマルチテナンシー
      url: "/nkfsosm_tenancy_overview.html"
    - title: Flex サブスクリプションインフラストラクチャ
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: サイト要件
      url: "/nkfsosm_site_requirements.html"
    - title: 処理
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: FlexサブスクリプションとActive IQ デジタルアドバイザ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Active IQ デジタルアドバイザからレポートを表示および生成します
        url: "/aiq-keystone-details.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/rn_whats_new.html"
    - title: 解決済みの問題です
      url: "/rn_fixed_issues.html"
    - title: 既知の問題
      url: "/rn_known_issues.html"
  - title: Flex サブスクリプション FAQ
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Flex サブスクリプション
      url: "/nkfsfaq_keystone_subscription.html"
    - title: サービス提供の詳細
      url: "/nkfsfaq_service_offer_details.html"
    - title: 動作モデル
      url: "/nkfsfaq_operating_models.html"
    - title: NetApp Service Engine / セルフサービスアクセスポータル
      url: "/nkfsfaq_netapp_service_engine_self-service_access_portal.html"
  - title: NetApp Service Engine Web インターフェイス
    url: "/sewebiug_overview.html"
    entries:
    - title: 課金アカウント、サブスクリプション、サービス、およびパフォーマンス
      url: "/sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html"
    - title: はじめに
      entries:
      - title: 概要
        url: "/sewebiug_getting_started_overview.html"
      - title: ログインします
        url: "/sewebiug_log_in_to_the_netapp_service_engine_web_interface.html"
      - title: サービスプロバイダと顧客の役割と運用
        url: "/sewebiug_partner_service_provider.html"
      - title: テナントを選択します
        url: "/sewebiug_select_tenant.html"
      - title: NetApp Service Engine Web インターフェイスを表示します
        url: "/sewebiug_netapp_service_engine_web_interface_overview.html"
    - title: Flex サブスクリプションダッシュボードを表示します
      url: "/sewebiug_dashboard.html"
    - title: 請求を表示します
      url: "/sewebiug_billing.html"
    - title: ファイルサービスを操作します
      url: "/sewebiug_working_with_file_services_overview.html"
      entries:
      - title: サーバを表示します
        url: "/sewebiug_view_servers.html"
      - title: ファイルサーバを作成します
        url: "/sewebiug_create_a_file_server.html"
      - title: ファイルサーバを変更します
        url: "/sewebiug_modify_file_server.html"
      - title: ファイルサーバを削除します
        url: "/sewebiug_delete_file_server.html"
      - title: 共有を表示します
        url: "/sewebiug_view_shares.html"
      - title: ファイル共有を作成します
        url: "/sewebiug_create_a_new_file_share.html"
      - title: Snapshot からファイル共有を作成します
        url: "/sewebiug_create_file_share_from_snapshot.html"
      - title: ファイル共有を変更する
        url: "/sewebiug_modify_a_file_share.html"
      - title: ファイル共有を削除します
        url: "/sewebiug_delete_a_file_share.html"
      - title: ファイル共有のアドホックスナップショットを作成します
        url: "/sewebiug_create_adhoc_snapshot_of_a_file_share.html"
    - title: ブロックストレージの操作
      url: "/sewebiug_working_with_block_storage_overview.html"
      entries:
      - title: ホストグループを操作する
        url: "/sewebiug_view_host_groups.html"
      - title: ディスクを表示します
        url: "/sewebiug_view_disks.html"
      - title: ディスクを作成します
        url: "/sewebiug_create_a_new_disk.html"
      - title: Snapshot からディスクを作成します
        url: "/sewebiug_create_a_disk_from_a_snapshot.html"
      - title: ディスクを変更します
        url: "/sewebiug_modify_a_disk.html"
      - title: ディスクを削除します
        url: "/sewebiug_delete_a_disk.html"
      - title: ディスクのアドホックスナップショットを作成します
        url: "/sewebiug_create_an_adhoc_snapshot_of_a_disk.html"
    - title: オブジェクトストレージの操作
      entries:
      - title: 概要
        url: "/sewebiug_working_with_object_storage_overview.html"
      - title: バケットを表示します
        url: "/sewebiug_view_buckets.html"
      - title: オブジェクトストレージを初期化
        url: "/sewebiug_initialize_object_storage.html"
      - title: バケットを作成する
        url: "/sewebiug_create_buckets.html"
      - title: オブジェクトストレージグループとユーザを表示します
        url: "/sewebiug_view_the_object_storage_group_and_users.html"
      - title: オブジェクトストレージグループを作成する
        url: "/sewebiug_create_an_object_storage_group.html"
      - title: オブジェクトストレージグループを変更する
        url: "/sewebiug_modify_an_object_storage_group.html"
      - title: オブジェクトストレージグループを削除する
        url: "/sewebiug_delete_an_object_storage_group.html"
      - title: Create Object Storage User の略
        url: "/sewebiug_create_object_storage_user.html"
      - title: オブジェクトストレージユーザを変更する
        url: "/sewebiug_modify_an_object_storage_user.html"
      - title: ユーザの S3 キーを作成します
        url: "/sewebiug_create_an_s3_key_for_a_user.html"
      - title: ユーザの S3 キーを削除します
        url: "/sewebiug_delete_an_s3_key_for_a_user.html"
    - title: クラウドサービスを管理します
      entries:
      - title: クラウドサービスを管理します
        entries:
        - title: 概要
          url: "/sewebiug_managing_subscribed_services_overview.html"
        - title: サブスクライブしたサービスのリストを表示します
          url: "/sewebiug_view_a_list_of_subscribed_services.html"
        - title: サブスクライブ済みサービスを追加します
          url: "/sewebiug_add_a_subscribed_service.html"
        - title: サブスクライブしたサービスの詳細を変更します
          url: "/sewebiug_modify_the_subscribed_service_details.html"
        - title: サブスクライブしたサービスを削除します
          url: "/sewebiug_delete_a_subscribed_service.html"
      - title: Azure NetApp Files を管理します
        entries:
        - title: Azure NetAppアカウントを管理
          url: "/sewebiug_managing_azure_netapp_accounts.html"
        - title: Azure容量プールを管理します
          url: "/sewebiug_managing_azure_capacity_pools.html"
        - title: Azureボリュームを管理する
          url: "/sewebiug_managing_azure_volumes.html"
      - title: Cloud Volumes Service for Google Cloud Platformを管理します
        url: "/sewebiug_managing_gcp_cvs.html"
    - title: レポートを表示します
      url: "/sewebiug_working_with_reports.html"
    - title: ボリュームをバックアップします
      url: "/sewebiug_back_up_file_shares_and_disks.html"
    - title: サブスクリプションを管理します
      url: "/sewebiug_managing_subscriptions.html"
    - title: サービスリクエストを管理します
      entries:
      - title: 概要
        url: "/sewebiug_managing_service_requests_overview.html"
      - title: サービスリクエストを提出します
        url: "/sewebiug_raise_a_service_request.html"
      - title: サービスリクエストを追跡します
        url: "/sewebiug_track_a_service_request.html"
      - title: サービスリクエストプロセス
        url: "/sewebiug_service_request_process.html"
    - title: 管理タスクを実行
      entries:
      - title: ユーザを管理します
        entries:
        - title: ユーザのリストを表示します
          url: "/sewebiug_view_a_list_of_users.html"
        - title: ユーザを追加します
          url: "/sewebiug_add_a_user.html"
        - title: ユーザの詳細を変更します
          url: "/sewebiug_modify_user_details.html"
        - title: ユーザを削除します
          url: "/sewebiug_delete_a_user.html"
      - title: テナントとサブテナントを管理します
        url: "/sewebiug_managing_tenants_and_subtenants.html"
      - title: アラートを表示および管理します
        url: "/sewebiug_alerts.html"
    - title: ネットワークを管理します
      url: "/sewebiug_define_network_configurations.html"
  - title: NetApp Service Engine API リファレンス』を参照してください
    url: "/seapiref_overview_of_netapp_service_engine_apis.html"
    entries:
    - title: 許可と認証
      url: "/seapiref_authorization_and_authentication.html"
    - title: NetApp Service Engine REST API
      url: "/seapiref_netapp_service_engine_rest_apis.html"
    - title: コンシューマ API
      entries:
      - title: 概要
        url: "/seapiref_consumer_apis_overview.html"
      - title: クラウドオーケストレーション API
        url: "/seapiref_cloud_orchestration_apis.html"
      - title: ブロックストレージ API
        url: "/seapiref_block_storage_apis.html"
      - title: ファイルサービス API
        url: "/seapiref_file_services_apis.html"
      - title: オブジェクトストレージ API
        url: "/seapiref_object_storage_apis.html"
      - title: バックアップ API
        url: "/seapiref_backups_apis.html"
      - title: レポート用 API
        url: "/seapiref_reporting_apis.html"
      - title: API を使用してサブネットを作成する
        url: "/seapiref_subnets_apis.html"
      - title: "（コンシューマ）管理 API"
        url: "/seapiref_@consumer@_administration_apis.html"
    - title: 管理者 API
      entries:
      - title: 概要
        url: "/seapiref_administrator_apis_overview.html"
      - title: テナント
        url: "/seapiref_tenants.html"
      - title: サブテナント
        url: "/seapiref_subtenants.html"
      - title: ユーザ
        url: "/seapiref_users.html"
      - title: ゾーン
        url: "/seapiref_zones.html"
      - title: リージョン
        url: "/seapiref_regions.html"
      - title: ONTAP クラスタ
        url: "/seapiref_ontap_clusters.html"
      - title: StorageGRID インスタンス
        url: "/seapiref_storagegrid_instances.html"
      - title: サービスレベル
        url: "/seapiref_service_levels.html"
      - title: サービスリクエスト
        url: "/seapiref_service_requests.html"
      - title: ジョブ
        url: "/seapiref_jobs.html"
  - title: 法的通知
    url: "/legal-notices.html"
