---
sidebar: sidebar 
permalink: rn_whats_new.html 
keywords: netapp, keystone, release notes, new features, what's new, 
summary: NetApp Service Engine の新機能 
---
= このリリースの NetApp Keystone Flex サブスクリプションサービスの新機能
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このリリースの NetApp Keystone Flex Subscription （ Flex サブスクリプション）サービスでは、次の機能と機能拡張が導入されています。



== NetApp Service Engine 2.2 で導入された機能

このリリースの新機能では、課金、容量利用率、サービスリクエスト、アラートに関する新しいウィジェットのダッシュボードが改良されています。また、このリリースには、課金およびアラート管理用の新しい画面や、 [ 登録済みサービス ] メニューの名前をクラウドサービスに変更する機能も含まれています。



=== ダッシュボードビューが強化されました

NetApp Service Engine ダッシュボードが再設計され、サブスクライブしたサービスの使用済み容量を確認するための「 * Capacity Utilization * 」という新しいコンポーネントが追加されました。* 月額料金 ( 請求 )* すべての月額プランの合計月額料金を表示します。* 警告 * ：環境内の最新のアラートの概要を表示します。* サービスリクエスト * ：環境内で生成された最新のサービスリクエストのリストを表示します。詳細については、を参照してください link:sewebiug_dashboard.html["Flex サブスクリプションダッシュボードを表示します"]



=== 新しい請求画面

請求履歴データを簡単に確認して計算できるように、新しい * 請求先 * 画面が追加されました。画面には、すべての加入サービスに関連する月額料金の全体像が表示されます。

ダッシュボードの * 月額料金 * ウィジェットまたは * Administration > Billing * からこの画面に移動して、すべての加入サービスの月額サブスクリプションレベルの内訳を表示します。請求データは、コミット済み容量とバースト時の使用容量に基づいており、過去数カ月間の使用状況に応じて提供されます。詳細については、を参照してください link:sewebiug_billing.html["請求を表示します"]



=== ［ 新しいアラート ］ 画面

このリリースでは、システムで生成されたアラートとユーザーが生成したアラートをすべて一覧表示する新しい * Alerts * 画面が導入されています。この画面では、環境に関する重要なイベントに対するカスタムのアラートメッセージを作成して、他のユーザに通知することもできます。アラートは必要に応じて表示および却下できます。詳細については、を参照してください link:sewebiug_alerts.html["アラートを作成および管理します"]



=== 強化されたユーザーインターフェイス

NetApp Service Engine のユーザインターフェイスでは、次の機能が強化されています。 * 左側のナビゲーションペインにある * ダッシュボード * メニューから、わかりやすいナビゲーションポイントからダッシュボードにアクセスできます。* 左側のナビゲーションペインの * 登録サービス * メニューの名前が * クラウドサービス * に変更されました。

====

====


== NetApp Service Engine 2.1 で導入された機能

このリリースの新機能には、 Flex サブスクリプション環境でのマルチテナンシーのサポート、およびアクセス頻度の低いデータを低コストのローカル階層またはクラウド階層に移動するための階層化機能が含まれています。



=== サービスプロバイダ向けの Flex サブスクリプションサービスのご紹介

NetApp Service Engine で、サービスプロバイダによるマルチテナント環境の管理がサポートされるようになりました。お客様独自のサブスクリプションを所有しているプロビジョニング、レポート作成、課金、および管理の機能を実行できます。この機能をサポートするために、次の機能拡張が行われました。

* * ダッシュボード： * ダッシュボードには、特定のサブスクリプション番号のストレージサブスクリプションに関する情報（サービス階層、各サービスレベルの容量使用状況、アドオンデータ保護サービスなど）が表示されます。サービスプロバイダは、 NetApp Keystone Flex サブスクリプションとテナントサブスクリプションの詳細を表示できます。テナント管理者は、テナントのすべてのテナントサブスクリプションの詳細を表示できます。
* * レポート： * NetApp Keystone Flex サブスクリプションの使用状況およびテナントの使用状況に関する容量およびパフォーマンスレポートを作成できます。パートナー管理者は、 * Reports * > * Keystone Usage * から Flex Subscription の使用状況に関する容量レポートを表示できます。パートナー管理者は、特定のテナントの容量使用状況レポートを * Reports * > * Tenant Usage * / * Capacity Usage * から表示できます。テナント管理者は、 * Reports * > * Tenant Usage * からテナントレポートを表示できます。
* * サブスクリプション： * パートナー管理者は、 Flex サブスクリプションとテナントサブスクリプションを * サブスクリプション * > * Keystone サブスクリプション * と * サブスクリプション * > * テナントサブスクリプション * でそれぞれ表示および更新できます。テナント管理者は、テナントサブスクリプションのみを表示できます。
* * users ： * ユーザのロールに基づいて、要件に応じて、テナンシー内の新規または既存のユーザに権限を割り当てることができます。ロールは、ネットアップ管理者、読み取り専用権限を持つネットアップ管理者、パートナー管理者、テナント管理者のいずれかです。パートナー管理者は、新しいユーザに割り当てることができるのは、パートナーの管理者またはテナントの管理者ロールだけです。テナント管理者ユーザは、テナント管理者ロールのみを他のユーザに割り当てることができます。
* * ネットワークメニュー： * パートナー管理者は、テナント用に定義されたネットワークを表示できます。サブテナントおよびゾーンのサブテナントおよびゾーン用のサブネットは、 * networks * > * subnet* から作成することもできます。これは、エンドユーザやサブテナントがストレージをプロビジョニングする際に必要になります。
* API のサポート : このリリースでは '/tenants /{tenant_id }/zones/{ zone_id}/subnets'/{ zone_id}/subnets/{id}/tags' API が提供され ' サブテナント用のサブネットを作成および表示することができます


この機能の詳細については、次のリンクを参照してください。 * link:nkfsosm_overview.html["運用モデル、役割、担当業務"]* * * * * * 



=== 階層化

NetApp Keystone Flex サブスクリプションサービスに、 NetApp FabricPool テクノロジを活用した階層化機能が追加されました。使用頻度の低いデータを特定し、ネットアップのオンプレミス環境にあるコールドストレージに階層化します。階層化には、階層化の高度なパフォーマンスレベルや階層化のプレミアムなパフォーマンスレベルがあります。

次の API が変更され、新しい階層化サービスレベルの属性値が追加されました。

* ファイルサービス API
* ブロックストア API


詳細については、次のリンクを参照してください。 * link:nkfsosm_tiering.html["階層化"]* 

====

====


== NetApp Keystone Flex サブスクリプション 2.0.1 で導入された機能



=== Google Cloud Platform 向け Cloud Volume サービスにも対応

NetApp Service Engine では、既存の Azure NetApp Files サポートに加え、 Google Cloud Platform （ GCP ）向け Cloud Volume サービスをサポートできるようになりました。登録したサービスを管理し、 NetApp Service Engine から Google Cloud Volume をプロビジョニングおよび変更できるようになりました。


NOTE: Cloud Volume サービスへのサブスクリプションは、 NetApp Service Engine の外部で管理されます。関連するクレデンシャルが NetApp Service Engine に提供され、クラウドサービスに接続できるようになります。



=== NetApp Service Engine の外部でプロビジョニングされたオブジェクトを管理できます

お客様の環境にすでに存在し、 NetApp Service Engine で設定された Storage VM に属しているボリューム（ディスクおよびファイル共有）を、 NetApp Keystone Flex Subscription （ Flex サブスクリプション）の一部として表示および管理できるようになりました。NetApp Service Engine 以外でプロビジョニングされたボリュームが、適切なステータスコードの「共有」および「 * ディスク」ページに表示されるようになりました。バックグラウンドプロセスは一定の間隔で実行され、 NetApp Service Engine インスタンス内の外部ワークロードをインポートします。

インポートされたディスクとファイル共有は、 NetApp Service Engine 上の既存のディスクとファイル共有と同じ標準に設定できません。インポート後 ' これらのディスクとファイル共有は非標準ステータスで分類されますNetApp Service Engine ポータルを使用して標準化および管理するには、 * Support > Service Request > New Service Request * からサービス要求を送信します。



=== SnapCenter と NetApp Service Engine の統合

SnapCenter と NetApp Service Engine の統合の一環として、 SnapCenter 環境で作成された Snapshot から、 NetApp Service Engine インスタンス以外の場所にディスクおよびファイル共有のクローンを作成できるようになりました。NetApp Service Engine ポータル上の既存の Snapshot からファイル共有またはディスクをクローニングする際に、これらの Snapshot が表示されます。取得プロセスはバックグラウンドで定期的に実行され、 NetApp Service Engine インスタンス内で Snapshot がインポートされます。



=== バックアップを維持するための新しい画面

新しい * Backup * 画面では、環境内に作成されたディスクとファイル共有のバックアップを表示および管理できます。バックアップポリシーを編集したり、ソースボリュームとのバックアップ関係を解除したり、ボリュームのすべてのリカバリポイントを含むバックアップボリュームを削除したりできます。この機能を使用すると、ソース・ボリュームを削除した場合でも、バックアップを（孤立したバックアップとして）保持して、あとでリストアすることができます。特定のリカバリポイントからファイル共有またはディスクをリストアする場合は、 * Support > Service Request > New Service Request * からサービス要求を上げることができます。



=== CIFS 共有でのユーザアクセスを制限するためのプロビジョニング

CIFS （ SMB ）またはマルチプロトコルの共有でユーザアクセスを制限する ACL を指定できるようになりました。ACL に追加する Active Directory （ AD ）の設定に基づいて Windows ユーザまたはグループを指定できます。link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps["詳細はこちら。"]

====

====


== NetApp Keystone Flex サブスクリプション 2.0 で導入された機能



=== MetroCluster のサポート

NetApp Service Engine は、 MetroCluster 構成が設定されたサイトをサポートしています。MetroCluster は、 ONTAP のデータ保護機能で、継続的な可用性が確保されたストレージに対して同期ミラーリングを使用して、 RPO （目標復旧時点） 0 または RTO （目標復旧時間） 0 を実現します。MetroCluster のサポートは、 NetApp Service Engine 内での同期ディザスタリカバリ機能に変換されます。MetroCluster インスタンスの各側は個別のゾーンとして登録され、それぞれにデータ保護の詳細料金プランが含まれた独自のサブスクリプションがあります。MetroCluster 対応ゾーンで作成された共有またはディスクは、 2 番目のゾーンに同期的にレプリケートされます。レプリケートゾーンの使用状況は、ストレージがプロビジョニングされているゾーンに適用される Data Protection Advanced のレートプランに従います。



=== Cloud Volume サービスのサポート

ネットアップサービスエンジンで Cloud Volume サービスをサポートできるようになりました。Azure NetApp Files をサポートできるようになりました。


NOTE: Cloud Volume サービスへのサブスクリプションは、 NetApp Service Engine の外部で管理されます。関連するクレデンシャルが NetApp Service Engine に提供され、クラウドサービスに接続できるようになります。

NetApp Service Engine は以下をサポートします。

* Cloud Volume サービスボリュームのプロビジョニングまたは変更（スナップショットの作成機能を含む）
* Cloud Volume サービスゾーンへのデータのバックアップ
* NSE インベントリでの Cloud Volume サービスボリュームの表示
* Cloud Volume サービスの使用状況の表示




=== ホストグループ

NetApp Service Engine では、ホストグループの使用がサポートされています。ホストグループは、 FC プロトコルホストのワールドワイドポート名（ WWPN ）または iSCSI ホストノード名（ IQN ）のグループです。ホストグループを定義してディスクにマッピングし、どのイニシエータがディスクにアクセスできるかを制御することができます。ホストグループを使用する代わりに、各ディスクに個別のイニシエータを指定し、次の処理を実行する必要があります。

* 同じイニシエータセットに提供する追加のディスク
* 複数のディスクにわたってイニシエータのセットを更新する




=== バースト時の使用状況と通知

一部の NetApp Service Engine でサポートされているストレージサブスクリプションでは、お客様がコミット済み容量を超えるバースト容量を使用できます。この容量は、サブスクライブ済みのコミット済み容量とは別に課金されます。使用状況やコストを制御するために、バースト容量をいつ使用するか、または使用したかを理解することが重要です。



==== 提案された変更によってバースト容量が使用される場合に通知します

原因 a サブスクリプションをバースト状態にするために、提示されたプロビジョニングの変更を表示する通知。ユーザーは、サブスクリプションをバーストにするか、アクションを続行しないかを選択して、続行することを選択できます。link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["詳細はこちら。"]



==== サブスクリプションがバースト状態になったときの通知

通知バナーは、サブスクリプションがバースト状態のときに表示されます。link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications["詳細はこちら。"]



==== Capacity レポートには、バースト使用状況が表示されます

容量レポート：サブスクリプションがバースト状態になってからの日数と使用済みバースト容量が表示されます。link:sewebiug_working_with_reports.html#capacity-usage["詳細はこちら。"]



=== パフォーマンスレポート

NetApp Service Engine Web インターフェイスの新しいパフォーマンスレポートには、次のパフォーマンス測定値に基づいて、個々のディスクまたは共有のパフォーマンスに関する情報が表示されます。

* IOPS/TB （テビバイトあたりの入出力処理数）：ストレージデバイスで実行される 1 秒あたりの入出力処理数（ IOPS ）。
* スループット（ MBps ）：ストレージメディアとの間のデータ転送速度（ MB/ 秒）。
* Latency （ ms ）：ディスクまたは共有からの読み取りと書き込みの平均時間（ミリ秒）




=== サブスクリプション管理

サブスクリプション管理が強化されました。次の操作を実行できます。

* サブスクリプションまたはサービス向けに、データ保護のアドオンを申請するか、データ保護の追加容量を申請する
* データ保護の使用容量を表示します




=== 課金機能の強化

請求で、 ONTAP （ファイルとブロック）ストレージのスナップショット使用量を測定して請求できるようになりました。



=== 非表示の CIFS 共有

NetApp Service Engine は、非表示の CIFS 共有の作成をサポートしています。
