---
sidebar: sidebar 
permalink: seapiref_backups_apis.html 
keywords: netapp, keystone, backups, apis, 
summary: Keystone バックアップ API 
---
= バックアップ API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップ API を使用して、環境内のボリューム（ファイル共有およびディスク）の Snapshot （バックアップまたはリカバリポイント）を表示および管理することができます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
「 /v2.1/backups
| テナント内のサブテナント用に作成されたすべてのボリュームのすべてのバックアップオブジェクトの詳細を取得できます。バックアップポリシー、ゾーン、タグなど、ソースボリュームとバックアップオブジェクトの詳細を取得します。  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/backups/{id}`
| テナントのサブテナントのボリューム用に作成された特定のバックアップオブジェクトの詳細を取得できます。入力した ID に基づいて、ソースボリュームおよびバックアップオブジェクト（バックアップポリシー、ゾーン、タグなど）の詳細を取得します。  a| 
id` ：バックアップオブジェクトの ID 。



 a| 
「 GET 」
 a| 
「 /v2.1/backups/{id}/`rection_points` 」
| 特定のバックアップオブジェクトのすべてのリカバリポイントの詳細を取得できます。タイムスタンプや名前などの詳細が取得されます。  a| 
id` ：バックアップオブジェクトの ID 。



 a| 
「 GET 」
 a| 
「 /v2.1/backups/{id}/``re cOVERY_points/{name}` 」
| 特定のバックアップオブジェクトの任意のリカバリポイントの詳細を取得できます。タイムスタンプや名前などの詳細が取得されます。  a| 
id` ：バックアップオブジェクトの ID 。`name` ：リカバリポイントの名前。



 a| 
「 POST 」
 a| 
「 /v2.1/backups
| 特定のソースボリュームのバックアップオブジェクトを作成できます。要求の本文に値を追加して、バックアップポリシー、保持するバックアップコピーの数、ソースリソース ID など、指定されたパラメータを使用してバックアップオブジェクトを作成します。  a| 
'`{" primary_resource_type":""< リソースタイプ >" 、 "source_resource_id":""<ID>" 、 "backup_zone" ： ""backup_policy" ： {"daily_backups_to _keep" ： <number of daily hoc backups to keTag ： "/ke_types" 、 "ke_type" ：毎月のバックアップ数を維持するための ")")"<1bay_backups_policy_backup_policy>" ： "<Tag N>" ｝ ``



 a| 
「 POST 」
 a| 
`/v2.1/backups/{id}/tags`
| サブテナントのバックアップオブジェクトのタグを作成または置き換えできます。バックアップオブジェクトの ID とタグの値を要求の本文に「 key ： value pair 」の形式で追加します。  a| 
id` ：バックアップオブジェクトの ID 。'{" key1":""<Tag 1> 、 "key2":""KEYN"" 、 "KEYN":""<Tag N>"}``



 a| 
「 PATCH 」
 a| 
`/v2.1/backups/{id}`
 a| 
ボリュームの任意のバックアップオブジェクトを ID に基づいて変更できます。バックアップポリシーの詳細、保持するバックアップの数、ソースリソース ID など、バックアップオブジェクトの ID と変更する値を要求の本文に追加します。

[NOTE]
====
'patch' 要求で 'source_resource_id' パラメータの値を null に設定することにより ' バックアップ・オブジェクトを孤立させることができますこれにより、 SnapMirror 関係は削除されますが、バックアップボリュームとその下のリカバリポイントは保持されます。

==== a| 
id` ：バックアップオブジェクトの ID 。`{" source_resource_id" ： "<Resource ID>" 、 "backup_policy" ： {"daily_backups_to _keep" ： <保持 する日次バックアップの数 >,"weekly_backups_to _keep" ： <number of weekly backups to keep> 、 "monthly_schedule_backups_to KEke" ： <tags")"<1$hoc バックアップの数 ,"_hoc タグ ",",")"<1"_hoc タグ ","_hoc タグ "<1">



 a| 
「削除」
 a| 
`/v2.1/backups/{id}`
| ボリュームのすべてのバックアップオブジェクトとすべてのリカバリポイントを削除できます。  a| 
id` ：バックアップオブジェクトの ID 。



 a| 
「削除」
 a| 
「 /v2.1/backups/{id}/``re cOVERY_points/{name}` 」
| ボリュームの特定のバックアップオブジェクト内の任意のリカバリポイントを削除できます。  a| 
id` ：バックアップオブジェクトの ID 。`name` ：リカバリポイントの名前。

|===