---
sidebar: sidebar 
permalink: seapiref_block_storage_apis.html 
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis 
summary: Keystone ブロックストレージ API 
---
= ブロックストレージ API
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ブロックストレージ API を使用して、ブロックストレージを表示および管理できます。

ディスクを作成する前に、ブロックストアを作成する必要があります。ディスクを作成するときは、ホストグループを作成するか、既存のホストグループを選択してディスクにアクセスする必要があります。詳細については、を参照してください link:sewebiug_working_with_block_storage_overview.html["ブロックストレージの操作"]。



== ブロックストア

ブロックストア API を使用して、ブロックストアを取得および管理できます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
「 /v2.1/blockstores 」と入力します
| すべてのブロックストアの詳細を取得できます。ブロックストア ID 、 IP アドレス、リージョン、ゾーン、サブネット ID など、ブロックストアの詳細を取得します。 タグを使用できます。  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/blockstores/{id}`
| 特定のブロックストアの詳細を取得できます。入力した ID に基づいて、 IP アドレス、リージョン、ゾーン、サブネット ID 、タグなどのブロックストアの詳細を取得します。  a| 
id` ：ブロックストアの ID 。



 a| 
「 POST 」
 a| 
「 /v2.1/blockstores 」と入力します
| ブロックストアを作成できます。要求の本文に値を追加して、サービスプロトコル、サブテナント ID 、ゾーン、サブネット ID 、タグなど、指定したパラメータでブロックストアを作成します。  a| 
「 ubtenant_id 」：サブテナントの ID 。'zone' ：ゾーンの名前。'ubnet_id ' ：サブネットの ID



 a| 
「 POST 」
 a| 
`/v2.1/blockstores/{id}/`tags`
| ブロックストアのタグは、作成または置換できます。ブロックストアの ID とタグの値を要求の本文に「 key ： value pair 」の形式で追加します。  a| 
id` ：ブロックストアの ID 。



 a| 
「 PUT 」
 a| 
`/v2.1/blockstores/{id}`
| 任意のブロックストアを ID に基づいて変更できます。ブロックストアの ID 、およびゾーン、サービスプロトコル、タグなどの変更する値を要求の本文に追加します。  a| 
id` ：ブロックストアの ID 。



 a| 
「削除」
 a| 
`/v2.1/blockstores/{id}`
 a| 
任意のブロックストアを ID で削除できます。
 a| 
id` ：ブロックストアの ID 。

|===

NOTE: ブロックストアを削除する前に、マッピングされているすべてのディスクを削除する必要があります。



== ディスク

ディスク API を使用して、ディスクを取得および管理できます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
「 /v2.1/disks 」
| すべてのディスクの詳細を取得できます。ブロックストア ID 、名前、ディスクパス、プロトコル、 Snapshot ポリシーなど、ディスクの詳細を取得します。 タグを使用できます。  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/disks/{id}`
| 特定のディスクの詳細を取得できます。ブロックストア ID 、名前、ディスクパス、プロトコル、 Snapshot ポリシーなど、ディスクの詳細を取得します。 入力した ID に基づいてタグを作成します。  a| 
id` ：ディスクの ID 。



 a| 
「 POST 」
 a| 
「 /v2.1/disks 」
| ディスクを作成できます。要求の本文に値を追加して、サブテナント ID 、ゾーン、名前、ディスクパス、 Snapshot ポリシー、 バックアップポリシーおよびタグ。  a| 
「 ubtenant_id 」：サブテナントの ID 。'zone' ：ゾーンの名前。`name` ：ディスクの名前。「 disk_path 」：ディスクのパス。'protocol' ：ブロック・デバイスのアクセスに使用されるストレージ・プロトコルos_type ：ホスト・オペレーティング・システムのタイプ「 hostgroup_dmappings 」：ホストグループマッピング。「 service_level 」： Standard 、 Premium 、 Premium-Tiering 、 Extreme 、 Extreme のいずれかのサービスレベル名を指定できます。[ize_GB] ：ディスクのサイズ（ GB 単位）。



 a| 
「 POST 」
 a| 
「 /v2.1/disks/{id}/`s Snapshot/{name}` 」
| ディスクのスナップショットを作成できます。  a| 
id` ：ディスクの ID 。`name` ：スナップショットの名前。



 a| 
「 POST 」
 a| 
`/v2.1/disks/{id}/`tags`
| ディスクのタグは、作成または置換できます。ディスクの ID とタグの値を要求の本文に「 key ： value pair 」の形式で追加します。  a| 
id` ：ディスクの ID 。



 a| 
「 PUT 」
 a| 
`/v2.1/disks/{id}`
| 任意のディスクを ID に基づいて変更できます。ディスクの ID 、および名前、サービスレベル、 Snapshot ポリシー、バックアップポリシー、タグなど、変更する値を要求の本文に追加します。  a| 
id` ：ディスクの ID 。「 hostgroup_dmappings 」：ホストグループマッピング。



 a| 
「削除」
 a| 
`/v2.1/disks/{id}`
| 任意のディスクを ID で削除できます。  a| 
id` ：ディスクの ID 。



 a| 
「削除」
 a| 
「 /v2.1/disks/{id}/`s Snapshot/{name}` 」
| ディスクの Snapshot は、ディスクの ID および Snapshot 名で削除できます。  a| 
id` ：ディスクの ID 。`name` ：スナップショットの名前。

|===


== ホストグループ

ディスクへのアクセス制御はホストグループで管理されます。ホストグループ API を使用して、ホストグループを取得および管理できます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
「 /v2.1/hostgroups 」と入力します
| すべてのホストグループの詳細を取得できます。名前、サブテナントの詳細、テナントの詳細、ゾーン、 プロトコル、イニシエータ、ホストグループを使用するディスク、およびタグ。  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/hostgroups/{id}`
| 特定のホストグループの詳細を取得できます。ホストグループの名前、サブテナントの詳細、テナントの詳細、ゾーン、 入力した ID に基づいて、プロトコル、イニシエータ、ホストグループを使用するディスク、およびタグ。  a| 
`id` ：ホストグループの ID 。



 a| 
「 POST 」
 a| 
「 /v2.1/hostgroups 」と入力します
| ホストグループを作成することができます。要求の本文に値を追加して、名前、サブテナント ID 、ゾーン、プロトコル、 イニシエータ、およびタグ  a| 
`name` ：ホストグループの名前。「 ubtenant_id 」：サブテナントの ID 。'zone' ：ゾーンの名前。'protocol' ：ブロック・デバイスのアクセスに使用されるストレージ・プロトコルos_type ：ホスト・オペレーティング・システムのタイプ



 a| 
「 POST 」
 a| 
`/v2.1/hostgroups/{id}/`tags`
| ホストグループのタグは、作成または置換できます。ホストグループの ID とタグの値を要求の本文に「 key ： value pair 」の形式で追加します。  a| 
`id` ：ホストグループの ID 。



 a| 
「削除」
 a| 
`/v2.1/hostgroups/{id}`
| すべてのホストグループを ID で削除できます。  a| 
`id` ：ホストグループの ID 。

|===


== ホストグループ内のイニシエータ

Host Groups API を使用して、ホストグループにマッピングされているイニシエータを取得および管理できます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
`/v2.1/hostgroups/{id}/`initiators
| すべてのイニシエータの詳細を取得できます。イニシエータとそのエイリアスを取得します。  a| 
`id` ：ホストグループの ID 。



 a| 
「 GET 」
 a| 
`/v2.1/hostgroups/{id}/`initiators /{alias}`
| 特定のイニシエータの詳細を取得できます。入力した ID とエイリアスに基づいてイニシエータを取得します。  a| 
`id` ：ホストグループの ID 。'alias' ：イニシエータのエイリアス名



 a| 
「 POST 」
 a| 
`/v2.1/hostgroups/{id}/`initiators
 a| 
ホストグループのイニシエータを作成できます。ホストグループのイニシエータを作成するには、要求の本文にイニシエータとそのエイリアスの値を追加します。
 a| 
`id` ：ホストグループの ID 。'alias' ：イニシエータのエイリアス名イニシエータ：イニシエータ（ iSCSI Qualified Name または FC WWPN ）



 a| 
「 PATCH 」
 a| 
`/v2.1/hostgroups/{id}/`initiators /{alias}`
| イニシエータを変更できます。要求の本文に新しいイニシエータを追加します。  a| 
`id` ：ホストグループの ID 。'alias' ：イニシエータのエイリアス名イニシエータ : イニシエータ (iSCSI 修飾名または FC WWN)



 a| 
「削除」
 a| 
`/v2.1/hostgroups/{id}/`initiators /{alias}`
 a| 
イニシエータは、ホストグループの ID とイニシエータのエイリアスで削除できます。
 a| 
`id` ：ホストグループの ID 。'alias' ：イニシエータのエイリアス名

|===
[NOTE]
====
ホストグループにイニシエータを追加するときは、イニシエータがホストグループのプロトコルと一致している必要があります。iSCSI プロトコルを使用するホストグループには IQN を、 FC プロトコルを使用するホストグループには WWPN を使用する必要があります。

ホストグループからイニシエータを削除すると、ホストグループのマッピング先のすべてのディスクが対象になります。

====