---
sidebar: sidebar 
permalink: seapiref_reporting_apis.html 
keywords: netapp, keystone, reporting, apis, 
summary: Keystone レポート API 
---
= レポート用 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表のメソッドを使用して、レポートを取得および生成します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/reports` 」 | すべてのレポートのリストを取得します。 


| 「 POST 」 | `/v2.1/reports/{filename}` | レポートを取得します。 
|===


== レポートのリストを取得します

次の表に示すメソッドを使用して、レポートのリストを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/reports` 」 | テナントで使用可能なすべてのレポートを取得します。レポートは日付範囲でフィルタリングできます。  a| 
* 「 tenant_id （文字列）」
* 'start(string) `: 開始時に指定した日付より新しいレポートを取得します
* `end (string) `: 最後に指定した日付より古いレポートを取得します


|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....


=== ファイル名で識別されたレポートを取得します

次の表に示すメソッドを使用して、ファイル名で特定されたレポートを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/reports/{filename}` | ファイル名で識別されたレポートを取得します。 | `filename(string) `: レポートファイルの名前。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....