---
sidebar: sidebar 
permalink: seapiref_regions.html 
keywords: netapp, keystone, regions, 
summary: Keystone リージョン 
---
= リージョン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、リージョンを作成、変更、および削除します。リージョンを取得できる API については、（コンシューマ）管理 API を参照してください。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/regions 」と入力します | リージョンを取得します。 


| 「 GET 」 | `/v2.1/regions/{name}` | リージョンを名前で取得します。 


| 「 POST 」 | 「 /v2.1/regions 」と入力します | 新しいリージョンを作成します。 


| 「 PUT 」 | `/v2.1/regions/{name}` | リージョンの詳細を変更します。 


| 「削除」 | `/v2.1/regions/{name}` | リージョンを削除します。 
|===


== リージョン属性

次の表に、リージョンの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | リージョンの一意の識別子。 


| 「 name 」 | 文字列 | リージョン名。 


| 概要 | 文字列 | リージョンの概要。 
|===


== リージョンを読み出します

次の表に示すメソッドを使用して、すべてのリージョンまたはリージョンのサブセットを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/regions 」と入力します | リージョンを読み出します。 | 「 offset 」および「 limit 」 - を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 4,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5e7bf44daab46c00014ce77f",
        "name": "au-east8",
        "description": "This is the new region description",
        "zones": []
      }
    ]
  }
}
....


== 名前を使用してリージョンを取得します

次の表に示すメソッドを使用して、リージョンを名前で取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/regions/{name}` | 名前を使用してリージョンを取得します。 | `name (string) ` : リージョン名。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "au-east1",
        "description": "string",
        "zones": [
          "au-east1-a"
        ]
      }
    ]
  }
}
....


== リージョンを作成します

リージョンを作成するには、次の表に示すメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/regions 」と入力します | 新しいリージョンを作成します。 | なし 
|===
要求本文の必須属性 : 'name

* 要求本文の例： *

....
{
  "name": "MyRegionName",
  "description": "DescriptionOfMyRegion"
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "Description": "DescriptionOfMyRegion",
        "user_id": "5bbee380a2df7a04d43acaee",
        "created": "0001-01-01T00:00:00Z",
        "tags": null
      }
    ]
  }
}
....


== リージョンを変更します

リージョンを変更するには、次の表に示すメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/regions/{name}` | 名前で識別された領域を修正します。リージョンの名前と概要を変更できます。 | `name (string) ` : リージョンの名前。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "name": "MyRegionName",
  "description": "NewDescriptionOfMyRegion"
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "description": "NewDescriptionOfMyRegion",
        "zones": []
      }
    ]
  }
}
....


== リージョンを削除します

リージョンを削除するには、次の表に示すメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/regions {name}` | 名前で識別された 1 つのリージョンを削除します。最初に、リージョン内のすべてのゾーンを削除する必要があります。 | Name (string) ` ：リージョンの名前。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
No content for succesful delete
....