---
sidebar: sidebar 
permalink: seapiref_authorization_and_authentication.html 
keywords: netapp, keystone, authorization, authentication, 
summary: Keystone の承認と認証 
---
= 許可と認証
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Service Engine REST API には、問題 HTTP 要求を実行できる任意の Web ブラウザまたはプログラミングプラットフォームを使用してアクセスできます。NetApp Service Engine は、基本的な HTTP 認証メカニズムに加えて、 Java Web Token （ JWT ）ベアラ認証をサポートしています。API を呼び出す前に、ユーザを認証する必要があります。

参照APIの場合は、NetApp Service Engine Webインターフェイスにログインし、*左ナビゲーションペイン>サポート> APIドキュメント*からSwaggerインターフェイスを表示できます。



== HTTP ステータスコード

API の実行時や問題のトラブルシューティング時には、 NetApp Service Engine API で使用されるさまざまな HTTP ステータスコードとエラーコードについて理解しておく必要があります。

次の表に、認証に関連するエラーコードを示します。

|===
| HTTP ステータスコード | ステータスコードタイトル | 説明 


| 200 | わかりました | 同期 API 呼び出しの実行に成功した場合に返されます。 


| 201 | 作成済み | Active Directory の設定など、同期呼び出しによって新しいリソースが作成されたことを示します。 


| 202. | 承認済み | LUN やファイル共有の作成など、プロビジョニング機能の非同期呼び出しの実行が成功したときに返されます。 


| 400 | 無効な要求です | 入力検証に失敗したことを示します。ユーザは、要求の本文に有効なキーが含まれている場合など、入力を修正する必要があります。 


| 401 | 不正な要求です | リソースを表示する権限がありません / 権限がありません。 


| 403 | 禁止された要求です | アクセスしようとしていたリソースへのアクセスは禁止されています。 


| 404 | リソースが見つかりません | アクセスしようとしているリソースが見つかりません。 


| 405 | メソッドを使用できません | メソッドを使用できません 


| 412 | 前提条件に失敗しました | 前提条件が 1 つ以上満たされていません。 


| 500 | 内部サーバエラー | 内部サーバエラー。サーバから応答を取得できませんでした。この内部サーバエラーは、永続的な場合とそうでない場合があります。たとえば、 get または get all 処理を実行してこのエラーが表示された場合は、この処理を 5 回以上繰り返すことを推奨します。永続的なエラーの場合、引き続きステータスコード 500 が返されます。処理が成功すると、ステータスコード 200 が返されます。 
|===


== API の使用に関する推奨事項

API を使用するときは、次の推奨される方法に従ってください。

* 有効な実行の場合は、すべての応答コンテンツタイプが次の形式であることを確認します。
+
....
application/json
....
* 配列値を更新するときは、値の文字列全体を更新する必要があります。配列に値を追加することはできません。既存の配列のみを置き換えることができます。
* フィルタ演算子のワイルドカード (`*`) とパイプ (`|') を組み合わせてオブジェクトを照会しないでください間違った数のオブジェクトが取得される可能性があります。

