---
sidebar: sidebar 
permalink: seapiref_object_storage_apis.html 
keywords: netapp, keystone, object, storage, apis, 
summary: Keystone オブジェクトストレージ API 
---
= オブジェクトストレージ API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このセクションでは、オブジェクトストレージ、オブジェクトストレージユーザ、およびオブジェクトストレージグループを管理するための API を提供します。

オブジェクトストレージのワークフローは次のタスクで構成されます。

* オブジェクトストレージアカウントを作成する。
* オブジェクトストレージグループを作成する。
* オブジェクトストレージユーザを作成する。
* ユーザの S3 キーを作成します。




=== オブジェクトストレージグループ

次の表に示すメソッドを使用して、オブジェクトストレージグループを読み出し、作成、または変更します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/objectiam/groups 」 | オブジェクトストレージグループを読み出します。 


| 「 GET 」 | `/v2.1/objectiam/groups/{id}` | ID を使用してオブジェクトストレージグループを読み出します。 


| 「 POST 」 | 「 /v2.1/objectiam/groups 」 | オブジェクトストレージの ID アクセス管理グループを作成します。 


| 「 PUT 」 | `/v2.1/objectiam/groups/{id}` | ID で識別されるオブジェクトストレージグループを変更します。 


| 「削除」 | `/v2.1/objectiam/groups/{id}` | ID で識別されているオブジェクトストレージグループを削除します。 
|===


==== オブジェクトストレージグループの属性

次の表に、オブジェクトストレージの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | オブジェクトストレージグループの一意の識別子。 


| 「 name 」 | 文字列 | オブジェクトストレージグループの名前。 


| 「テナント」 | 文字列 | グループが属するサブテナントの名前。 


| 'ubtenant_id | 文字列 | グループが属しているサブテナントの識別子。 


| 「テナント」 | 文字列 | グループが属するテナントの名前。 


| 「 tenant_id 」 | 文字列 | グループが属するテナントの識別子。 


| '3_policy |   a| 
以下に示す S3 ポリシー：

[listing]
----
"s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
----
|===


=== オブジェクトストレージグループを読み出します

次の表に示すメソッドを使用して、すべてのオブジェクトストレージグループまたは一部のオブジェクトストレージグループを取得します。「 ubtenant_id 」を指定すると、そのサブテナントに属するオブジェクトストレージグループのみが返されます。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/objectiam/groups 」 | すべてのオブジェクトストレージグループを読み出します。必要に応じて、サブテナント ID を指定して、サブテナントに関連付けられているオブジェクトストレージグループのみを取得します。 | 「 ubtenant_id （文字列）」： ID およびアクセス管理（ IAM ）ユーザ / グループに関連付けられたサブテナント ID 。「 offset 」および「 limit 」 - を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]

....


==== ID を使用してオブジェクトストレージグループを読み出します

次の表に示すメソッドを使用して、 ID 別にオブジェクトストレージグループを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/objectiam/groups/{id}` | ID を使用してオブジェクトストレージグループを読み出します。 | `id (string) ` ：オブジェクトストレージグループの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


==== オブジェクトストレージグループを作成する

オブジェクトストレージグループを作成するには、次の方法を使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/objectiam/groups/` 」 | オブジェクトストレージユーザをホストする新しいオブジェクトストレージグループサービスを作成します。 | なし 
|===
要求の本文に必要な属性は 'name'`ubtenant_id '`3Policy' です

* 要求本文の例： *

....
{
  "name": "MyNewGroup",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fa312c356a0001a73841",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T07:05:21.130260774Z",
        "updated": "2020-06-02T07:05:21.130260774Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== オブジェクトストレージグループを変更する

次の表に示す方法を使用して、オブジェクトストレージグループを変更します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/objectiam/groups/{id}` | オブジェクトストレージグループを変更する。 | `id (string) ` ：オブジェクトストレージグループの一意の識別子。 
|===
要求の本文に必要な属性は 'name'`ubtenant_id '`3Policy' です

* 要求本文の例： *

....
{
  "s3_policy": {
    "Statement": [
        {
        "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:GetObject",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionTagging"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::*"
        }
    ]
  }
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fe822c356a0001a73859",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:23:46.43550235Z",
        "updated": "2020-06-02T07:23:46.43550235Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== ID 別にオブジェクトストレージグループを削除します

次の表に示すメソッドを使用して、 ID 別にオブジェクトストレージグループを削除します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/objectiam/groups/{id}` | ID 別にオブジェクトストレージグループを削除します。 | `id (string) ` ：オブジェクトストレージグループの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


=== オブジェクトストレージユーザ

次の表に示す方法を使用して、次の作業を実行します。

* オブジェクトストレージユーザを読み出し、作成、または変更する。
* S3 キーの作成、ユーザの S3 キーの取得、またはキー ID を使用したキーの取得を行います。


|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/objectiam/users 」 | オブジェクトストレージユーザを読み出します。 


| 「 GET 」 | `/v2.1/objectiam/users/{id}` | ID を使用してオブジェクトストレージユーザを読み出します。 


| 「 POST 」 | 「 /v2.1/objectiam/users 」 | オブジェクトストレージユーザを作成する。 


| 「 PUT 」 | `/v2.1/objectiam/users/{id}` | ID で識別されるオブジェクトストレージユーザを変更します。 


| 「削除」 | `/v2.1/objectiam/users/{id}` | ID によってオブジェクトストレージユーザを削除します。 


| 「 GET 」 | `/v2.1/objectiam/users/{user_id}/s3keys | ユーザにマッピングされたすべての S3 キーを取得します。 


| 「 POST 」 | `/v2.1/objectiam/users/{user_id}/s3keys | S3 キーを作成します。 


| 「 GET 」 | `/v2.1/objectiam/users/{userid}/s3keys/{key_id}` | キー ID で S3 キーを取得します。 


| 「削除」 | `/v2.1/objectiam/users/{userid}/s3keys/{key_id}` | キー ID に基づいて S3 キーを削除します。 
|===


==== オブジェクトストレージユーザの属性

次の表に、オブジェクトストレージユーザの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | オブジェクトストレージユーザの一意の識別子。 


| 「 display_name 」と入力します | 文字列 | ユーザの表示名。 


| 「テナント」 | 文字列 | ユーザが属しているサブテナントの名前。 


| 'ubtenant_id | 文字列 | ユーザが属しているサブテナントの識別子。 


| 「テナント」 | 文字列 | ユーザが属するテナントの名前。 


| 「 tenant_id 」 | 文字列 | ユーザが属しているテナントの識別子。 


| objectiam_user_urn` | 文字列 | URN 。 


| 'g_group_membership | 文字列 | NetApp StorageGRID グループのメンバーシップ。例： "sg_group_membership" ： ["5d2fb0f4f47df00015274e3"] 
|===


=== オブジェクトストレージユーザを読み出します

次の表に示すメソッドを使用して、すべてのオブジェクトストレージユーザまたは一部のオブジェクトストレージユーザを読み出します。「 ubtenant_id 」を指定すると、そのサブテナントに属するオブジェクトストレージグループのみが返されます。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/objectiam/users 」 | すべてのオブジェクトストレージユーザを読み出します。 | 「 ubtenant_id （文字列）」： IAM ユーザまたはグループに関連付けられているサブテナント ID 。「 offset 」および「 limit 」 - を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


==== ID を使用してオブジェクトストレージユーザを読み出します

次の表に示すメソッドを使用して、 ID 別にオブジェクトストレージの使用状況を取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/objectiam/users {id}` | ID を使用してオブジェクトストレージユーザを読み出します。 | id` ：オブジェクトストレージアカウント ID 。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


==== オブジェクトストレージユーザを作成する

次の表に示すメソッドを使用して、オブジェクトストレージユーザを作成します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/objectiam/users 」 | オブジェクトストレージユーザを新規に作成します。 | なし 
|===
要求の本文属性 : 「 display_name 」、「 ubtenant_id 」、「 g_group_membership 」

* 要求本文の例： *

....
{
  "display_name": "MyUserName",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "sg_group_membership": [
    "5ed5fa312c356a0001a73840"
  ]
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed603712c356a0001a7386c",
        "action": "create",
        "job_summary": "Activate request is successfully submitted",
        "created": "2020-06-02T07:44:49.647815816Z",
        "updated": "2020-06-02T07:44:49.647815816Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== オブジェクトストレージユーザを変更する

オブジェクトストレージユーザを変更するには、次の表に示すメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/objectiam/users/{id}` | ID で識別されるオブジェクトストレージユーザを変更します。 | id` ：オブジェクトストレージのユーザ ID 。 
|===
要求の本文属性 : 「 display_name 」、「 ubtenant_id 」、「 g_group_membership 」

* 要求本文の例： *

....
{
  "display_name": "MyModifiedObjectStorageUser",
  "subtenant_id": "5e57a465896bd80001dd4961",
  "sg_group_membership": [
    "5e60754f9b64790001fe937b"
  ]
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed604002c356a0001a73880",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:47:12.205889873Z",
        "updated": "2020-06-02T07:47:12.205889873Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== すべての S3 キーをオブジェクトストレージユーザにマッピングする

次の表に示すメソッドを使用して、すべての S3 キーをオブジェクトストレージユーザにマッピングします。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/objectiam/users/{user_id}/s3keys | オブジェクトストレージユーザの S3 キーを作成する。 | `user_id(string) ` ：オブジェクトストレージのユーザ識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z"
      }
    ]
....


==== オブジェクトストレージユーザの S3 キーを作成する

オブジェクトストレージユーザの S3 キーを作成するには、次のメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | `/v2.1/objectiam/users/{user_id}/s3keys | オブジェクトストレージユーザの S3 キーを作成する。 | `user_id(string) ` ：オブジェクトストレージのユーザ識別子。 
|===
要求本文属性 : 'expires' ( 文字列 )


NOTE: キーの有効期限日時は UTC で設定されます。将来設定する必要があります。

* 要求本文の例： *

....
{
  "expires": "2020-04-07T10:40:52Z"
}
....
* 応答本文の例： *

....
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z",
        "access_key": "PL86KPEBN6XT4T7UHNDE",
        "secret_key": "FlD/YWAM7JMr9gG8pumU8dzvcTLMzLYtUe2lNzcA"
      }
    ]
  }
}
....


==== キー ID を使用してオブジェクトストレージユーザの S3 キーを取得します

次の表に示すメソッドを使用して、オブジェクトストレージユーザの S3 キーをキー ID 別に取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/objectiam/users/{userid}/s3keys/{key_id}` | キー ID で S3 キーを取得します。  a| 
* `user_id(string) ` ：オブジェクトストレージのユーザ ID 。例： 5e66c77809a74c0001b89598
* 「 key_id ( 文字列 ) 」： S3 キー。例： 5e66de2509a74c0001b8957


|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecc7bb9b5d2730001f798fb",
        "display_name": "****************XCXD",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "objectiam_user_id": "5eb2212d1cbe3b000134762e",
        "objectiam_user": "MyUser",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "expires": "2020-05-27T00:00:00Z"
      }
    ]
  }
}
....


==== キー ID に基づいて S3 キーを削除します

次の表に示すメソッドを使用して、キー ID に基づいて S3 キーを削除します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/objectiam/users/{userid}/s3keys/{key_id}` | キー ID で S3 キーを削除します。  a| 
* `user_id(string) ` ：オブジェクトストレージのユーザ ID 。例： 5e66c77809a74c0001b89598
* 「 key_id ( 文字列 ) 」： S3 キー。例： 5e66de2509a74c0001b8957


|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
No content to return for succesful execution
....


=== オブジェクトストレージアカウント

次の表に示す方法を使用して、次の作業を実行します。

* オブジェクトストレージアカウントを取得、アクティブ化、または変更する。
* S3 バケットを作成する。


|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/objectstorage/accounts 」を参照してください | オブジェクトストレージアカウントを読み出します。 


| 「 GET 」 | `/v2.1/objectstorage/accounts/{id}` | ID を使用してオブジェクトストレージアカウントを読み出します。 


| 「 POST 」 | 「 /v2.1/objectstorage/accounts 」を参照してください | オブジェクトストレージアカウントを作成する。 


| 「 PUT 」 | `/v2.1/objectstorage/accounts/{id}` | ID で識別されるオブジェクトストレージアカウントを変更します。 


| 「削除」 | `/v2.1/objectstorage/accounts/{id}` | ID で識別されるオブジェクトストレージアカウントを変更します。 


| 「 GET 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | S3 バケットを取得します。 


| 「 POST 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | S3 バケットを作成する。 
|===


==== オブジェクトストレージアカウントの属性

次の表に、オブジェクトストレージアカウントの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | オブジェクトストレージユーザの一意の識別子。 


| 'ubtenant_id | 文字列 | サブテナントオブジェクトのインスタンスの識別子。 


| 'QUOTA_GB' | 整数 | 共有またはディスクのサイズ。 
|===


=== すべてのオブジェクトストレージアカウントを読み出します

次の表に示すメソッドを使用して、すべてのオブジェクトストレージアカウントまたは一部のオブジェクトストレージアカウントを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/objectstorage/accounts 」を参照してください | すべてのオブジェクトストレージユーザを読み出します。 | 「 offset 」および「 limit 」 - 。を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例 *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 19,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtenant",
        "subtenant": " MySubtenant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": "E- MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
}
....


==== ID を使用してオブジェクトストレージアカウントを読み出します

次の表に示すメソッドを使用して、 ID 別にオブジェクトストレージアカウントを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/objectstorage/accounts/{id}` | ID を使用してオブジェクトストレージアカウントを読み出します。 | id` ：オブジェクトストレージアカウント ID 。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtennant",
        "subtenant": " MySubtennant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": " MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
....


==== オブジェクトストレージアカウントをアクティブ化する

次の表に示す方法を使用して、オブジェクトストレージアカウントをアクティブ化します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/objectstorage/accounts 」を参照してください | オブジェクトストレージサービスをアクティブ化する。 | なし 
|===
要求の本文に必要な属性： 'ubtenant_id 、 QUOTA_GB

* 要求本文の例： *

....
{
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 20
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed608542c356a0001a73893",
        "action": "create",
        "job_summary": "Activate request for Sub Tenant MyNewSubtenant is successfully submitted",
        "created": "2020-06-02T08:05:40.017362022Z",
        "updated": "2020-06-02T08:05:40.017362022Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== オブジェクトストレージアカウントを変更する

次の表に示すメソッドを使用して、オブジェクトストレージアカウントを変更します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/objectstorage/accounts/{id}` | オブジェクトストレージサービスを変更する（クォータの変更など） | id(string) ` ：オブジェクトストレージアカウント ID 。 
|===
要求本文に必要な属性は 'name''`ubtenant_id 'quota_gb です

* 要求本文の例： *

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed609162c356a0001a73899",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T08:08:54.841652098Z",
        "updated": "2020-06-02T08:08:54.841652098Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== オブジェクトストレージアカウントを削除する

オブジェクトストレージアカウントを削除する前に、関連付けられているグループ、ユーザ、およびバケットをすべて削除しておく必要があります。次の表に示すメソッドを使用して、オブジェクトストレージアカウントを削除します。


NOTE: S3 互換ユーティリティを使用してバケットを削除します。NetApp Service Engine からバケットを削除することはできません。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/objectstorage/accounts/{id}` | オブジェクトストレージアカウントを削除する。 | id(string) ` ：オブジェクトストレージアカウント ID 。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "action": "string",
        "object_id": "5d2fb0fb4f47df00015274e3",
        "object_type": "string",
        "status": "string",
        "status_detail": "string",
        "last_error": "string",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "link": "string"
      }
    ]
  }
}
....


=== オブジェクトストレージバケット

次の表の API を使用して、オブジェクトストレージバケットの作成と読み出しを行います。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | オブジェクトストレージバケットの読み出し 


| 「 POST 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | オブジェクトストレージバケットを作成する。 
|===


==== オブジェクトストレージバケットの属性

次の表に、オブジェクトストレージバケットの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | オブジェクトストレージユーザの一意の識別子。 


| 「名前」 | 文字列 | バケット名。 


| 'ubtenant_id | 文字列 | バケットが属しているサブテナントの識別子。 
|===


==== S3 バケットを取得します

次の表に示すメソッドを使用して、 S3 バケットを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | S3 バケットを取得します。 | 「 ubtenant_id 」：バケットを所有するサブテナント。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "creationTime": "2020-06-02T08:13:25.695Z",
        "name": "mybucket"
      }
    ]
  }
}
....


==== S3 バケットを作成する

次の表に示すメソッドを使用して、 S3 バケットを作成します。


NOTE: バケットを作成するには、サブテナントのオブジェクトストレージアカウントが存在している必要があります。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/objectstorage/buckets' 」という 2 つのオプションがあります | S3 バケットを作成します。 | なし 
|===
要求の本文の必須属性：

* `name` ( 文字列 ): S3 バケット名 ( 小文字または数字のみ )
* 「 ubtenant_id 」（文字列）： S3 バケットが属しているサブテナントの ID


* 要求本文の例： *

....
{
  "name": "mybucket",
  "subtenant_id": "5ecefbbef418b40001f20bd6"
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed60a232c356a0001a7389e",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T08:13:23.105015108Z",
        "updated": "2020-06-02T08:13:23.105015108Z",
        "object_id": "5ed60a232c356a0001a7389f",
        "object_type": "sg_buckets",
        "object_name": "mybucket",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....