---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: Keystone ファイルサービス API 
---
= ファイルサービス API
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ファイルサービス API を使用して、ファイルサーバとファイル共有を表示および管理できます。

ファイル共有を作成する前に、ファイルサーバを作成してホストする必要があります。



== ファイルサーバ API

ファイルサーバ API を使用して、ファイルサーバを表示および管理できます。ファイルサーバの詳細については、を参照してください link:hsewebiug_create_a_file_server.html["ファイルサーバを作成します"]。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
/v2.1/fileservers
| すべてのファイルサーバの詳細を取得できます。ファイルサーバ ID 、名前、リージョン、ゾーン、テナント、 タグを使用できます。  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/filesServers/{id}`
| 特定のファイルサーバの詳細を取得できます。ファイルサーバの名前、リージョン、ゾーン、テナントなどの詳細を取得します。 入力した ID に基づいてタグを作成します。  a| 
id` ：ファイルサーバの ID 。



 a| 
「 POST 」
 a| 
/v2.1/fileservers
| ファイルサーバを作成できます。要求の本文に値を追加して、名前、サブテナント ID 、ゾーン、サブネット ID など、指定したパラメータでファイルサーバを作成します。  a| 
`name` ：ファイルサーバの名前。「 ubtenant_id 」：サブテナントの ID 。'zone' ：ゾーンの名前。'ubnet_id ' ：サブネットの ID



 a| 
「 POST 」
 a| 
'/v2.1/filesServers/{id}/`tags'
| ファイルサーバのタグを作成または置換できます。ファイルサーバの ID とタグの値を要求の本文に「 key:value pair 」の形式で追加します。  a| 
id` ：ファイルサーバの ID 。



 a| 
「 PUT 」
 a| 
`/v2.1/filesServers/{id}`
| 任意のファイルサーバを ID に基づいて変更できます。ファイルサーバの ID 、および名前、プロトコル、ゾーン、リージョン、タグなど、要求の本文で変更する値を追加します。  a| 
id` ：ファイルサーバの ID 。



 a| 
「削除」
 a| 
`/v2.1/filesServers/{id}`
 a| 
任意のファイルサーバを ID で削除できます。
 a| 
id` ：ファイルサーバの ID 。

|===
[NOTE]
====
ファイルサーバを削除する前に、そのサーバにマッピングされているファイル共有をすべて削除する必要があります。

CIFS 対応のファイルサーバを削除しても、 Active Directory コンピュータオブジェクトは削除されません。Active Directory 管理者に、削除したファイルサーバのコンピュータオブジェクトを手動で Active Directory から削除するよう依頼します。

====


== ファイル共有 API

ファイル共有 API を使用して、ファイル共有を表示および管理できます。ファイル共有の詳細については、を参照してください link:sewebiug_create_a_new_file_share.html["ファイル共有を作成します"]。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
`/v2.1/fileshares`
| すべてのファイル共有の詳細を取得できます。ID 、名前、 Snapshot ポリシー、プロトコルなどのファイル共有の詳細を取得します。 ファイルサーバの IP タグとタグ  a| 
offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/fileshares/{id}`
| 特定のファイル共有の詳細を取得できます。ID 、名前、 Snapshot ポリシー、プロトコル、ファイルサーバの IP など、ファイル共有の詳細を取得します。 入力した ID に基づいてタグを作成します。  a| 
id` ：ファイル共有の ID 。



 a| 
「 POST 」
 a| 
`/v2.1/fileshares`
| ファイル共有を作成できます。要求の本文に値を追加して、 ID 、名前、 Snapshot ポリシー、プロトコル、 ファイルサーバの IP タグとタグ  a| 
`name` ：ファイル共有の名前。「 hare_path 」：ファイル共有のパス。`fileserver_id : ファイルサーバの ID 。'size_GB' ：ファイル共有のサイズ（ GB 単位）「 service_level 」： Standard 、 Premium 、 Premium-Tiering 、 Extreme 、 Extreme のいずれかのサービスレベル名を指定できます。'protocol' ：ファイル共有へのアクセスに使用されるプロトコル（ NFS 、 CIFS 、またはマルチプロトコル）「 security_style 」：セキュリティ形式（ UNIX または NTFS ）。「 export_policy` ：ファイル共有のエクスポートポリシー。



 a| 
「 POST 」
 a| 
`/v2.1/fileshares/{id}/```Snapshot/{name}`
| ファイル共有の Snapshot を作成できます。  a| 
id` ：ファイル共有の ID 。`name` ：スナップショットの名前。



 a| 
「 POST 」
 a| 
`/v2.1/fileshares/{id}/`tags`
| ファイル共有のタグは、作成または置換できます。ファイル共有の ID とタグの値を、要求の本文に「 key ： value pair 」の形式で追加します。  a| 
id` ：ファイル共有の ID 。



 a| 
「 PUT 」
 a| 
`/v2.1/fileshares/{id}`
| 任意のファイル共有を ID に基づいて変更できます。名前、プロトコル、 Snapshot ポリシー、バックアップポリシー、タグなど、ファイルサーバの ID と変更する値を要求の本文に追加します。  a| 
id` ：ファイル共有の ID 。`name` ：ファイル共有の名前。'size_GB' ：ファイル共有のサイズ（ GB 単位）「 service_level 」： Standard 、 Premium 、 Premium-Tiering 、 Extreme 、 Extreme のいずれかのサービスレベル名を指定できます。'protocol' ：ファイル共有へのアクセスに使用されるプロトコル（ NFS 、 CIFS 、またはマルチプロトコル）「 export_policy` ：ファイル共有のエクスポートポリシー。



 a| 
「削除」
 a| 
`/v2.1/fileshares/{id}`
| 任意のファイル共有を ID で削除できます。  a| 
id` ：ファイル共有の ID 。



 a| 
「削除」
 a| 
`/v2.1/fileshares/{id}/```Snapshot/{name}`
| ファイル共有の ID および Snapshot 名に基づいて、ファイル共有の任意の Snapshot を削除できます。  a| 
id` ：ファイル共有の ID 。`name` ：スナップショットの名前。

|===

NOTE: CIFS 共有の場合、共有パスの末尾に「 $ 」文字を追加すると、「 pathtomyiddenshare$ 」のように非表示の共有になります。
