---
sidebar: sidebar 
permalink: seapiref_users.html 
keywords: netapp, keystone, users, 
summary: Keystone のユーザ 
---
= ユーザ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、サブテナントを取得、作成、変更、および削除します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/Users 」 | すべてのユーザのリストを取得します。 


| 「 GET 」 | `/v2.1/users/{id}` | ユーザ ID を使用してユーザを取得します。 


| 「 POST 」 | 「 /v2.1/Users 」 | 新しいユーザを作成します。 


| 「 PUT 」 | `/v2.1/users/{id}` | ユーザの詳細を変更します。 


| 「削除」 | `/v2.1/users/{id}` | ユーザを削除します。 


| 「 GET 」 | `/v2.1/users/{username}` | ユーザ名でユーザを取得します。 
|===


=== ユーザー属性

次の表に、ユーザ属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | ユーザの一意の識別子。 


| 「ユーザ名」 | 文字列 | ユーザ名。 


| 「 password 」と入力します | 文字列 | ユーザーのパスワード。 


| 「名」 | 文字列 | ユーザーの名。 


| 「 lastName 」 | 文字列 | ユーザーの姓です。 


| 「ディズプレイ名」 | 文字列 | ユーザーの表示名。 


| 「電子メール」 | 文字列 | ユーザーの電子メールアドレス。 


| 「電話」 | 文字列 | ユーザーの電話番号。 


| "profileImageURL" | 文字列 | ユーザのプロファイルイメージの URL 。 


| 「 tenant_id 」 | 文字列 | このユーザのプライマリテナント ID 。 


| 「在職期間」 | –  a| 
ユーザが属しているテナンシー。アレイは次のもので構成されています。

* 「 tenant_id 」、および
* 「 role_name 」これはユーザロールです。ユーザ、 admin 、 read 、 partner 、 または root 。




| 「プロバイダ」 | 文字列 | 認証プロバイダ : 「 local 」または「 ActiveDirectory 」 


| 「プロバイダデータ」 | –  a| 
認証プロバイダの詳細。構成は次のとおりです。

* 「 email_address 」、および
* 「 member_of 」 ( グループメンバーシップ )


|===


=== すべてのユーザを取得します

次の表に示すメソッドを使用して、すべてのユーザを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/Users 」 | すべてのユーザを取得します。 | なし 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5dddbe0ef071fe0001b889fd",
        "username": "TestUser3",
        "firstName": "Test",
        "lastName": "User",
        "displayName": "",
        "email": "testuser@netapp.com",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "admin"
          }
        ]
      }
    ]
  }
}
....


=== ID を使用してユーザを取得します

次の表に示すメソッドを使用して、 ID 別にユーザを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/Users 」 | ID を使用してユーザを取得します。 | `id (string) ` : ユーザの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e585df6896bd80001dd4b44",
        "username": "testuser01",
        "firstName": "",
        "lastName": "",
        "displayName": "",
        "email": "",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== ユーザ名でユーザを取得します

次の表に示すメソッドを使用して、ユーザ名ごとにユーザを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/Users 」 | ユーザ名でユーザを取得します。 | `username(string) ` ：ユーザのユーザ名。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== ユーザを作成します

次の表に示す方法を使用して、ユーザを作成します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/Users 」 | 新しいユーザを作成します。 | なし 
|===
要求本文の必須属性 : 'username'tenantid'tenanc'provider.

* 要求本文の例： *

....
{
  "username": "MyUser",
  "password": "mypassword",
  "firstName": "My",
  "lastName": "User",
  "displayName": "CallMeMyUser",
  "email": "user@example.com",
  "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e7c3af7aab46c00014ce877",
  "tenancies": [
    {
      "tenant_id": "5e7c3af7aab46c00014ce877",
      "role_name": "admin"
    }
  ],
  "provider": "local",
  "provider_data": {
    "email": "user@example.com",
    "member_of": "string"
  }
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed6f463129e5d000102f7e1",
        "username": "MyUser",
        "firstName": "My",
        "lastName": "User",
        "displayName": "CallMeMyUser",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e7c3af7aab46c00014ce877",
            "name": "MyTenant",
            "code": "mytenantcode",
            "role_name": "admin"
          }
        ]
      }
    ]
  }
}
....


=== ユーザを ID で変更します

次の表に示す方法を使用して、ユーザ ID 別にユーザを変更します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/users/{id}` | ユーザ ID で識別されるユーザを変更します。ユーザ名、表示名、パスワード、 E メールアドレス、電話番号、 プロファイルイメージの URL およびテナンシーの詳細。 | `id (string) ` : ユーザの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "password": "MyNewPassword",
   "firstName": "MyFirstName",
   "lastName": "MySurname",
   "displayName": "CallMeMYF",
   "email": "user@example.com",
   "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e5f1c4f253c820001877839",
  "tenancies": [
    {
      "tenant_id": "5e5f1c4f253c820001877839",
      "role_name": "user"
    }
  ]
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


=== ユーザを ID で削除します

次の表に示すメソッドを使用して、 ID 別にユーザを削除します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/users/{name}` | ID で識別されたユーザを削除します。 | `id (string) ` : ユーザの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
No content for succesful delete
....