---
sidebar: sidebar 
permalink: seapiref_subnets_apis.html 
keywords: netapp, keystone, subnets, networks, apis 
summary: Keystone ネットワーク API 
---
= サブネット API を使用してネットワーク設定を定義します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サブテナントおよびゾーンのサブテナントやサブテナント用のサブネットの表示と作成には、サブテナント API を使用します。これらのパラメータを使用してネットワーク設定を定義できます。

[cols="1,1,3,2"]
|===
| HTTP 動詞 | パス | 説明 | 必須パラメータ / 要求本文 


 a| 
「 GET 」
 a| 
`/v2.1/tenants /{tenant_id }/`zones /{zone_name}/subnets'
| テナントおよびゾーンのすべてのサブネットオブジェクトを取得できます。VLAN 、サブテナント、ゾーン、ルートなど、サブネットの詳細を取得します。 タグを使用できます。  a| 
tenant_id ：テナントの ID 。'zone_name' ：ゾーンの名前。offset ：結果セットの収集を開始する前にスキップする項目の数。`limit` ：返される項目の数。



 a| 
「 GET 」
 a| 
`/v2.1/tenants /{tenant_id }/`zones/{zone_name}/subnets/`{id}`
| テナントおよびゾーン用に作成された特定のサブネットオブジェクトの詳細を取得できます。VLAN 、サブテナント、ゾーン、ルートなど、サブネットの詳細を取得します。 入力した ID に基づいてタグを作成します。  a| 
tenant_id ：テナントの ID 。'zone_name' ：ゾーンの名前。id` ：サブネットの ID 。



 a| 
「 POST 」
 a| 
`/v2.1/tenants /{tenant_id }/`zones /{zone_name}/subnets'
| 特定のテナントおよびゾーン用のサブネットオブジェクトを作成できます。要求の本文に値を追加して、名前、 VLAN 、 CIDR 、サブテナント ID 、 ルート、およびタグ。  a| 
tenant_id ：テナントの ID 。'zone_name' ：ゾーンの名前。"{" 名前 " ： "string" 、 "vlan" ： "1000" 、 "CIDR" ： "10.0.0.0/24 、 "Subtenant _id" ： "5d2fb0f47df00015274e3" 、 "routes" ： [{" 宛先 " ： "10.0.0.0/24 、 "gateway" 、 "gateway" ： "0.1" 、 "value:"" 、 "21",""



 a| 
「 POST 」
 a| 
`/v2.1/tenants /{tenant_id }/`zones /{zone_name}/subnets/`{id}/tags'
| テナントのサブネットオブジェクトのタグを作成または置き換えることができます。サブネットオブジェクトの ID とタグの値を要求の本文に「 key ： value pair 」の形式で追加します。  a| 
tenant_id ：テナントの ID 。'zone_name' ：ゾーンの名前。id` ：バックアップオブジェクトの ID 。'{" key1":""<Tag 1> 、 "key2":""KEYN"" 、 "KEYN":""<Tag N>"}``

|===