---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Keystone サービスリクエスト 
---
= サービスリクエスト
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、サービス要求を作成および取得します。

|===


| HTTP メソッド | パス | 説明 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests` | サービスリクエストを取得します。 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests/{id}` | ID を使用してサービスリクエストを取得します。 


| 「 POST 」 | `/v2.1/tenants /{tenant_id }/servicests/` | サービスリクエストを作成します。 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests/categories | サービスリクエストカテゴリを取得します。 
|===


== サービスリクエストの属性

次の表に、サービス要求の属性を示します。

|===


| 属性 | を入力します | 説明 


| 「 ID 」 | 文字列 | サービスリクエストの識別子。たとえば、「 `S RQ0035952014`. 」のようになります 


| 「オブジェクト」 | 文字列 | サービスリクエストの件名。 


| 「 comment` 」 | 文字列 | サービスリクエストに関するコメント 


| 「 category` 」 | 文字列 | 要求のカテゴリ：バックアップ、ディザスタリカバリ、テクニカル、その他、またはサブスクリプション。 


| 「 priority 」 | 文字列 | サービスリクエストの優先度：非常に低い、低い、通常、高い、または緊急。 


| 「スクリュ」 | 文字列 | Zuora の登録番号。 


| 「責任」 | –  a| 
サブスクリプション契約の詳細：

* サービスレベル（文字列）：サービスレベル： Standard 、 Premium 、または Extreme 。
* New_commitment （整数）：必要な新しい合計容量。




| 「 zone 」 | 文字列 | ゾーン名。 


| 'ubtenant_id | 文字列 | サブテナントの ID 。 


| 'storage-object_type' | 文字列 | ストレージオブジェクトのタイプ：ファイルサーバまたはブロックストア。 


| 'storage-object_id' | 文字列 | ストレージオブジェクトの識別子。たとえば、「 5d2fb0fb4f47df00015274e3` 」のようになります 


| 「 service-type | 文字列 | サービスタイプ：ファイルサービス、ブロックストレージ、オブジェクトストレージ。 
|===


== サービスリクエストを取得します

次の表に示すメソッドを使用して、指定したテナントのサービス要求カテゴリを取得します。

|===


| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests` | サービスリクエストを取得します。 | `tenant_id ` ：（任意）指定したテナントのサービス要求を返します。「 offset 」および「 limit 」 - を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== ID を使用してサービスリクエストを取得します

次の表に示すメソッドを使用して、サービスリクエスト ID 別にサービスリクエストを取得します。

|===


| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests/{id}` | ID を使用してサービスリクエストを取得します。  a| 
* 'tenant_id ：テナント ID
* 「 id` ：サービスリクエスト ID 」例： SRQ0035952014


|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== サービスリクエストを作成します

次の表に示すメソッドを使用して、サービスリクエストを作成します。

|===


| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | `/v2.1/tenants /{tenant_id }/servicests/categories | サービスリクエストを作成します。 | `tenant_id`：テナントの識別子。 
|===
要求の本文に必要な属性：必要な属性は、サービス要求のカテゴリによって異なります。次の表に、要求の本文の属性を示します。

|===


| カテゴリ | 必須 


| サブスクリプション。 | `subscription` および `commitment` 


| ディザスタリカバリ | `storage_object_type`、 `subtenant_id`および `storage_object_id` 


| テクニカル | `subtenant_id` および `service_type`状況 `service_type` はファイルサービスまたはブロックストレージです。ゾーンは必須です。 


| その他 | ゾーン 
|===
* 要求本文の例： *

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== サービスリクエストカテゴリを取得します

次の表に、指定したテナントの読み出しサービス要求のカテゴリを示します。

|===


| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/tenants /{tenant_id }/servicests/categories | サービスリクエストカテゴリを取得します。 | `tenant_id:` （オプション）指定したテナントのサービス要求を返します。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....