---
sidebar: sidebar 
permalink: seapiref_storagegrid_instances.html 
keywords: netapp, keystone, storagegrid, instances, 
summary: Keystone StorageGRID インスタンス 
---
= StorageGRID インスタンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、オブジェクトストレージをサポートする StorageGRID インスタンスをセットアップおよび管理します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | /v2.1/storageggridinstances' | StorageGRID インスタンスを取得します。 


| 「 POST 」 | /v2.1/storageggridinstances' | オブジェクトストレージをホストする新しい StorageGRID インスタンスを作成します。 


| 「 GET 」 | `/v2.1/storagegridinstances/{id}` | ID を使用して StorageGRID インスタンスを取得します。 


| 「 PUT 」 | `/v2.1/storagegridinstances/{id}` | StorageGRID インスタンスを更新します。 
|===


=== StorageGRID インスタンスの属性

次の表に、 StorageGRID インスタンスの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | StorageGRID インスタンスの一意の識別子。 


| 「 name 」 | 文字列 | StorageGRID インスタンス名。 


| 'admin_rest_uri | 文字列（ $URI ） | StorageGRID 管理ノードエンドポイント。 


| '3_endpoints （エンドポイント） | 文字列（ $URI ） | StorageGRID エンドポイント。例： [`"https://s3.examplegrid.com"[]、 "https://s3.location.company.com"`[] ] 


| 「 GRID_NETWORK_USERNAME 」のように入力します | 文字列 | StorageGRID ユーザ名。 


| 「 GRID_NETWORK_PASSWORD 」 | 文字列 | StorageGRID のパスワード。 


| 「 tenant_username 」を参照してください | 文字列 | StorageGRID テナントのユーザ名。 


| 「 tenant_password 」を参照してください | 文字列 | StorageGRID テナントのパスワード。 


| 'subscription_number' | 文字列 | Zuora の登録番号。 
|===


=== StorageGRID インスタンスを取得します

次の表に示すメソッドを使用して、 StorageGRID インスタンスを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | /v2.1/storageggridinstances' | StorageGRID インスタンスを取得します。 | なし 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


=== ID を使用して StorageGRID インスタンスを取得します

次の表に示すメソッドを使用して、 StorageGRID インスタンスを ID 別に取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/storagegridinstances/{id}` | ID を使用して StorageGRID インスタンスを取得します。 | `id (string) ` ： StorageGRID インスタンスの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


=== ID を使用して StorageGRID インスタンスを作成します

次の表に示すメソッドを使用して、 ID 別に StorageGRID インスタンスを作成します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | `/v2.1/storagegridinstances/{id}` | ID を使用して StorageGRID インスタンスを取得します。 | id(string) ： StorageGRID インスタンスの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....


=== StorageGRID インスタンスを ID で変更します

次の表に示すメソッドを使用して、 StorageGRID インスタンスを ID 別に変更します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/storagegridinstances/{id}` | StorageGRID インスタンスを ID で変更します。 | `id (string) ` ： StorageGRID インスタンスの一意の識別子。 
|===
要求された要求本文属性 : 'none'

* 要求本文の例： *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....