---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Keystone のサービスレベル 
---
= サービスレベル
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、サービスレベルを取得、作成、変更、および削除します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/serviclevel 」を参照してください | すべてのサービスレベルを取得します。 


| 「 GET 」 | `/v2.1/serviclevel /{id}` | ID ごとにサービスレベルを取得します。 


| 「 POST 」 | 「 /v2.1/serviclevel 」を参照してください | 新しいサービスレベルを作成します。 


| 「 PUT 」 | `/v2.1/serviclevel /{id}` | サービスレベルの詳細を ID で変更します。 


| 「削除」 | `/v2.1/serviclevel /{id}` | サービスレベルを削除します。 
|===


== サービスレベルの属性

次の表に、サービスレベルの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | サービスレベルの一意の識別子。 


| 「 name 」 | 文字列 | サービスレベルの名前。 


| 概要 | 文字列 | サービスレベルの概要。 


| 'policy_name' | 文字列 | サービスレベルの Quality of Service （ QoS ；サービス品質）名。指定可能な値は、 NSE_VALUE 、 NSE_standard 、 NSE_performance 、および NSE_Extreme です。 


| 「利用可能」 | ブール値 | サービスレベルが使用可能かどうかを示します。 


| 「おじいさん」 | ブール値 | サービスレベルが廃止されたかどうかを示します。 


| 'peak_iops_per_tb | 整数 | TiB あたりの最大 IOPS 。 


| 'expected_iops_per_tb' | 整数 | TiB あたりの最小想定 IOPS 。 


| absolute_min_IOPS | 整数 | 想定 IOPS がこの値より低い場合に上書き値として使用される絶対最小 IOPS 。 


| 'peak_iops_allocation | 文字列 | ピーク IOPS の割り当て。有効な値は、 allocated space と used _space です。 


| 'io_block_size_kk` | 整数 | I/O ブロックサイズ（ KiB ）を指定します。 


| 「 _ サイズ _ GB 」 | 整数 | 最小サイズ（ GiB ）。 


| 「 mAX_SIZE 」 | 整数 | 最大サイズ（ GiB ）。 


| 「 mAX_peak_iops` | 整数 | サービスレベルの最大ピーク IOPS 。 


| 「 mAX_expected_IOPS」 | 整数 | 最大想定 IOPS 。 


| 'autogrow_max_percent | 整数 | 自動拡張の最大割合。 


| 「 ONTAP_Aggregates 」 | –  a| 
ONTAP アグリゲートのリスト。ONTAP アグリゲートは次の要素で構成されます。

* 'cluster_UIID: ONTAP クラスタ UUID
* 「 aggr_name ： ONTAP aggregate name 」のようになります
* 「 aggr_uuid ： ONTAP アグリゲート UUID 」
* 'node_name ： ONTAP cluster node name （例：


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| 'primary_volume_defaults' | –  a| 
* snapshot_auto_delete_target_free_space （整数）：このオプションは、 Snapshot コピーの自動削除を停止する空きスペースの割合を指定します。
* auto_size mode （文字列）：ボリュームのオートサイズモードです。有効な値は次のとおりです。 off 、 grow 、 grow_shrink 。例：


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


== サービスレベルを取得します

次の表に示すメソッドを使用して、すべてのサービスレベルを取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/serviclevel 」を参照してください | すべてのサービスレベルを取得します。 | なし 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== 名前ごとにサービスレベルを取得します

次の表に示すメソッドを使用して、サービスレベルを名前別に取得します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/serviclevel /{name}` | 名前ごとにサービスレベルを取得します。 | `name (string) ` ：サービスレベルの名前。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== サービスレベルを作成します

次の表に示すメソッドを使用して、サービスレベルを作成します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/serviclevel 」を参照してください | サービスレベルを作成します。 | なし 
|===
要求の本文属性 : 'name''policy_name

* 要求本文の例： *

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


== サービスレベルを変更します

次の表に示す方法を使用して、サービスレベルを変更します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/serviclevel /{name}` | サービスレベルの詳細を変更します。 | `name (string) ` ：サービスレベルの名前。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 応答本文の例： *

....
TBA
....


== サービスレベルを ID で削除します

次の表に示すメソッドを使用して、 ID 別にサービスレベルを削除します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/serviclevel /{name}` | ID で識別されたサービスレベルを削除します。 | `name (string) ` ：サービスレベルの名前。 
|===
* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
No content for succesful delete
....