---
sidebar: sidebar 
permalink: seapiref_ontap_clusters.html 
keywords:  
summary:  
---
= ONTAP クラスタ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
次の表に示すメソッドを使用して、 ONTAP クラスタを取得、作成、変更、および削除します。

|===
| HTTP メソッド | パス | 説明 


| 「 GET 」 | 「 /v2.1/ontapclusters 」を参照してください | すべての ONTAP クラスタを取得します。 


| 「 GET 」 | `/v2.1/ontapclusters/{id}` | ID を使用して ONTAP クラスタを取得します。 


| 「 POST 」 | 「 /v2.1/ontapclusters 」を参照してください | 新しい ONTAP クラスタを作成します。 


| 「 PUT 」 | `/v2.1/ontapclusters/{id}` | ID を使用して ONTAP クラスタのインベントリを更新します。 


| 「削除」 | `/v2.1/ontapclusters/{id}` | ONTAP クラスタを削除する 
|===


=== ONTAP クラスタの属性

次の表に、 ONTAP クラスタの属性を示します。

|===
| 属性 | を入力します | 説明 


| 「 id` 」 | 文字列 | ONTAP クラスタの一意の識別子。 


| 「 name 」 | 文字列 | ONTAP クラスタ名。 


| 「 uuuu` | 文字列 | ONTAP クラスタの Universal Unique Identifier （ UUID ）。 


| 「管理 IP 」 | 文字列 | ONTAP クラスタ管理 IPv4 アドレス。 


| 「ユーザ名」 | 文字列 | ONTAP クラスタ名 


| 「 password 」と入力します | 文字列 | ONTAP クラスタのパスワード 


| 「 provisioning _state 」を参照してください | 文字列  a| 
クラスタがプロビジョニング処理に使用できるかどうかを示します。オプションは次のとおりです。

* を開きます
* クローズしました




| 「 ATA_NETWORK_IP_CIDR` 」 | 文字列 | サブネットの CIDR 表記。 


| 「 ATA_NETWORK_DEFAULTGATEWAY 」 | 文字列 | IPv4 アドレス。 


| 「 ATA_network_ports 」と入力します | –  a| 
ONTAP クラスタのデータネットワークポートのリスト。

[listing]
----
For example:
[
  {
  "node_name": "dev-ots-per01-01",
  "port_name": "e0c-120",
  "parent_port": "e0c"
  }
]
----


| 「 intercluster_LIFs 」 | –  a| 
ONTAP クラスタのクラスタ間 LIF 。

[listing]
----
For example:
[
  {
  "name": "peer1",
  "node": "aff-01",
  "port": "a0a-103",
  "address": "10.128.113.232",
  "netmask": "255.255.255.0"
  },
{
  "name": "peer2",
  "node": "aff-02",
  "port": "a0a-103",
  "address": "10.128.113.233",
  "netmask": "255.255.255.0"
  }
]
----


| 'vm_root_service_level | 文字列 | ONTAP クラスタ Storage Virtual Machine （ SVM ）のルートサービスレベル名。指定できる値は、 Standard 、 Extreme 、または Premium です。このサービスレベルは、クラスタの下に作成されたすべての SVM にデフォルトで割り当てられます。クラスタには、前述のサービスレベル用のアグリゲートを関連付ける必要があります。 


| 「 zone 」 | 文字列 | ゾーン名。 


| 'subscription_number' | 文字列 | Zuora の購読。 


| 'ervices _available | –  a| 
利用可能なサービスとその状態のリスト。例：

[listing]
----
{
  "fcp": false,
  "iscsi": true,
  "nas": true
  }
----


| 「 ATA_FCP_Ports 」とは異なります | –  a| 
FCP 対応 ONTAP クラスタのノードおよびポートのリスト。例：

[listing]
----
[  {   "node_name": "aff-01",   "port_name": "0g"  },  {   "node_name": "aff-01",   "port_name": "0h"
  ]
----


| 'is_MCC | ブール値 | クラスタで MetroCluster が有効になっているかどうかを示します。デフォルトは False です。 


| 「 mcc_partner_cluster 」と入力します | 文字列 | MetroCluster ペア内の現在のクラスタのパートナークラスタの識別子。クラスタで MetroCluster が有効になっている場合は必須。 
|===


=== すべての ONTAP クラスタを取得します

すべての ONTAP クラスタまたは一部の ONTAP クラスタを取得するには、次の表に示すメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | 「 /v2.1/ontapclusters 」を参照してください | すべての ONTAP クラスタを取得します。 | 「 offset 」および「 limit 」 - を参照してください link:seapiref_netapp_service_engine_rest_apis.html#pagination>["共通ページ付け"] 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 2,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": []
      },
      {
        "id": "5eaf5249f038943eb46b6608",
        "name": "aff",
        "region": "au-east1",
        "zone": "au-east1-b",
        "uuid": "62d649d2-07a1-11e6-9549-00a0985c0dcb",
        "management_ip": "10.128.113.69",
        "username": "admin",
        "services_available": {
          "fcp": true,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "aff-01",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          },
          {
            "node_name": "aff-02",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          }
        ],
        "data_network_ip_cidr": "10.50.50.0/24",
        "data_network_default_gateway": "10.50.50.1",
        "svm_root_service_level": "premium",
        "intercluster_lifs": [
          {
            "name": "peer1",
            "node": "aff-01",
            "port": "a0a-103",
            "address": "10.128.113.232",
            "netmask": "255.255.255.0"
          },
          {
            "name": "peer2",
            "node": "aff-02",
            "port": "a0a-103",
            "address": "10.128.113.233",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00004635",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [
          {
            "node_name": "aff-01",
            "port_name": "0g"
          },
          {
            "node_name": "aff-01",
            "port_name": "0h"
          },
          {
            "node_name": "aff-02",
            "port_name": "0g"
          },
          {
            "node_name": "aff-02",
            "port_name": "0h"
          }
        ],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== ID を使用して ONTAP クラスタを取得します

ID を使用して ONTAP クラスタを取得するには、次の手順を実行します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 GET 」 | `/v2.1/ontapclusters/{id}` | ID で識別されている ONTAP クラスタを取得します。 | id(string) ` ： ONTAP クラスタの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


=== ONTAP クラスタを作成する

次の表の API を使用して、 ONTAP クラスタを作成します。

ONTAP クラスタは、常に iSCSI サービスを有効にして作成されます。FCP サービスは、インフラでサポートされている場合に必要に応じて有効にすることができます。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 POST 」 | 「 /v2.1/ontapclusters 」を参照してください | ONTAP クラスタを作成する | なし 
|===
要求の本文属性 : 'name'uu'management_ip'username'password', 「 ATA_NETWORK_IP_CIDR`, `d ATA_NETWORK_DEFAULT_GATEWAY 」 , 「 intercluster_LIFs 」 , 「 zone 」のようになります

FCP が有効になっている場合 (`erviss_available`fcp 属性を使用して ) 'd ata_fcp_ports' が必要です

'is_MCC' が true の場合 '`mcc_partner_cluster' が必要です

* 要求本文の例： *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "clustername-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "clustername-01-icl01",
      "node": "clustername-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "extreme",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": true
  },
  "data_fcp_ports": [
  ],
  "is_mcc": false,
}
....
* 応答本文の例： *

....
{
    "status": {
        "user_message": "Okay. New resource created.",
        "verbose_message": "",
        "code": 201
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "clustername-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "extreme",
                "intercluster_lifs": [
                    {
                        "name": "clustername-01-icl01",
                        "node": "clustername-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== ONTAP クラスタを変更

ONTAP クラスタを変更するには、次のメソッドを使用します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「 PUT 」 | `/v2.1/ontapclusters/{id}` | ID で識別される ONTAP クラスタの詳細を変更します。 | id(string) ` ： ONTAP クラスタの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "dev-ots-syd01-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "dev-ots-syd01-01-icl01",
      "node": "dev-ots-syd01-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "standard",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": false
  },
  "data_fcp_ports": [
  ]
}
....
* 応答本文の例： *

....
{
    "status": {
        "user_message": "Okay. Accepted for processing.",
        "verbose_message": "",
        "code": 202
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "dev-ots-syd01-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "standard",
                "intercluster_lifs": [
                    {
                        "name": "dev-ots-syd01-01-icl01",
                        "node": "dev-ots-syd01-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


=== ONTAP クラスタを削除する

次の表に示す方法を使用して、 ONTAP クラスタを削除します。

|===
| HTTP メソッド | パス | 説明 | パラメータ 


| 「削除」 | `/v2.1/ontapclusters/{id}` | ID で識別された ONTAP クラスタを削除します。 | id(string) ` ： ONTAP クラスタの一意の識別子。 
|===
要求本文の必須属性 : 「なし」

* 要求本文の例： *

....
none
....
* 応答本文の例： *

....
No content for succesful delete
....