---
sidebar: sidebar 
permalink: sewebiug_view_host_groups.html 
keywords: netapp, keystone, view, host, groups, 
summary: Keystone によってホストグループが表示される 
---
= ホストグループを操作する
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ホストグループは、ディスクへのアクセスを決定するために定義されます。ホストグループに割り当てられているイニシエータノードに基づいて、そのホストグループへのアクセスが決定されます。



== ホストグループを表示します

ホスト・グループのリストを表示するには ' メニューから *block storage > Host Groups * を選択します

定義済みのホストグループが一覧表示されます。

このページでは、新しいホストグループの作成、ホストグループの変更、およびホストグループの削除を行うことができます。



= ホストグループを作成します

ホストグループを作成するには、次の 2 つの方法があります。

* 以下で説明する [ ホストグループ ] ページから実行します。
* 新しいディスクを作成する際に使用します。この方法は、まだ初期化されていないブロックストアにホストグループを作成する必要がある場合に使用します。詳細については、を参照してください link:sewebiug_create_a_new_disk.html#create-a-new-disk["新しいディスクを作成します"]。
+
空のホストグループを作成し、プレースホルダとしてディスクにマッピングすることができます。ストレージにアクセスするには、空のホストグループを更新してイニシエータを追加する必要があります。





=== 作業を開始する前に

ホストグループを作成するには、次のものが必要です。

* ホストグループを作成するサブテナント、リージョン、およびゾーン。



NOTE: サブテナント / ゾーンの組み合わせのブロックストアが以前に初期化されていない場合は、このメソッドを使用してホストグループを作成することはできません。もう 1 つの方法は、を参照することです link:sewebiug_create_a_new_disk.html#create-a-new-disk["新しいディスクを作成します"] プロセス。ブロックストアを初期化し、そのプロセスの一環としてホストグループを作成することができます。

* ホストグループの名前
* ホストグループプロトコル： iSCSI または FCP
* グループに追加するイニシエータのリスト。 FC ホストノードの場合は WWPN 、 iSCSI ホストノード名の場合は IQN 。
* 各イニシエータのエイリアス。エイリアスは、イニシエータサーバを識別する単純な名前、またはサーバ上の個々のポート / インターフェイスです。たとえば、「サーバ 4 」と入力します。




=== 手順

. link:sewebiug_view_host_groups.html#view-host-groups["ホストグループを表示します"] リスト
. [Create Host Group] をクリックします。
. Create Host Group ページで、次の手順を実行します。
+
.. プロトコルとして iSCSI または FCP を選択します。
.. サブテナント、リージョン、およびゾーンを選択し、ホストグループに対してを選択します。


. ホストグループの名前を指定します。
. OS Type ：ディスクオペレーティングシステムを選択します。
. グループのイニシエータを追加します。各イニシエータに対して、エイリアスとイニシエータを指定します。
. 必要に応じて、タグセクションのホストグループにタグ（キーと値のペア）を追加します。
. [ 作成（ Create ） ] をクリックします。ホストグループが作成されます。




=== 完了後

作成されたホストグループは、ディスクにマッピングできます。



== ホストグループを変更します

ホストグループを変更して、イニシエータを追加、削除、または変更できます。

ホストグループを変更すると、そのホストグループにマッピングされている各ディスクのアクセスが変更されます。

イニシエータのエイリアスは変更できません。エイリアスを変更するには、グループからイニシエータを削除してから、作成し直してください。



=== 手順

. を表示します link:sewebiug_view_host_groups.html#view-host-groups["ホストグループ"] リスト
. リストからホストグループを選択し、そのホストグループの [Edit] アイコンをクリックします。
+
既存のイニシエータを変更するには、リストからイニシエータを探してイニシエータの値を編集し、 * Update * をクリックします。

+
イニシエータを追加します。

+
.. [ イニシエータの追加 ] をクリックします。
.. エイリアスとイニシエータを指定します。
.. [ 作成（ Create ） ] をクリックします。
+
ホストグループからイニシエータを削除するには、リストでイニシエータを特定し、削除アイコンをクリックします。



. [ 完了（ Done ） ] をクリックします。




== ホストグループを削除する

ホストグループにマッピングされたディスクがない場合は、ホストグループを削除できます。



=== 手順

. を表示します link:sewebiug_view_host_groups.html#view-host-groups["ホストグループ"] リスト
. リストからホストグループを選択し、そのホストグループの削除アイコンをクリックします。
. 削除の確認ダイアログで、ホストグループ名を入力して、ホストグループを削除することを確認します。
. [* 確認 *] をクリックします。

