---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: バックアップを作成、変更、削除したり、バックアップからリストアしたりできます 
---
= ファイル共有とディスクをバックアップする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
環境で作成されたボリューム（ファイル共有およびディスク）の Snapshot （バックアップまたはリカバリポイント）を表示および管理して、プライマリファイル共有およびディスクの複数のコピーをリモートで保持できます。

レプリケートされたファイル共有と異なるゾーンのディスクは、各クラスタの専用のバックアップ Storage VM （ Storage Virtual Machine （ SVM ）に格納されます。バックアップは、異なるゾーンにある 2 つの独立した ONTAP クラスタ間で実行できます。NetApp Service Engine でサポートされる標準のバックアップポリシーは次のとおりです。

* アドホック
* 毎日
* 毎週
* 毎月


NetApp Service Engine でサポートされている標準のバックアップポリシーに従っていないボリュームを使用することは可能です link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["サービスリクエストを提出します"] 問題を固定する * 非標準ボリューム * カテゴリ。


NOTE: アドホック（スケジュールされていない）バックアップは、 GUI または API を使用していつでも手動で実行できます。

ファイル共有およびディスクに対して作成された Snapshot のリストは、「 * Backups * 」ページに表示できます。バックアップは選択したテナントに基づいて表示されます。



== バックアップオブジェクトを作成する

ボリュームの Snapshot を作成するには、作成時にバックアップポリシーを定義します link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html["ファイル共有を作成します"] または link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_disk.html["ディスクを作成します"]。

.手順
. Enable * Backup Policy * 」を選択します。
. バックアップゾーンと、アドホック、毎日、毎週、または毎月のいずれかの単位で作成するバックアップの数を指定します。
. [ 作成（ Create ） ] をクリックします。



NOTE: 既存のファイル共有またはディスクのバックアップポリシーを編集して、バックアップを作成またはスケジュール設定することもできます。



== バックアップオブジェクトを変更する

ファイル共有またはディスクの選択したバックアップオブジェクトに対して、バックアップを無効にするか、ソースからバックアップオブジェクトの接続を解除して、孤立したバックアップにすることができます。ソースとの SnapMirror 関係を解除します。アドホック、毎日、毎週、または毎月のいずれかの単位で作成されるバックアップの数を変更することもできます。

.手順
. リストでバックアップを見つけ、そのオブジェクトの行の最後にある編集アイコンをクリックします。
. 必要に応じて、バックアップのソースおよび各タイプのバックアップの数を変更します。ソースボリュームとの SnapMirror 関係を解除するには、バックアップのソースを「 * None （ orphaned ）」に変更します。ソースボリュームが削除された場合でも、バックアップは孤立したバックアップとして保持されます。バックアップオブジェクトの状態が変化し、ソースボリュームのステータス（孤立または削除）が同じリストのソースボリューム名に追加されます。オブジェクトの状態については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["こちらをご覧ください"]
. [ 完了（ Done ） ] をクリックします。Snapshot が変更されます。ソースとの SnapMirror 関係を解除した場合、つまり、バックアップオブジェクトが孤立した場合は、「 * Backups * 」タブのソース名は「削除済み」と表示されます。



NOTE: また、ボリュームの * バックアップポリシー * を無効にすることにより、ソースボリュームとの SnapMirror 関係を解除することもできます。



== バックアップオブジェクトを削除する

未使用のバックアップボリュームを削除してストレージスペースを増やします。

.手順
. リストでバックアップを見つけ、そのオブジェクトの行の最後にある削除アイコンをクリックします。
. Confirm Delete * （削除の確認）ダイアログボックスで、バックアップオブジェクトを削除することを確認するためのバックアップ名（ソースボリューム名）を入力します。
. [* 確認 *] をクリックします。



NOTE: バックアップを削除すると、そのバックアップのすべてのリカバリポイントが削除されます。また、プライマリファイル共有またはディスクを削除した場合でも、バックアップは孤立したバックアップとして保持され、リストアのためのすべてのリカバリポイントが含まれます。削除されたソースのバックアップ・ボリュームおよびリカバリ・ポイントを削除するには、 [*Backups] タブからバックアップ・オブジェクトを明示的に削除する必要があります。



== バックアップのリストア

可能です link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["サービスリクエストを提出します"] 特定のリカバリポイントからファイル共有またはディスクをリストアする場合。

.手順
. 左側のナビゲーションペインで * support * を選択し、 * Service Requests * を選択します。
. [ 新しいサービスリクエスト ] をクリックします。
. サービスリクエストのカテゴリとして「 * バックアップリストア * 」を選択します。
. その他の詳細を指定して次に進みます。

