---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Keystone サブスクリプションを管理する 
---
= サブスクリプションの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サブスクリプションの管理には、NetApp Keystone サブスクリプションサービスおよびテナントサブスクリプションサービスへのサービスレベルの割り当て、またはNetApp Service Engineインターフェイスを使用したサービスレベルへの容量の割り当てと変更が含まれます。

サービスプロバイダ/パートナー様とネットアップの関係で表されるサブスクリプションサービスとテナントサブスクリプションは、サービスプロバイダとそのテナントおよびサブテナント（エンドユーザ）の関係を表します。ネットアップの管理者またはGSSCがパートナー様とテナント向けのKeystoneサブスクリプションサービスを作成する場合、ストレージの割り当てが完了していることを意味します。ただし、サービスレベルが作成され、対応する容量の割り当てが完了していないかぎり、サブテナントやエンドユーザはストレージを使用できません。パートナー様の管理者は、Keystoneサブスクリプションサービスとテナントサブスクリプションのストレージを管理できます。テナント管理者は、テナントサブスクリプションの詳細とテナント独自のテナントサービスのみを表示できます。



== Keystoneサブスクリプションを管理

パートナー様の管理者は、*サブスクリプション*>* Keystoneサブスクリプション*からKeystoneサブスクリプションサービスを表示および管理できます。* Keystoneサブスクリプション*は、ネットアップの管理者がパートナー様向けに作成するKeystoneサブスクリプションサービスです。パートナー様の管理者は、Keystoneサブスクリプションサービスを表示し、次の目的でサービスリクエストを作成できます。

* サブスクリプションの容量を増やします
* サブスクリプションへのサービスの追加（サービスレベルと容量の割り当て）


サービスリクエストはサポートチームが受け取り、対応します。

サブスクライブしているデータ保護サービスと高度な保護サービスを別々のタブで表示および管理することもできます。詳細については、を参照してください link:index.html#flex-subscription["データ保護とデータ保護の詳細"]。



=== サブスクリプションの容量を増やします

拡張要件を満たすために、サブスクライブされている任意のサービスレベルのコミット済み容量を増やすことができます。

.手順
. 容量を増やすサブスクリプションをドロップダウンメニューから選択します。
. 目的のサービスレベルの [ 容量の増加 ] をクリックします。
. 必要な容量（ TiB ）を指定します。
. [*確認*]をクリックします。[ Keystoneサブスクリプションの管理]ページに戻ります。
. [Submit Changes] をクリックします。GSSCのサービスリクエストが作成され、容量が増加します。サービスリクエストの進捗状況は、メッセージに表示されたSR番号で確認および追跡できます。トラッキングの詳細については、を参照してください link:sewebiug_track_a_service_request.html["サービスリクエストを追跡します"]。




=== サービスをサブスクリプションに追加します

サービスをサブスクリプションに追加できます。サービスの追加には、サブスクリプションにサービスレベルを割り当て、同じサービスレベルの容量を指定します。

各サブスクリプションには、各サービスレベルのいずれかを設定できます。たとえば、サブスクリプションにExtremeサービスとStandardサービスがすでに含まれている場合は、PremiumサービスまたはBlockサービスを追加できます。

.手順
. サブスクリプションに追加するサービスレベルをドロップダウンメニューから選択します。
. [ サービスの追加 ] をクリックします。
. 通知依頼を設定するサービス・レベルをドロップダウン・メニューから選択し（例：「エクストリーム階層化」）'サービス・レベルにコミットする容量（TiB）を追加します
. [* 確認 *] をクリックします。Manage Keystone Subscriptionsページに戻ります。
. [Submit Changes] をクリックします。GSSCのサービスリクエストが作成され、サービスレベルがサブスクリプションに割り当てられます。サービスリクエストの進捗状況は、メッセージに表示されたSR番号で確認および追跡できます。


トラッキングの詳細については、を参照してください link:sewebiug_track_a_service_request.html["サービスリクエストを追跡します"]。



== テナントサブスクリプションを管理します

パートナー管理者の場合は、テナントサブスクリプション * > * テナントサブスクリプション * からテナントサブスクリプションを作成、表示、更新できます。テナント管理者の場合、表示できるのはサブスクリプションだけです。



=== テナントサブスクリプションを作成および編集します

テナントの新しいサブスクリプションを作成できます。

.手順
. [ 新規サブスクリプション ] をクリックします。
. 地域、ゾーン、サブスクリプション期間、レートプラン、およびその他の詳細を指定します。テナントサブスクリプションは、選択したゾーンに基づいて Keystone サブスクリプションに割り当てられます。これは、 Keystone サブスクリプションがそれぞれゾーンに関連付けられているためです。
+

NOTE: 重複するサブスクリプションは作成できません。指定した開始日よりも前の日にサブスクリプションが開始されるため、開始日は少なくとも翌日にする必要があります。また、現在の日付から 30 日以内にする必要があります。

. [ 作成（ Create ） ] をクリックします。


サブスクリプションを削除することはできません。既存のテナントサブスクリプションを編集して新しいサービスレベルを追加したり、サービスレベルのコミット済み容量を増やしたり、サブスクリプションにタグを追加したりすることのみができます。

パートナー管理者は、テナントサブスクリプションを編集できます。サブスクリプションに新しいサービスレベルを追加したり、追加済みのサービスレベルの容量を編集したりできます。新しいサービスレベルを追加するには、次の手順を実行します。

.手順
. [+]アイコンをクリックして'編集するサブスクリプションを選択します
. [サブスクリプションへの新しいサービスレベルの追加*]ページで、新しいサービスレベルを選択し、必要な容量を追加します。サービスレベルがすでに追加されている場合は、追加または削除することはできません。
. [ 更新（ Update ） ] をクリックします。


また、購読のタグアイコンをクリックしてタグを追加することもできます。

サブスクリプションにすでに割り当てられているサービスレベルにサブスクライブ済み容量を編集するには、次の手順を実行します。

.手順
. をクリックして'編集するサブスクリプションを展開しますそのためには'V'アイコンをクリックしますそのサブスクリプションのサービスレベルが表示されます。
. それぞれのペン編集アイコンをクリックして、編集するサービスレベルを選択します。
. TiBの容量を増減して、料金プランを変更します。
. [ 更新（ Update ） ] をクリックします。

