---
sidebar: sidebar 
permalink: sewebiug_create_a_disk_from_a_snapshot.html 
keywords: netapp, keystone, create, disk, Snapshot 
summary: Snapshot からディスクを作成します 
---
= Snapshot からディスクを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既存の Snapshot から新しいディスクを作成できます。Snapshot からクローニングされた新しいディスクには、 Snapshot の作成元のディスクと同じプロパティが適用されます。

.手順
. 左側のナビゲーションペインから *Block Storage* を選択し、 *Disks* を選択します。
. Create Disk （ディスクの作成）をクリックし、 * Clone from snapshot （スナップショットからのクローン） * を選択します。テナントのすべてのディスクが表示された * ディスクの選択 * 画面が表示されます。ディスクは、リージョン、ゾーン、およびサブテナントでフィルタできます。動作状態のディスクを選択することができます。
. 目的のディスクの横にあるチェックボックスをオンにして、「 * 次へ * 」をクリックします。Select Snapshot * （スナップショットの選択）画面が表示され、ディスクのすべてのスナップショットが表示されます。
+

NOTE: 選択したディスクについて、 SnapCenter Service Engine の外部の 環境に作成された Snapshot がある場合、それらの Snapshot がインポートされ、選択した Snapshot のリストに表示されます。インポートされたこれらの Snapshot を選択し、そこから新しいディスクのクローンを作成できます。

+
特定の Snapshot を検索するか、スケジュールタイプを選択して Snapshot をフィルタリングできます。

. クローンを作成するスナップショットの横にあるチェックボックスをオンにし、 * 次へ * をクリックします。新しいディスクは、選択した Snapshot のプロパティを継承します。
. 名前 * とディスクパス * を追加します。サービスレベル * の割り当てなどの他の設定を更新し、 [*Create] をクリックします。


* ディスクの作成 * は非同期ジョブとして実行されます。可能です

* ジョブリストでジョブのステータスを確認します。ジョブの追跡については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["こちらをご覧ください"]。
* ジョブが完了したら、ディスクのステータスを「 * ディスク * 」リストで確認します。

