---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone によってユーザの S3 キーが作成される 
---
= ユーザの S3 キーを作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ユーザの S3 キーを作成するには、このメソッドを使用します。

キーは作成後すぐにキャプチャしてください。キーの詳細を作成したあとで取得することはできません。

.手順
. オブジェクトストレージユーザを表示します link:sewebiug_view_the_object_storage_group_and_users.html["オブジェクトストレージグループおよびユーザを表示します"]。
. 正しいサブテナントが選択されていることを確認し、「* users *」タブをクリックします。
. リスト内でユーザを検索し、そのグループのキーアイコンをクリックします。
+
リスト内の項目の操作の詳細については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["リストビューアクションをリスト表示します"]。

. Manage S3 Keys *ダイアログボックスに、ユーザのキーのリストが表示されます。キーの詳細については、を参照してください https://["ポリシーで権限を指定します"]。
. ユーザに既存のキーがない場合は、 * S3 キーの作成 * をクリックしてフィールドを表示し、キーを作成します。
. キーを期限切れにする場合は、有効期限と有効期限を UTC で指定します。それ以外の場合は、これらのフィールドにデフォルト値をそのまま使用します。
. キーを作成するには、チェックマークをクリックします。S3 Key Details *ダイアログボックスが表示され、アクセスキーとシークレットキーが表示されます。
. アクセスキーと秘密キーの両方をコピーし、ユーザーに詳細を通知します。
+
S3 Key Details *（S3キーの詳細*）ダイアログボックスを閉じる前に、キーの詳細が記録されていることを確認します。閉じた後、キーの詳細が隠され、キーを取得できなくなります。

. [* 閉じる * ] をクリックします。
. もう一度 * Close * をクリックして Manage S3 Keys ダイアログを閉じます。

