---
sidebar: sidebar 
permalink: sewebiug_alerts.html 
keywords: netapp, keystone, alert, create, custom alert 
summary: アラートを作成および管理します 
---
= アラートを作成および管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アラートは、環境内の重要なイベントに関する情報を共有するために、自動でトリガーされるか手動で作成されるメッセージです。

ストレージをプロビジョニングすると、次の場合に自動アラートがトリガーされます。

* 新しいディスクまたはファイル共有によって、サブスクリプションがバーストにプッシュされます
* 新しいディスクまたはファイル共有は、新しいサブスクリプションでプロビジョニングされます
* サブスクリプション内の使用済み容量がしきい値を超えたか、またはコミット済み容量に近づいています


[* アラート * （ * Alerts * ） ] 画面を使用すると、システムで生成されたアラートとユーザーが生成したアラートを環境内で表示できます。

また、カスタムアラートを作成して他のユーザに表示することもできます。必要に応じて、自分自身および他のユーザのテナント内のアラートを表示および却下できます。



== マルチテナント環境でアラートを作成します

パートナー管理者は、アラートを手動で作成し、 1 つまたは環境内のすべてのテナントに送信できます。


NOTE: 作成したアラートを却下することができます。ただし、まだ表示していないテナントに対してのみ却下されます。

.手順
. メニューから * Administration * > * Alerts * を選択します。
. ［ * アラートの作成 * ］ をクリックします。
. ［ * アラートの作成 * ］ 画面で、アラートの送信先となるステータスとテナントを選択し、メッセージを追加します。
+

NOTE: 環境内のすべてのテナントにアラートを送信する場合は、「すべて」を選択します。

. [ 作成（ Create ） ] をクリックします。新しいアラートが作成されます。




== テナンシーにアラートを作成します

テナント管理者の場合は、環境内のすべてのユーザに手動でアラートを作成して送信できます。


NOTE: 作成したアラートを却下することができます。ただし、まだ表示していないユーザに対してのみ却下されます。

.手順
. メニューから * Administration * > * Alerts * を選択します。
. ［ * アラートの作成 * ］ をクリックします。
. ［ * アラートの作成 * ］ 画面でステータスを選択し、メッセージを追加します。
. [ 作成（ Create ） ] をクリックします。新しいアラートが作成されます。

