---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, snapshot 
summary: Snapshotからファイル共有を作成します 
---
= Snapshotからファイル共有を作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既存のSnapshotから新しいファイル共有を作成できます。Snapshotからクローニングされた新しいファイル共有には、Snapshotの作成元のファイル共有と同じプロパティが含まれます。

.手順
. 左側のナビゲーションペインで * ファイルサービス * を選択し、 * 共有 * を選択します。
. Create Share （共有の作成） * をクリックし、 * Clone from snapshot （スナップショットからのクローン） * を選択しますまたは、スナップショットをクローニングに使用する共有がわかっている場合は、ファイル共有を探してその横にあるコピーボタンをクリックします。共有は動作状態である必要があります。オブジェクトの状態については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["オブジェクトの状態"]。テナントのすべてのファイル共有を含む* Create Share from Snapshot *（スナップショットからの共有の作成）画面が表示されます。ファイル共有は、リージョン、ゾーン、およびサブテナントでフィルタできます。動作状態の任意のファイル共有を選択できます。
. 目的のファイル共有の横にあるチェックボックスをオンにし、 * Next * （次へ）をクリックします。ファイル共有のSnapshotが表示されます。
+

NOTE: 選択したファイル共有について、SnapCenter Service Engine以外の環境で作成されたSnapshotがある場合、それらのSnapshotがインポートされ、選択したSnapshotのリストに表示されます。インポートしたこれらのSnapshotを選択し、そこから新しいファイル共有のクローンを作成できます。

+
特定のSnapshotを検索するか、スケジュールタイプを選択してSnapshotをフィルタリングできます。

. クローンを作成するスナップショットの横にあるチェックボックスをオンにし、* Next *（次へ）をクリックします。新しいファイル共有には、選択したSnapshotのプロパティが継承されます。
. 名前 * と * 共有パス * を追加します。サービスレベル * の割り当てなどの他の設定を更新し、 [*Create] をクリックします。ニーズに最も適したサービスレベルを選択します。


.完了後
* CIFS タイプの共有の場合のみ：ホスト名で共有を使用できるようにするには、ドメイン管理者が DNS レコードを CIFS サーバ名および IP アドレスで更新する必要があります。それ以外の場合、共有には IP アドレスを使用してのみアクセスできます。例：
+
** DNS レコードが更新されたら、ホスト名または IP を使用して共有にアクセスします。例 file://["\\ ホスト名 \ 共有"^] または file://["\\ IP \ 共有"^]
** DNS レコードを更新しない場合は、 IP アドレスを使用して共有にアクセスする必要があります file://["\\ IP \ 共有"^]


* * 共有の作成 * は非同期ジョブとして実行されます。可能です
+
** ジョブリストでジョブのステータスを確認します。ジョブの追跡については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["こちらをご覧ください"]。
** ジョブが完了したら、共有リスト * で共有のステータスを確認します。



