---
sidebar: sidebar 
permalink: sewebiug_managing_tenants_and_subtenants.html 
keywords: netapp, keystone, managing, subtenants, 
summary: Keystone がサブテナントを管理する 
---
= テナントとサブテナントを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Service Engine を使用して、テナントとサブテナントを表示および管理できます。初期のテナンシーは、ネットアップのサポート部門がサービスプロバイダやパートナー、テナントに合わせてセットアップします。リージョン、ゾーン、およびサブスクリプションはすでにサポートによって設定されており、テナントとサブテナントをテナントの下に作成するときに使用できます。



== テナント

パートナー管理者の場合は、テナントの作成、変更、削除を * Administration * > * tenants * から実行できます。テナント管理者は、各自のテナントサブスクリプションとサブテナントのみを表示できます。パートナーテナンシーのテナントに対しては、ネットワークを定義することもできます。



=== テナントを作成します

パートナー管理者の場合はテナントを作成できます。テナントごとにネットワークを作成して管理することもできます。ネットワークの作成の詳細については、を参照してください link:sewebiug_define_network_configurations.html["サブネットを使用してネットワーク設定を定義します"]。

.手順
. Create Tenant * をクリックします。
. 名前とコードを追加します。テナントを表すコードは、 NetApp Service Engine インスタンス内で一意で、小文字で構成されている必要があります。
. [ 作成（ Create ） ] をクリックします。



NOTE: 既存のテナントの名前と概要のみを変更できます。また、サブテナントやストレージコンポーネントが関連付けられているテナントは削除できません。



== サブテナント

パートナー管理者またはテナント管理者は、サブテナントを表示および管理できます。



=== サブテナントを作成します

パートナー管理者またはテナント管理者は、 * Administration * > * Subtenants * からサブテナントを作成、変更、および削除できます。また、サブテナントごとにネットワークを作成および管理することもできます。

ネットワークの作成の詳細については、を参照してください link:sewebiug_define_network_configurations.html["サブネットを使用してネットワーク設定を定義します"]。

.手順
. 「 * サブテナントを作成 * 」をクリックします。
. 名前とコードを追加します。サブテナントを表すコードは、 NetApp Service Engine インスタンス内で一意で、小文字で構成されている必要があります。
. [ 作成（ Create ） ] をクリックします。



NOTE: 既存のサブテナントの名前は変更のみ可能です。また、ストレージコンポーネントが関連付けられているサブテナントは削除できません。
