---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: バックアップを作成、変更、削除したり、バックアップからリストアしたりできます 
---
= ファイル共有とディスクをバックアップする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップポリシーを定義して、環境内にボリューム（ファイル共有およびディスク）のバックアップを作成したり、プライマリボリュームの複数のコピーをリモートで保持したりできます。


NOTE: ボリュームのバックアップポリシーを作成または編集すると、システムにバックアップが自動的に作成されます。NetApp Service Engineインターフェイスからバックアップを作成することはできません。バックアップAPIを使用して、ボリュームのバックアップを作成および管理できます。

詳細については、を参照してください link:seapiref_backups_apis.html["バックアップAPI"]

ソースボリュームのバックアップは、Flexサブスクリプションで有効になっているNetApp SnapMirrorテクノロジを使用して有効にします。詳細については、を参照してください link:index.html#flex-subscription["こちらをご覧ください"]。

ボリュームを作成または編集するときは、ボリュームのバックアップスケジュールを定義します。バックアップは意図した間隔で作成され、デスティネーションシステムに格納されます。バックアップが機能するためには、デスティネーション環境との間にSnapMirror関係を確立する必要があります。レプリケートされたファイル共有と異なるゾーンのディスクは、各クラスタの専用のバックアップ Storage VM （ Storage Virtual Machine （ SVM ）に格納されます。バックアップは、異なるゾーンにある 2 つの独立した ONTAP クラスタ間で実行できます。

NetApp Service Engine でサポートされる標準のバックアップポリシーは次のとおりです。

* アドホック
* 毎日
* 毎週
* 毎月


バックエンドで作成されるバックアップの場合'ボリュームは運用可能な状態にある必要がありますオブジェクトの状態の詳細については、「動作」（バックアップのソースオブジェクト）を参照してください。 link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["こちらをご覧ください"]。

NetApp Service Engine でサポートされている標準のバックアップポリシーに従っていないボリュームを使用することは可能です link:sewebiug_raise_a_service_request.html["サービスリクエストを提出します"] 問題を固定する * 非標準ボリューム * カテゴリ。

ファイル共有およびディスクに対して作成されたバックアップのリストは、「* Backups *」ページに表示できます。バックアップは選択したテナントに基づいて表示されます。



== バックアップポリシーまたはスケジュールを編集する

ファイル共有およびディスクを作成または編集するときに、それらのバックアップポリシーを定義できます。バックアップは、指定されたポリシーに基づいてバックエンドで作成されます。詳細については、を参照してください link:sewebiug_create_a_new_file_share.html["ファイル共有を作成します"] または link:sewebiug_create_a_new_disk.html["ディスクを作成します"]。

.手順
. Enable * Backup Policy * 」を選択します。
. バックアップゾーンと、アドホック、毎日、毎週、または毎月のいずれかの単位で作成するバックアップの数を指定します。
. [ 作成（ Create ） ] をクリックします。



NOTE: 既存のファイル共有またはディスクのバックアップポリシーを編集して、バックアップをスケジュールすることもできます。



== バックアップのソースを変更または切断します

ファイル共有またはディスクの選択したバックアップオブジェクトに対して、バックアップを無効にするか、ソースからバックアップオブジェクトの接続を解除して、孤立したバックアップにすることができます。ソースとの SnapMirror 関係を解除します。アドホック、毎日、毎週、または毎月のいずれかの単位で作成されるバックアップの数を変更することもできます。

.手順
. 左側のナビゲーションペインで、*バックアップ*をクリックします。環境内のすべてのオブジェクトに対して作成されたバックアップのリストを表示できます。
. リストでバックアップを探し（ボリューム名で検索）、行の末尾にある編集アイコンをクリックします。
. 必要に応じて、バックアップのソースおよび各タイプのバックアップの数を変更します。ソースボリュームとの SnapMirror 関係を解除するには、バックアップのソースを「 * None （ orphaned ）」に変更します。ソースボリュームが削除された場合でも、バックアップは孤立したバックアップとして保持されます。バックアップオブジェクトの状態が変化し、ソースボリュームのステータス（孤立または削除）が同じリストのソースボリューム名に追加されます。オブジェクトの状態については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["こちらをご覧ください"]
. [ 完了（ Done ） ] をクリックします。Snapshotが変更されます。ソースとの SnapMirror 関係を解除した場合、つまり、バックアップオブジェクトが孤立した場合は、「 * Backups * 」タブのソース名は「削除済み」と表示されます。



NOTE: Create Share/Edit ShareおよびCreate Disk/Edit Disk画面で、ボリュームの* Backup Policy *を無効にして、ソースボリュームとのSnapMirror関係を解除することもできます。



== バックアップとリストアのサポートを依頼

可能です link:sewebiug_raise_a_service_request.html["サービスリクエストを提出します"] 特定のリカバリポイントからファイル共有またはディスクをリストアする場合。

.手順
. 左側のナビゲーションペインで * support * を選択し、 * Service Requests * を選択します。
. [ 新しいサービスリクエスト ] をクリックします。
. サービスリクエストのカテゴリとして「 * バックアップリストア * 」を選択します。
. その他の詳細を指定して次に進みます。




== バックアップオブジェクトを削除する

未使用のバックアップボリュームを削除すると、ストレージスペースが増えます。削除されたソースのバックアップボリュームとリカバリポイントを削除するには、バックアップAPIを使用する必要があります。


NOTE: バックアップを削除すると、そのバックアップのすべてのリカバリポイントが削除されます。また、プライマリファイル共有またはディスクを削除した場合でも、バックアップは孤立したバックアップとして保持され、リストアのためのすべてのリカバリポイントが含まれます。
