---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone によってユーザの S3 キーが作成される 
---
= ユーザの S3 キーを作成します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ユーザの S3 キーを作成するには、このメソッドを使用します。

キーは作成後すぐにキャプチャしてください。キーの詳細を作成したあとで取得することはできません。



=== 手順

. を表示します link:sewebiug_view_a_list_of_users.html#view-a-list-of-users["ユーザリスト"]。
. 正しいサブテナントが選択されていること、および表示にユーザ（グループではない）が表示されていることを確認します。
. リスト内でユーザを検索し、そのグループの [ キー ] アイコンをクリックします。
+
リスト内の項目の操作の詳細については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["リストビューアクションをリスト表示します"]。

. Manage S3 Keys （ S3 キーの管理）ダイアログボックスが表示され、ユーザのキーのリストが示されます。
. ユーザに既存のキーがない場合は、 * S3 キーの作成 * をクリックしてフィールドを表示し、キーを作成します。
. キーを期限切れにする場合は、有効期限と有効期限を UTC で指定します。それ以外の場合は、これらのフィールドのデフォルト値のままにします。
. キーを作成するには、チェックマークをクリックします。S3 Key Details （ S3 キーの詳細）ダイアログボックスが開き、アクセスキーとシークレットキーが表示されます。
. 詳細をユーザーに通知する準備として、アクセスキーと秘密キーの両方をコピーします。
+
S3 の Key Details ダイアログボックスを閉じる前に、キーの詳細がキャプチャされていることを確認します。閉じた後、キーの詳細が隠され、キーを取得できなくなります。

. [* 閉じる * ] をクリックします。
. もう一度 * Close * をクリックして Manage S3 Keys ダイアログを閉じます。

