---
sidebar: sidebar 
permalink: sewebiug_modify_file_server.html 
keywords: netapp, keystone, modify, file, server, 
summary: ファイルサーバを変更します 
---
= ファイルサーバを変更します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既存のサーバには、次の変更を加えることができます。

. サーバ名を変更します
. サーバを CIFS 対応にし、 Active Directory のユーザ名とパスワード、 Active Directory ドメイン、 DNS サーバ、サーバ名（オプション）、および Active Directory の組織単位を指定します。Active Directory のクレデンシャルは、コンピュータを Active Directory ドメインに追加する権限があるユーザのものである必要があります。
. サーバをレプリケートするリージョンまたはゾーンを指定して、非同期ディザスタリカバリ DP を有効にします。



NOTE: 非同期ディザスタリカバリがすでに有効になっている場合は、無効にすることはできません。詳細については、を参照してください link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery["ディザスタリカバリ"]。

.手順
. を表示します link:sewebiug_view_servers.html#view-servers["[ ファイルサーバ ] リスト"]。
. リスト内のサーバを探し、そのサーバの [Edit] アイコンをクリックします。（リスト内の項目の操作の詳細については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["リストビューアクションをリスト表示します"]）。
. 必要に応じて変更します。を参照してください link:sewebiug_create_a_file_server.html["ファイルサーバを作成します"] を参照してください。
. [ 完了（ Done ） ] をクリックします。これにより、サーバを変更するジョブが作成されます。


.完了後
Modify Server は非同期ジョブとして実行されます。可能です

* ジョブリストでジョブのステータスを確認します。ジョブの追跡については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["こちらをご覧ください"]。
* ジョブが完了したら、サーバーリストでサーバーのステータスを確認します。

