---
sidebar: sidebar 
permalink: sewebiug_view_shares.html 
keywords: netapp, keystone, view, shares, 
summary: Keystone が共有を表示します 
---
= ファイル共有を表示します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
* Shares * リストに、選択したテナントに属するファイル共有が表示されます。リストを表示するには、メニューから * file services > Shares * を選択します。

既存の環境にすでに含まれており、NetApp Service Engineで設定されているStorage VMに属するファイル共有は、この画面に表示して、NetApp Keystone サブスクリプションサービスの一部として管理することもできます。NetApp Service Engine 以外でプロビジョニングされたファイル共有は定期的にインポートされ、該当するステータスコードがこのページに表示されます。

インポートしたファイル共有が NetApp Service Engine の許容可能な標準規格に準拠している場合、共有を動作可能にするために必要なすべてのパラメータが使用可能になります。インポートされたファイル共有は「 Operational 」ステータスで NetApp Service Engine から直接管理できます。ただし、一部の共有は NetApp Service Engine 上の既存の共有と同じ標準に含まれていない場合があります。インポート後、これらのファイル共有は「 Imported 」または「 Non-Standard 」ステータスで分類されます。ボリュームのステータスとそれらを運用するための手順については、を参照してください link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["オブジェクトの状態"]

共有リストには、各共有に関する簡単な情報が表示されます。リストの機能の使用方法の詳細については、を参照してください link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["リストビュー"]。

* 共有名
* サーバが配置されているサーバ
* 共有パス
* CIFS 共有パス（ DNS との統合による CIFS 共有のマウントに使用）
* サブテナント
* そのゾーンが存在します
* サービスレベル
* 動作状態（動作、更新、サポートへの連絡）
* 作成日

