---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Keystone Azure ボリュームを管理する 
---
= Azure ボリュームの管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このセクションでは、 Azure ボリュームを管理する方法について説明します。


NOTE: Azure Volumes を管理するには、顧客管理者アクセスが必要です。

ここでは、次の作業の実行方法について説明します。

* Azure ボリュームのリストを表示します。
* Azure ボリュームを追加
* Azure ボリュームの詳細を変更する。
* Azure ボリュームを削除する




== Azure ボリュームのリストを表示します

Azure Volumes のリストには、指定したサブテナントおよび場所に対応する Azure ボリュームプールのリストが表示されます。リストを表示するには、メニューから * file services > Azure Volumes * を選択します。

このリストには、各 Azure ボリュームに関する単純な情報が表示されます。各 Azure ボリュームの横にある操作アイコンを使用して、 Azure ボリュームを変更または削除できます。



== Azure ボリュームを追加

このセクションでは、 Azure ボリュームを追加する方法について説明します。

.作業を開始する前に
次のものが必要です。

* Azure ボリュームが属するサブテナント
* ANF アカウント
* Azure Virtual Network （ VNet ； Azure 仮想ネットワーク）とサブネット
* ボリュームを格納する容量プール
* ボリュームの名前
* ファイルパス
* ボリュームのクォータ（サイズ）


.手順
. メニューから * file services > Azure Volumes * を選択します。
. [ 作成（ Create ） ] をクリックします。
. Create Azure Volume ダイアログボックスで、サブテナント、 ANF アカウント、 VNet 、サブネットを指定します。 容量プール、ボリュームの名前、ファイルパス、およびクォータ。ボリュームを正常に作成するには、一意のファイルパスを入力してください。
. 必要に応じて、ボリュームにタグを追加します。
. [ 作成（ Create ） ] をクリックします。Azure ボリュームが作成されると、ボリュームの状態が「 S ucceeded 」に変わります（ Azure Volumes リストに表示可能）。




== Azure ボリュームの詳細を変更する

Azure ボリュームの詳細を変更するには、この方法を使用します。ファイルのパスとクォータを変更したり、タグを追加または削除したりできます。

.手順
. メニューから * file services > Azure Volumes * を選択します。
. リストから Azure ボリュームを探し、編集アイコンをクリックします。
. Azure ボリュームの管理ダイアログボックスで、必要な変更を行います。ファイルパスまたはクォータを変更する場合は、ファイルパスが一意であること、およびクォータがプール内の使用可能クォータを超えないことを確認してください。
. [ 更新（ Update ） ] をクリックします。




== Azure ボリュームを削除する

Azure ボリュームを削除するには、このメソッドを使用します。

.手順
. メニューから * file services > Azure Volumes * を選択します。
. リストから Azure ボリュームを探して、削除アイコンをクリックします。
. 削除の確認ダイアログボックスで、削除する Azure ボリュームの名前を入力します。
. [* 確認 *] をクリックします。

