---
sidebar: sidebar 
permalink: sewebiug_managing_azure_capacity_pools.html 
keywords: netapp, keystone, managing, azure, capacity, pools, 
summary: Keystone Azure 容量プールを管理する 
---
= Azure 容量プールの管理
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このセクションでは、 Azure の容量プールを管理する方法について説明します。


NOTE: Azure の容量プールを管理するには、顧客管理者アクセスが必要です。

ここでは、次の作業の実行方法について説明します。

* Azure 容量プールのリストを表示します
* Azure 容量プールを追加します
* Azure 容量プールの詳細を変更します
* Azure 容量プールを削除します




=== Azure 容量プールのリストを表示します

Azure 容量プールのリストには、指定したサブテナントおよび場所の容量プールのリストが表示されます。リストを表示するには、メニューから * file services > Azure Capacity Pools * を選択します。

このリストには、各 Azure 容量プールに関する単純な情報が表示されます。各 Azure 容量プールの横にある操作アイコンを使用して、 Azure 容量プールを変更または削除できます。



=== Azure 容量プールを追加します

このセクションでは、 Azure 容量プールを追加する方法について説明します。



==== 作業を開始する前に

次のものが必要です。

* 容量が属するサブテナント
* ANF アカウント
* サービスレベル
* 容量プールの名前
* プールのサイズ




==== 手順

. メニューから * file services > Azure Capacity Pools * を選択します。
. [ 作成（ Create ） ] をクリックします。
. Create Azure Capacity Pool ダイアログボックスで、サブテナント、 ANF アカウント、サービスレベル、名前、およびサイズを指定します。
. 必要に応じて、容量プールにタグを追加します。
. [ 作成（ Create ） ] をクリックします。容量プールが作成されると、状態が「 ucceeded 」に変わります（ Azure Capacity Pools リストで確認できます）。




=== Azure 容量プールの詳細を変更します

Azure 容量プールの詳細を変更するには、このメソッドを使用します。プールのサービスレベルのサイズを変更したり、タグを追加または削除したりできます。



==== 手順

. メニューから * file services > Azure Capacity Pools * を選択します。
. リストから Azure 容量プールを探し、編集アイコンをクリックします。
. Manage Azure Capacity Pool （ Azure 容量プールの管理）ダイアログボックスで、必要に応じて変更を行います。
. [ 更新（ Update ） ] をクリックします。




=== Azure 容量プールを削除します

Azure 容量プールを削除するには、このメソッドを使用します。



==== 手順

. メニューから * file services > Azure Capacity Pools * を選択します。
. リストから Azure 容量プールを探し、削除アイコンをクリックします。
. 削除の確認ダイアログボックスで、削除する Azure 容量プールの名前を入力します。
. [* 確認 *] をクリックします。

