---
sidebar: sidebar 
permalink: sewebiug_working_with_block_storage_overview.html 
keywords: netapp, keystone, working, block, storage, overview, 
summary: Keystone ブロックストレージの使用の概要 
---
= 概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ブロックストレージシステムでは、データストレージはそれぞれ一意の識別子で分割されます。NetApp Service Engine は、ブロックデータストレージをブロックストアと呼び、個々のコンポーネントをディスクと呼びます。

ブロックストアはサブテナントに属しており、ゾーン内に指定されています（サブテナントごとにゾーンごとに 1 つのブロックストア）。ブロックストアには、 iSCSI プロトコルまたは FC プロトコル経由のディスクへのアクセスに使用するネットワーク属性（ IP アドレスや VLAN ID など）があります。ディザスタリカバリ DP はブロックストアで有効にすることができます。詳細については、を参照してください link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery.html["ディザスタリカバリ"]。

ブロックストアを使用するには初期化する必要があります。ブロックストレージが使用可能で初期化されていない場合は、ディスク作成プロセスの一環としてブロックストアに最初のディスクを作成する前に初期化できます。

ディスクはブロックストア上に作成されます。ディスクには、容量や関連するサービスレベルなど、設定可能な多数の属性があります。などの DP オプション link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#snapshots["Snapshot"] および  ディスクに対して有効にできます。

ディスクへのアクセスはホストグループによって制御されます。ホストグループは、イニシエータのノード名で構成されます。 1 つ以上のホストグループをディスクにマッピングすることで、ディスクにアクセスできるイニシエータを定義できます。

ホストグループ

* プロトコルに固有です。次のいずれかです。
+
** FC プロトコルホストグループ： FC World Wide Port Name （ WWPN ；ワールドワイドポート名）のイニシエータで構成されます。たとえば、「 20:56:00:a0:98:5c:0d:da`) 」と入力します。
** iSCSI プロトコルホストグループ： iSCSI Qualified Name （ IQN ）のイニシエータで構成されます。たとえば、「 iqn.1998-01.com.vmware:esx2` 」と入力します。


* エイリアスとイニシエータのペアで構成されます。エイリアスを使用すると、イニシエータを簡単に識別できます。たとえば 'esxserver1' と入力します
* イニシエータなしで作成できます。空のホストグループはプレースホルダとしてディスクにマッピングできますが、ディスクにアクセスできるように完全に定義されている必要があります。ホストグループを使用すると、次のことが可能に
* 複数のディスクを同じイニシエータセットにマッピングしています
* 複数のディスクにわたってイニシエータのセットを更新する。


ここでは、次の項目について説明します。

* ホストグループの使用：
+
** ホストグループを表示します
** ホストグループを作成します
** ホストグループイニシエータを変更します
** ホストグループを削除する


* ディスクの使用：
+
** ディスクを表示します
** 新しいディスクを作成します
** Snapshot からディスクを作成します
** ディスクを変更します
** ディスクを削除します
** ディスクのアドホックスナップショットを作成します



