---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: サブネットを作成および削除します 
---
= テナントとサブテナントのネットワーク設定を定義する
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サービスプロバイダまたはパートナー管理者は、テナントのサブスクリプションゾーンに基づいてテナントのネットワーク設定を定義し、各ネットワーク設定に VLAN を割り当てることができます。また、同じゾーンおよびテナンシーに属する各 VLAN のサブネットを作成し、そのテナンシーのサブテナントに割り当てることもできます。

事前設定されたテナントネットワークでサブネットを作成する必要があります。サブテナントまたはエンドユーザがファイルサーバまたはブロックストアをプロビジョニングする場合は、サブネットが必要です。ファイル Storage VM とブロック Storage VM は ONTAP の IPspace によって所有され、ファイルおよびブロック Storage Engine のサブテナントによって所有されます。サブテナントレベルでネットワークの境界を定義すると、 NetApp Service Engine のサブテナントは、そのゾーンの 1 つの ONTAP IPspace にマッピングされます。これにより、リスクが解消され、 2 つの個別のサブテナントが同じ VLAN ID を選択して同じ IPspace で終了することがなくなります。

* 各ゾーンに複数のサブネットを作成できます。テナンシー内のゾーンごとに、 VLAN のリストが割り当てられています。これらすべての使用可能な VLAN について、対応するサブネットを作成できます。サブネットと VLAN の間には 1 対 1 のマッピングがあります。一方、 1 つのゾーンとサブネット間に 1 つの対多数のマッピングがあります。
* 1 つのテナントに、ゾーン内の使用可能な VLAN ごとに 1 つずつ、複数のサブネットを設定できます。ゾーンごとに 1 つのネットワーク構成の下に表示されます。
* 各ネットワークサブネットに設定できる VLAN は 1 つだけです。各ネットワーク構成には、使用可能な VLAN のリストが表示されます。
* サブテナントのゾーンと VLAN の組み合わせに対して作成できるサブネットは 1 つだけです。



NOTE: テナント管理者は、テナントのネットワーク設定とそのサブテナントのサブネットだけを表示できます。



== テナントのネットワーク設定を定義する

パートナー管理者は、テナントごとにネットワーク設定を作成できます。設定可能な一意の VLAN プールは、要件に基づいて各テナントに割り当てることができます。テナントが削除されると、関連付けられている VLAN がテナント VLAN プールに解放されます。

.作業を開始する前に
* テナントが作成されていることを確認します
* ゾーン、 VLAN 、およびポートオーバーライドの設定を理解しておく必要があります


.手順
. * Administration * > * tenants * から、必要なテナントを選択します。
. ネットワークアイコンをクリックします。テナントのネットワーク構成のリストが表示されます。
. [ ネットワークの作成 *] をクリックします。必要に応じて、ゾーン、 VLAN 、およびポートオーバーライドを指定します。
+

NOTE: ポートの上書きは、ゾーンの設定時にサポートチームによって設定されます。ポートの上書きを指定しない場合、ネットワークはデフォルトポートを使用し、そのテナント用の IPspace に新しい VLAN を作成します。

. [ 作成（ Create ） ] をクリックします。テナント用の新しいネットワーク構成がネットワーク画面に表示されます。


ゾーンのネットワーク設定が作成されている場合は、新しい VLAN をネットワーク設定に割り当てることしかできません。[*+*] アイコンをクリックして、 VLAN およびポートオーバーライドの詳細を追加します。[ 更新（ Update ） ] をクリックします。



== サブテナント用のサブネットを作成します

パートナー管理者は、サブテナント用のサブネットを * networks * > * subnets * から作成できます。サブネット定義には、 ONTAP に実装されている VLAN ID 、 CIDR アドレス範囲、およびルート仕様が含まれます。サブネットはテナントとゾーン内の VLAN にアライメントされます。1 つのゾーンに対して同じ VLAN を持つ 2 つのサブネットを作成することはできません。

.作業を開始する前に
* テナント用の VLAN とゾーンの設定が完了している必要があります
* 作成するサブネットの要件を確認しておく必要があります


.手順
. 必要なテナントを選択します。サブネットを作成するサブテナントは、このテナントの下に配置する必要があります。
. [ * networks * > * subnets * ] をクリックします。サブテナント用に作成されたサブネットのリストは、 * Subnets * ページで確認できます。
. [ サブネットの作成 *] をクリックします。
. サブテナント、ゾーン、サブネットの名前、 VLAN 、およびサブネットの CIDR を指定します。ルート仕様とタグを追加することもできます。
+

NOTE: ルート仕様では、 * Destination * は一意で、指定された VLAN の一部である必要があります。また、複数のルートで * Metric * に同じ値を設定できます。

. [ 作成（ Create ） ] をクリックします。



NOTE: サブネットは編集または削除できません。編集できるのは、関連付けられているタグだけです。
