---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Keystone サブスクリプションを管理する 
---
= サブスクリプションの管理
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サブスクリプションの管理には、 NetApp Keystone Flex サブスクリプション（ Flex サブスクリプション）サービスとテナントサブスクリプションサービスへのサービスレベルの割り当て、または NetApp Service Engine インターフェイスを使用したサービスレベルへの容量の割り当てと変更が含まれます。

サービスプロバイダ / パートナーとネットアップの間の関係によって表される Flex Subscriptions は、サービスプロバイダとそのテナントとサブテナント（エンドユーザ）との関係を表します。ネットアップ管理者または GSSC がパートナー様とテナント向けの Flex サブスクリプションサービスを作成する場合、ストレージの割り当てが完了していることを意味します。ただし、サービスレベルが作成され、対応する容量の割り当てが完了していないかぎり、サブテナントやエンドユーザはストレージを使用できません。パートナー管理者は、 Flex サブスクリプションとテナントサブスクリプションのストレージを管理できます。テナント管理者は、テナントサブスクリプションの詳細とテナント独自のテナントサービスのみを表示できます。



== Flex サブスクリプションの管理（ Keystone サブスクリプション）

パートナー管理者は、 * サブスクリプション * > * Keystone サブスクリプション * から Flex サブスクリプションサービスを表示および管理できます。* Keystone サブスクリプション * は、ネットアップ管理者がパートナー様向けに作成した Flex サブスクリプションサービスです。パートナー管理者は、 Flex サブスクリプションサービスを表示して、次のサービスリクエストを作成できます。

* サブスクリプションの容量を増やします
* サブスクリプションへのサービスの追加（サービスレベルと容量の割り当て）


サービスリクエストはサポートチームが受け取り、対応します。

サブスクライブしているデータ保護サービスと高度な保護サービスを別々のタブで表示および管理することもできます。



=== サブスクリプションの容量を増やします

拡張要件を満たすために、サブスクライブされている任意のサービスレベルのコミット済み容量を増やすことができます。

.手順
. 容量を増やすサブスクリプションをドロップダウンメニューから選択します。
. 目的のサービスレベルの [ 容量の増加 ] をクリックします。
. 必要な容量（ TiB ）を指定します。
. [* 確認 *] をクリックします。




=== サービスをサブスクリプションに追加します

サービスをサブスクリプションに追加できます。サービスの追加には、サブスクリプションにサービスレベルを割り当て、同じサービスレベルの容量を指定します。

サブスクリプションには、それぞれのパフォーマンスレベルが 1 つしか含まれない場合があります。たとえば、サブスクリプションに Extreme と Standard のサービスがすでに含まれている場合は、 Premium サービスまたは Block サービスを追加できます。

.手順
. 容量を増やすサブスクリプションをドロップダウンメニューから選択します。
. [ サービスの追加 ] をクリックします。
. 追加するサブスクリプションサービスをドロップダウンメニューから選択し、サービスレベルにコミットする容量（ TiB ）を追加します。
. [* 確認 *] をクリックします。



NOTE: 高度な階層化やプレミアム階層化に登録している場合は、既存のサブスクリプションのパフォーマンスレベルを編集し、階層化に対応したパフォーマンスレベルを選択できます。階層化対応のパフォーマンスレベルから階層化非対応のパフォーマンスレベルへの移行も可能です。



== テナントサブスクリプションを管理します

パートナー管理者の場合は、テナントサブスクリプション * > * テナントサブスクリプション * からテナントサブスクリプションを作成、表示、更新できます。テナント管理者の場合、表示できるのはサブスクリプションだけです。



=== テナントサブスクリプションを作成します

テナントの新しいサブスクリプションを作成できます。

.手順
. [ 新規サブスクリプション ] をクリックします。
. 地域、ゾーン、サブスクリプション期間、レートプラン、およびその他の詳細を指定します。テナントサブスクリプションは、選択したゾーンに基づいて Keystone サブスクリプションに割り当てられます。これは、 Keystone サブスクリプションがそれぞれゾーンに関連付けられているためです。
+

NOTE: 重複するサブスクリプションは作成できません。指定した開始日よりも前の日にサブスクリプションが開始されるため、開始日は少なくとも翌日にする必要があります。また、現在の日付から 30 日以内にする必要があります。

. [ 作成（ Create ） ] をクリックします。


サブスクリプションを削除することはできません。既存のテナントサブスクリプションを編集して新しいサービスレベルを追加したり、サービスレベルのコミット済み容量を増やしたり、サブスクリプションにタグを追加したりすることのみができます。
