---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: ネットアップサービスエンジンパートナー、サービスプロバイダの職務 
---
= サービスプロバイダと顧客の役割と運用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サービスプロバイダまたはパートナー（同じ意味で使用）のロール、またはお客様またはテナント（同じ意味で使用）の管理者に基づいて、 NetApp Service Engine Web ポータルの表示と機能が決定されます。



== サービスプロバイダ管理者として実行できるアクティビティ

サービスプロバイダ管理者はマルチテナント環境で、 NetApp Service Engine の Web UI を使用して、独自のサブスクリプションを使用しているお客様のプロビジョニング、レポート作成、課金、および管理を実行できます。次の機能を実行できます。

* Keystoneサブスクリプションサービスの一部としてサブスクライブおよびプロビジョニングされたストレージを表示します。
+

NOTE: サービスとして提供される容量は、ネットアップから購入するよりも多くなります（オーバーサブスクリプション）。テナントサブスクリプションは現在のKeystoneサブスクリプション期間を超えることができますが、サブスクリプションの作成時およびダッシュボード/レポートに警告が表示されます。

* テナント、サブテナントの作成、表示、変更、削除 ユーザの権限が必要です。
* サブスクリプションのゾーンとリージョンを表示します。
* Keystoneサブスクリプションサービスで複数のテナントを管理およびホストする：テナントサブスクリプションを作成および管理し、独自のKeystoneサブスクリプションの詳細を表示します。
+

NOTE: テナントサブスクリプションは、対応するゾーンとKeystone Keystoneサブスクリプションに基づいて作成できます。Keystoneサブスクリプションのサブスクリプション容量に基づいて提供されるサービスレベルに従って作成される。

* テナント用に各ストレージタイプをプロビジョニングするためのネットワーク要件を確認したら、ファイルサーバまたはブロックストアを作成し、ブロック、ファイル、およびオブジェクトストレージを初期化します。
* テナントのサブネットを作成して管理することもできます。
* Keystoneサブスクリプションの一部として作成されたファイル共有、ディスク、バケットを表示できます。オブジェクトストレージグループとユーザの作成と管理も行います。
* Keystoneサブスクリプション、テナントサブスクリプション、およびすべてのテナントの使用状況に関するレポートを作成して、それぞれの課金システムや評価システムで使用できるようにします。
* すべてのテナントとお客様、および登録またはプロビジョニングしたストレージについてのみ、請求とレポートを表示する。
* OpsRamp / GSSC に統合された独自のサービス要求ツール（パートナー / サービスプロバイダの）でお客様から寄せられたサービス要求を表示および管理します。




== 顧客 / テナント管理者として実行できるアクティビティ

テナント管理者は、自分のテナンシーのサブスクリプションの詳細を表示したり、サブテナントに対する管理タスクを実行したりできます。次の操作を実行できます。

* テナントサブスクリプションサービスに登録され、プロビジョニングされたストレージを表示します。
* テナントのサブテナントを管理および編集できます。
* ゾーン、リージョン、サブテナント、およびサブネットを表示します。
* サービスプロバイダによって作成されたファイルサーバを表示します。
* ファイル共有、ディスク、およびバケットを作成し、サービスレベルを割り当てます。
* テナントおよびサブテナントのレポートを* Reports > Capacity Utilization *で表示し、テナントおよびサブテナントに登録またはプロビジョニングされているストレージの消費データのみを表示します。
* テナントおよびサブテナントのレポートを* Reports > Performance *で表示し、各登録サービスおよびアドオンサービス（データ保護および高度な保護）のテナントのパフォーマンスとサービスコンプライアンスを表示します。
+

NOTE: 追加のサブスクリプションの場合は、サービスリクエストツールを利用できます。


