---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: ネットアップサービスエンジンパートナー、サービスプロバイダの職務 
---
= サービスプロバイダと顧客の役割と運用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サービスプロバイダまたはパートナー（同じ意味で使用）のロール、またはお客様またはテナント（同じ意味で使用）の管理者に基づいて、 NetApp Service Engine Web ポータルの表示と機能が決定されます。



== サービスプロバイダ管理者として実行できるアクティビティ

サービスプロバイダ管理者はマルチテナント環境で、 NetApp Service Engine の Web UI を使用して、独自のサブスクリプションを使用しているお客様のプロビジョニング、レポート作成、課金、および管理を実行できます。次の機能を実行できます。

* Flex Subscription サービスの一部として登録およびプロビジョニングされているストレージを表示します。
+

NOTE: サービスとして提供される容量は、ネットアップから購入するよりも多くなります（オーバーサブスクリプション）。テナントサブスクリプションは現在の Flex サブスクリプション期間を超えて延長できますが、サブスクリプションの作成時およびダッシュボード / レポートに警告が表示されます。

* ゾーン、リージョンの作成、表示、変更、および削除 テナント、サブテナント、ユーザ
* Flex サブスクリプションサービスで複数のテナントを管理およびホストします。テナントサブスクリプションを作成および管理し、独自の Flex サブスクリプションの詳細を表示します。
+

NOTE: テナントサブスクリプションは、対応するゾーンと Keystone Flex Subscriptions に基づいて作成できます。これらは、 Flex サブスクリプションのサブスクライブ容量に基づいて提供されるサービスレベルに従って作成されます。

* テナント用に各ストレージタイプをプロビジョニングするためのネットワーク要件を確認したら、ファイルサーバまたはブロックストアを作成し、ブロック、ファイル、およびオブジェクトストレージを初期化します。
* テナントのサブネットを作成して管理することもできます。
* Flex サブスクリプションの一部として作成されたファイル共有、ディスク、およびバケットを表示します。オブジェクトストレージグループとユーザの作成と管理も行います。
* NetApp Keystone フレックスサブスクリプションに対する消費レポート、テナントサブスクリプション、およびすべてのテナントの使用状況を、それぞれの課金システムおよび評価システムで使用するために作成します。
* すべてのテナントとお客様、および登録またはプロビジョニングしたストレージについてのみ、請求とレポートを表示する。
* OpsRamp / GSSC に統合された独自のサービス要求ツール（パートナー / サービスプロバイダの）でお客様から寄せられたサービス要求を表示および管理します。




== 顧客 / テナント管理者として実行できるアクティビティ

テナント管理者は、自分のテナンシーのサブスクリプションの詳細を表示したり、サブテナントに対する管理タスクを実行したりできます。次の操作を実行できます。

* テナントサブスクリプションサービスに登録され、プロビジョニングされたストレージを表示します。
* テナントサブスクリプションサービスで複数のサブテナントとユーザを管理およびホストする。
* ゾーン、リージョン、テナンシー、およびサブネットを表示します。
* ファイルサーバを表示し、ファイル共有、ディスク、およびバケットを作成する。
* テナントとサブテナントのレポートを作成して、テナントとサブテナントに登録またはプロビジョニングされているストレージの消費データのみを表示します。
* サービスプロバイダのサービスリクエストツール内でサービスリクエストを発行および更新します。
+

NOTE: 追加のサブスクリプションの場合は、サービスリクエストツールを利用できます。


